### ISSUE TITLE
Use some kind of blockchain for aliases.

### ISSUE THREAD

**Issue by Jookia** [irungentoo/toxcore#1005]
Currently the idea of federated systems like toxme.se to provide aliases for aliases doesn't let the user have control of their aliases the same way they have control in their IDs, and worse, allows manipulation if people rely on DNS to look up toxme.se or a certificate authority to prove its authenticity.

Having some kind of blockchain that users who really wanted to stay distributed could look up for an alias, or having federated services like toxme mine and handle their own blocks of aliases but without going through DNS would create a system not prone to these attacks.

**Comment by ulrichard** [comment]
My vote for a namecoin integration similar to PyBitmessage.
It doesn't force anybody to use namecoin. People can use whatever means to get their Ids to their friends. But namecoin is just the most secure and convenient means that I'm aware of.

**Comment by LuccoJ** [comment]
It would be nice to have a system that doesn't actually require paying for getting an ID... or maybe one where CPU mining is cheap enough that you could quickly get the coins to do that by mining.

**Comment by GrayHatter** [comment]
No one in #tox-dev seems to like this idea enough to argue for it, so I'm going to close this until someone actually proposes an actual implementation/spec 

Don't take this as a closing of the idea of name support in toxcore, just that no one (yet) wants to do it with a blockchain.
