### ISSUE TITLE
Groups (not chats)

### ISSUE THREAD

**Issue by Jookia** [irungentoo/toxcore#1006]
Right now the only form of groups are group chats. It'd be nice to be able to have groups of people synchronized between people, and run group chats or group calls to these groups. A really nice side effect of this would be plugins dealing with a distributed social net, such as forums, file systems, VPNs, etc.

**Comment by GrayHatter** [comment]
@irungentoo close as replaced by new groupchats, non-specific, and wontfix

@* if you have any actual issues to be fixed open a new issue(s) with discriptive problems that have actual solutions
