### ISSUE TITLE
Mailing list for all Tox-related discussions?

### ISSUE THREAD

**Issue by v2e** [irungentoo/toxcore#1009]
Hello!
You probably heard that from August 1, 2014, many Skype clients for GNU/Linux stopped connecting to
servers. It happened to me as well. So I recalled that I had read about Tox some months before that. I decided to check its current state.
I installed uTox on my Gentoo machine, and to my great surprise, it just works out of the box! :)

I've been searching for a free replacement to Skype for several years, with litle luck. So, it is a great opportunity for me to switch from Skype to Tox. However, in order to do that I have to switch all my Skype contacts to Tox also. This is hard, but possible. The major problem I see here is that both Venom and uTox that I tried, are too weak for most people to use.

So I decided to ask here if there is a centralized mailing list for all Tox-related stuff (the core libraries, GUI clients, packages for different operating systems an so on). If there is no such ML, maybe it is worth creating one?

I know about IRC channel, but the mailing list seems more convenient for the community-based support and discussions. Also, the mailing list may be archived for the future indexing in search engines, and the thread-based sorting is much easier to use that parsing the IRC-chat.

I think, mailing list could move some load from the Tox developers to Tox community, like in LibreOffice or similar MLs, where there are much more users than developers usually answering to each other's questions.

What do you think about that?

Regards,
  Vladimir

**Comment by zetok** [comment]
since apparently toxcore isn't a place to discuss things not related to it: https://github.com/Tox/Tox-Foundation-Discussion/issues/3

@irungentoo this issue can be closed, right?
