### ISSUE TITLE
[idea] Tox ID is unfriendly; Proposal TIDY

### ISSUE THREAD

**Issue by haneefmubarak** [irungentoo/toxcore#1041]
Currently, as per the [Tox Docs](https://libtoxcore.so/core_concepts.html) (I love that rhyme!), a Tox ID is a 76 character hex string, consisting of a 256 bit (64 character) Public Key, a 32 bit (8 character) `nospam` integer, and a 16 bit (4 character) checksum integer:

![Tox ID](https://libtoxcore.so/_images/public_key_bd.png)

This is rather unfriendly. Imagine telling your friend that you're some long-ass string of numbers. Think she will remember that? Hell, how long will it take her to even write down? Instead, I propose a different ID system:

```
Format:

+------------------------------------------------------------------------------------------------------------------------------------------------------+
|username:firstChars (BLAKE2 ("hex (PubKey)"), 8), :hex (nospam):firstChars (BLAKE2 ("username:firstChars (BLAKE2 (hex (PubKey)), 8):hex (nospam)"), 4)|
+------------------------------------------------------------------------------------------------------------------------------------------------------+

Example (PubKey = random hex string):

+------------------------------------+
|haneefmubarak:D6C4EE91:2A7F9D7B:99bc|
+------------------------------------+

(BLAKE2 ("haneefmubarak:D6C4EE91:2A7F9D7B") = 99bcc8731b5859dab0b951bf8ea571eca3b3865a4284aedd64f80059663cccfb47f8c0588248ed4d94b346fd89885d9fb5f936d627b9c01a2e96006e96295cfa)
```

I hereby dub this `TIDY` ('T' for 'Tox', 'IDY' for how 'ID' is usually pronounced - hey we have a word!). 

IMHO, that seems a lot better. Instead of having to keep 76 weird characters (to an average user), you only need the person's username (unchangeable w/o creating a new key - smart workaround available) plus 24 weird characters.

That's small enough to even fit on a business card.

Now, behind the scenes, we could use a DHT to store the PubKeys. To look up a PubKey, you would use the username and the first 8  characters of the hash of the PubKey in hex form (ie: `haneefmubarak:D6C4EE91`) as the key, with the PubKey being the value. Everything else would work as is already implemented.

Meanwhile, this allows multiple users to have the same username, because the hash of the PubKey is also relevant. I recommend the following requirements for a username:

 - 4 - 40 characters
 - alphanumeric only
 - case sensitive

Similar to before, a user is still able to change their `nospam` at any time, and the checksum (BLAKE2) will change accordingly.

---

Now, while the username must be constant, I mentioned a workaround. A user who wishes to change their username could generate a new TIDY (ie: new username, PubKey, and `nospam`). Then, their client could give their new TIDY and details to anyone who connects to their old TIDY with a valid `nospam`. Essentially, any users connecting to that user would be redirected by that user's client, thus minimising the effect of a username change.

---

Enough of me talking though. What do you guys think?

**Comment by sergeevabc** [comment]
ToxID is 76 chars, which is definitely _uglier_ than prominent Bitcoin (34) or Minilock (45). For example, Thunderbird breaks signature part ```ToxID: <...>``` into aesthetically unpleasing two lines. Has this been an advantage in terms of security, yet it is useless fat. And Tox DNS gives no benefit for an average user without custom domain, who use gmail or tutanota. Moreover services like Toxme.io, which bind ToxID to e-mail looking address, give birth to even more confusion.
