### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by dubslow** [irungentoo/toxcore#1054]
https://gist.github.com/dubslow/b97e9ef861b3c6c6dce6

Run like so:

git pull master
./autogen.sh
./configure
make
make check

**Comment by urras** [comment]
Also see #1248

**Comment by urras** [comment]
it looks like multiple issues are causing the tests to fail

**Comment by GrayHatter** [comment]
@dubslow if this still happens, reopen tag me, and supply some more distro information
