### ISSUE TITLE
Maximum number of members in a Group

### ISSUE THREAD

**Issue by shgaurav77** [irungentoo/toxcore#1065]
What should be the limit of maximum members in a group. Currently since a P2P connection is established  with different members of a group. What would happen if I have 1000s of members in a group. It may have an adverse impact on client.
Any thoughts on this or can we have sort of multicasting in groups

**Comment by GrayHatter** [comment]
@irungentoo replaced by new group chats

**Comment by ProMcTagonist** [comment]
@GrayHatter have they merged?

**Comment by suhr** [comment]
No, they ain't.
