### ISSUE TITLE
feature request: send voice clips

### ISSUE THREAD

**Issue by aaannndddyyy** [irungentoo/toxcore#1080]
it would be a nice feature to be able to send voice clips just like in whatsapp and other apps.

why voice clips and not a call?
because the other peer may be afk and I simply want to leave a message in voice format.
or I simply don't want a full-scale call.

why toxcore?
Just like with avatars, this is a feature that all clients which support it should handle in a compatible way. so the signalling and transfer of voice clips should be standardized. for transfer the same mechanisms as file transfer could be used, so that any client would be able to receive them.

**Comment by GrayHatter** [comment]
client feature not core

**Comment by ProMcTagonist** [comment]
But you said that FILE_KIND requires core changes?

**Comment by GrayHatter** [comment]
Trivial, PR coming soon.

**Comment by ProMcTagonist** [comment]
<3

**Comment by GrayHatter** [comment]
#1460
