### ISSUE TITLE
Tox Slogan

### ISSUE THREAD

**Issue by Proplex** [irungentoo/toxcore#1083]
I really hate to put this here, but it's likely that this is the place where it'll get the most exposure.

We're in the process of redesigning/touching up some Tox client designs and it really struck me that we don't have a really quick, simple slogan. We've been using "A new kind of instant messaging" for a while but in no way is that quick, nor is it particularly interesting. Other services-that-shall-not-be-named have pretty good taglines, and I think we should start brainstorming one.

Any ideas? Probably keeping it to a 2-5 (2 being idea) word catchphrase would be best.

**Comment by deavmi** [comment]
Tox gets you laid

**Comment by deavmi** [comment]
Speak Freely sounds great.

**Comment by urras** [comment]
:+1: Speak Freely

**Comment by urras** [comment]
I'm still gonna have to go with "Secure messaging for everyone", since we already use it. Also, it sounds pretty good too.

**Comment by wiseoldman95** [comment]
"Speak freely" is easily confused with free as in price.

**Comment by stqism** [comment]
Would be fairly hard to deny that Tox is free as in price. 

Can't say the majority of computer users know what "free as in freedom" means.

**Comment by deavmi** [comment]
Yeah

**Comment by deavmi** [comment]
The majority doesn't know RMD

**Comment by deavmi** [comment]
* RMS

**Comment by wiseoldman95** [comment]
>Can't say the majority of computer users know what "free as in freedom" means. 

So, for most users, "Speak freely" mentally degrades into "Speak at no cost".

Is "speak at no cost" really is the hallmark of Tox?

**Comment by stqism** [comment]
Speech freely isn't even our slogan.

**Comment by ameenross** [comment]
It's still "Secure messaging for everyone", isn't it? I do feel there is room for improvement there.

**Comment by mannol** [comment]
How about using hastags to appease the simpleminded:
Tox - #FreeSpeech
Tox - #SayNoToNSA
Tox - #YesAllGoys
etc.?

**Comment by ameenross** [comment]
Wanted to put another one out there that just popped up in my head:

Tox - Outspoken

**Comment by deavmi** [comment]
Hashtags looks very appealing and sounds so too.

**Comment by deavmi** [comment]
But then again for a slogan in the app I would use Speak Freely. Just put
the hashtags on the site's homepage. As something that gets the user
intrigued.

**Comment by dfortner** [comment]
>hashtags
Jeez, where's @Proplex when you need him?
This project is going to shit.

**Comment by deavmi** [comment]
Lol @dfortner I see what you mean.

**Comment by deavmi** [comment]
Lol. I am in South Africa.
![](http://imgur.com/im6qbpS)
What about "Global Secure Messaging"?

**Comment by deavmi** [comment]
Speak freely is taken. At least we can avoid DCMA shits.
