### ISSUE TITLE
Request: Get ID from already-accepted friend

### ISSUE THREAD

**Issue by kyanha** [irungentoo/toxcore#1088]
I need to obtain the ID of an already-accepted friend, so that I can add them to my phone from my computer.  The front-end I use is uTox, and I went to open this request there, but https://github.com/notsecure/uTox/issues/325 says that toxcore itself does not support this need.  So, I am raising the issue here.

**Comment by codedust** [comment]
The friend sharing issue has been discussed in #1350.
However, clients should provide an easy option to compare Tox IDs IRL.
