### ISSUE TITLE
Mesh networks

### ISSUE THREAD

**Issue by HostFat** [irungentoo/toxcore#1097]
What do you think about adding the ability to make mesh networks as FireChat advertise itself as able to do?
(which in reality it seems not: http://forum.opengarden.com/discussion/1387/china-does-not-work)

**Comment by zetok** [comment]
@GrayHatter I think that this should be re-opened, given that this is a feature request, or, if it's not going to be implemented, could you say why? Is it out of toxcore's scope?

**Comment by quininer** [comment]
I look forward to when I can not use the Internet, I can still use Tox. ;)

**Comment by codedust** [comment]
In Germany, there is a non-commercial initiative for free (libre) wireless mesh networks, called [Freifunk](https://freifunk.net/en/). There are similar movements in many countries all over the world. It would be great if Tox would be still usable even if the "traditional" internet infrastructure of an entire city is down.

**Comment by GrayHatter** [comment]
I'm going to close this one again because tox is built on top of IP, while this might be a nice plugin, it would require a whole rewrite of toxcore. So I believe that it's outside of the scope of this repo.

Anyone want to argue against my conclusion?

**Comment by LuccoJ** [comment]
@GrayHatter usually, mesh network (including certainly the mentioned Freifunk) are most definitely also built on top of IP... it's not like they're a wholly different thing. Internet stacks are used on them, it's "just" that the routing is done differently.
I'm not really sure what, if anything, would need to be changed in Tox to support this kind of mesh network, though. It could work out of the box already, provided you have some in-mesh IP addresses of Tox nodes to bootstrap from.
