### ISSUE TITLE
[Regression] Tox doesn't work correctly on localhost

### ISSUE THREAD

**Issue by zetok** [irungentoo/toxcore#1118]
Since some time clients I've been running are unable to create localhost connections, for some reason they seem to be using TCP to communicate..

Clients running on localhost don't connect directly, files that are sent between them go outside of LAN, which wasn't the case time ago.

This deteriorates UX, since speeds on LAN/localhost are usually much higher than speeds when things are relayed through TCP relay.

Please fix.

**Comment by fbis251** [comment]
@zetok Did you mean that it doesn't work on a LAN? If so I am also having this issue. Could one of the developers provide some guidance on how to debug this issue? Thanks.

**Comment by zetok** [comment]
It seems to work much better now (i.e. qTox instances were able to connect over UDP on localhost), thus closing this issue.

There is still small issue though, in case where clients lose connectivity between themselves and reconnect using TCP.

If you still experience problem with clients not being able to talk to each other over UDP on localhost, please comment for reopen.
