### ISSUE TITLE
Pls. find a way to add the "Odigo Messenger" Sonar function !!!

### ISSUE THREAD

**Issue by AIFortress** [irungentoo/toxcore#1126]
For those that don't know what Odigo Messenger is: http://en.wikipedia.org/wiki/Odigo_Messenger
The sonar function from my memory is the ability to search while surfing on a website for users of the same program with the same interests as you. 
As the Tox have group chat  function this will greatly enhance the users experience with the program!
I am sure that It will be hard to do because of a ton of security problems, but the challenge is worth it.
Even if is only possible to be implemented, only as a scaled down version without the Interests filters, emoticons and personal profiles...

**Comment by GrayHatter** [comment]
@irungentoo close, stale, wontfix, security issues
