### ISSUE TITLE
Waiting to pickup duration

### ISSUE THREAD

**Issue by darkman088** [irungentoo/toxcore#1130]
Hello,

I hope that I am posting in the correct thread....
My experience with uTox and qTox shows, that when initiating a voice or a video call, the other party has a very short time to pick up, otherwise the call is being missed. I have posted this and guys told me, that this is a tox core issue. So, I am kindly asking you, whether it would be possible to let the line ring much longer, like for example at least 3 times more than the current time...

Thanks a lot !!!

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it's not a toxcore issue.
