### ISSUE TITLE
Adding users through group chats

### ISSUE THREAD

**Issue by TheLastProject** [irungentoo/toxcore#1135]
Toxcore should support adding users through group chats. The basic idea would be like this:

As seen to the end user:
First, the user clicks tox_user's nickname and selects "add as friend".

Then, tox_user gets a "friend invite". This isn't a true friend invite, but looks the same. When accepted, it sends the public key to the user sending the initial invite and adds them using the tox_add_friend_norequest function. The initial invitee then receives the public key, and adds this person using the tox_add_friend_norequest function.

At this point, both users added each other through a group chat.

The hard part is properly exchanging the Tox ID. Perhaps someone has a suggestion that would be easier to implement.

**Comment by GrayHatter** [comment]
@irungentoo close as fixed in new groupchats
