### ISSUE TITLE
Cannot install toxic from https://repo.tox.im/rpm/ on Fedora

### ISSUE THREAD

**Issue by Stevko-sk** [irungentoo/toxcore#1140]
Package toxic from repo https://repo.tox.im/rpm/ depends on packages libconfig9, libalut0, libncursesw5 and libnotify-bin. Fedora does not include packages with these names and therefore toxic cannot be installed. Fedora does, however, have packages libconfig, freealut, ncurses-libs and libnotify, which might provide same things (this should be checked).
This issue affects also tox-bootstrapd.

**Comment by mzdunek** [comment]
same here

https://repo.tox.im/rpm/repodata/repomd.xml: [Errno 12] Timeout on https://repo.tox.im/rpm/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')

it looks like repo is unavailable

**Comment by dfortner** [comment]
>Please file all bugs here: http://tox.lighthouseapp.com/projects/123754-tox/tickets

Tox wastes money with Lighthouse and complicating users' lives instead of simply using Github? I can't believe this...
Where's the old Public Relations people? The waste of money and complication of supposedly simple things is getting completely out of hand!

**Comment by stqism** [comment]
@dfortner: Lighthouse is free for FOSS projects.

**Comment by dfortner** [comment]
It's still bad for users that have to face a completely different interface, create an account somewhere else, leave Github, duplicate issues already posted here, etc. Really not good and unnecessary.

Where's the Public Relations Tox Manager? @Proplex right? He used to do a fine job and current Public Relations is truly horrible.

**Comment by dfortner** [comment]
So...?

**Comment by bitchecker** [comment]
https://github.com/Tox/toxic/issues/306#issuecomment-76698792

**Comment by urras** [comment]
Sorry for the inconvenience everyone, I thought this was fixed months ago. We're working to fix Toxic's RPM, but since this is a Toxic issue, can this issue be closed? We can move the conversation to https://github.com/Tox/toxic/issues/306
