### ISSUE TITLE
bootstrap server in mesh networks/darknets

### ISSUE THREAD

**Issue by kpcyrd** [irungentoo/toxcore#1149]
I intend to setup a bootstrap server on a mesh network. We're using private IP ranges, so most clients are unable to contact the bootstrap server. They'd be incredibly useful in the case of an internet shutdown.

I'd like to start a discussion if those servers can be included in the tox bootstrap server list.

**Comment by gjedeer** [comment]
@kpcyrd are you talking about cjdns?

Tox clients generally currently lack agility when it comes to bootstrapping. The ones which I've examined come with a list of bootstrap nodes baked into their binary and don't seem to save the peers they discovered.

If they did that, it would be easy to create a tool for adding your own bootstrap nodes without the need to recompile clients. You could also ship the bootstrap nodes file to other users of the meshnet.

**Comment by fcore117** [comment]
manual bootstrap file is needed for sharing updated nodes and even avoiding filtering by great firewalls that could ban all official nodes.

**Comment by kpcyrd** [comment]
@gjedeer yes

My ideas was to bake those bootstrap nodes into the official tox binary. If this network is available, they'd connect. If it isn't, they won't. I'm asking for opinions if such a PR should be merged.

**Comment by gjedeer** [comment]
Sorry for OT, then

**Comment by dubslow** [comment]
The save file containing your long term key also contains your friends' most recent node information, so once you've bootstrapped once, you can likely remain connected (as long as your friends don't change much/you go online often). Still though, the bootstrap nodes are in fact baked in currently.

**Comment by suhr** [comment]
Somewhat related: https://github.com/irungentoo/toxcore/issues/942

**Comment by JacobHenner** [comment]
This would be excellent for cjdns. How would a client handle references to public IPs in the DHT? Attempt to connect to them by regular means, or avoid them entirely? What if the client only had access to the mesh network, and not the standard internet?

**Comment by zetok** [comment]
@kpcyrd clients like Toxic and qTox allow to use custom bootstrap nodes via config file - you can use those to add bootstrap nodes of your darknet `:)`

As for including them in binary - not very likely, since they would be useless for >99.999% of people using Tox, and as such they would only hinder bootstrapping process.

@GrayHatter I think that this issue can be closed, given that toxcore has nothing to do with providing/embedding bootstrapping nodes in clients.

**Comment by timofonic** [comment]
Nodes? Bootstrapping? This reminds me of emule. Is this really resilient against firewalls and censoring?

Why not part of toxcore? I consider anonymity, antu-censoring and not depend on even official Internet as part of security.

**Comment by kpcyrd** [comment]
@timofonic This issue was mostly a meta-issue to get opinions on how something like that should be handled.

You always need a way to find your first nodes before you can learn other nodes from them. The list of bootstrapping nodes got moved to a [wiki][1] in the meantime. You could filter them on the firewall in theory (not sure if tox saves the list of nodes it learned between restarts).

[ipfs](/ipfs/ipfs) runs partly on cjdns (see h.ipfs.io), but they also haven't added fc00::/8 addresses to their config yet, so you always need regular internet until you've learned cjdns from them.

There are some networks around which support cjdns, [freifunk hamburg][2] being one of them. If this change gets consent you could just `pacman -S toxcore cjdns`, cjdns autodiscovers nearby nodes to peer with and you could use tox without being connected to regular internet. Assuming we host a bootstrap server on the directional radio network tox would still be fully functional in case of an internet shutdown (for your contacts inside hamburg, at least).

(Disclaimer: I'm working on both projects)

[1]: https://wiki.tox.chat/doku.php?id=users:nodes
[2]: https://map.hamburg.freifunk.net/
