### ISSUE TITLE
Bad permanence in tcp mode

### ISSUE THREAD

**Issue by youtux** [irungentoo/toxcore#1166]
Contacts disappearing / re-appearing in 5 minutes intervals when operating in 
TCP mode.

when using the toxic client on a quasi-"TCP only" network, letting tox operate 
in TCP-only mode, I see the following behaviour:
UDP disabled
No avatar set.
DHT connected
DHT disconnected. Attempting to reconnect.
DHT connected
12:05:14 --> GroupBot has come online
12:05:36 <-- GroupBot has gone offline
12:05:55 --> GroupBot has come online
12:10:33 <-- GroupBot has gone offline
12:10:56 --> GroupBot has come online
12:15:33 <-- GroupBot has gone offline
12:15:56 --> GroupBot has come online
12:20:34 <-- GroupBot has gone offline
12:20:58 --> GroupBot has come online
12:25:36 <-- GroupBot has gone offline
12:26:00 --> GroupBot has come online
12:30:38 <-- GroupBot has gone offline
12:31:00 --> GroupBot has come online
12:35:38 <-- GroupBot has gone offline
12:36:02 --> GroupBot has come online
12:40:39 <-- GroupBot has gone offline
12:41:02 --> GroupBot has come online
12:45:40 <-- GroupBot has gone offline
12:46:02 --> GroupBot has come online

I'm posting this by mrkiko

**Comment by dfortner** [comment]
Why has this been ignored for almost 2 entire months? The guy is trying to use GroupBot and you won't even look into his issue? Say at least "we will look into it" or something?

Where's the old Public Relations person? @Proplex 

Tox is really lacking in many aspects.

**Comment by dubslow** [comment]
This is probably feeding the troll, but TCP has received several changes and improvements in the last couple of months.

**Comment by youtux** [comment]
Thank you @dfortner, I'll try again when I have a so-evil network.

by mrkiko

**Comment by dfortner** [comment]
You are welcome, @youtux

**Comment by GrayHatter** [comment]
can you make this happen on demand?

**Comment by youtux** [comment]
Hi guys: the situation is completely different with the current toxcore.
The problem seems solved: infact I can see groupbot online for some hours it 
seems.
Then at some point toxcore itself seems to loose the connection to the network. 
due to the fact it tries to connect with other nodes maybe, but from inside my 
university only some ports are allored (e.g.: 80, 443, 587, 9418, 5223? and 
5222? ).

Thank you for your attention and reply.

**Comment by GrayHatter** [comment]
should be fixed
