### ISSUE TITLE
Why isn't this code being worked on?

### ISSUE THREAD

**Issue by Jacobsmail2** [irungentoo/toxcore#1172]
In Skype when you are in a group chat anyone can type into the group chat and everyone whether they are online or offline can eventually read it.  When you are in a group chat on Tox, when you eventually turn off your computer, you have to make a whole new chat room or be added back into the group chat once you are back online, and you don't have to ability to see what you missed.  This is quite annoying.  Being able to log on and see what you missed in the group chat on Skype is one feature that makes Skype so convenient to use.  Please consider adding this feature to Tox.

**Comment by GrayHatter** [comment]
fixed in new groupchats
