### ISSUE TITLE
Mistake in pkg-config file that toxcore installs needs to be fixed

### ISSUE THREAD

**Issue by yurivict** [irungentoo/toxcore#1173]
On FreeBSD it installs

    prefix=/usr/local
    exec_prefix=${prefix}
    libdir=${exec_prefix}/lib
    includedir=${prefix}/include

    Name: libtoxcore
    Description: Tox protocol library
    Requires:
    Version: 0.0.0
    Libs:  -L${libdir}  -ltoxdns -ltoxencryptsave -ltoxcore  -lsodium  -lm
    Cflags: -I${includedir}

-lsodium (and -lm) shouldn't be in 'Libs', because 'Libs' is what client apps link to in order to link to toxcore, and they shouldn't link to crypto-libs directly, unless they themselves will decide to (and they shouldn't need to).

-lsodium should be in 'Libs.private' instead. Also, 'Requires' should have libsodium

See http://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by GrayHatter** [comment]
still an issue?

**Comment by yurivict** [comment]
I will update this when I next update the FreeBSD port.

**Comment by GrayHatter** [comment]
@yurivict please reopen if it doesn't work
