### ISSUE TITLE
Peers and messages are not shown in groupchats

### ISSUE THREAD

**Issue by zetok** [irungentoo/toxcore#1184]
![2014-11-29 deceptive stq](https://cloud.githubusercontent.com/assets/3148759/5234640/09bb073a-77ce-11e4-98c3-bc34a46dbbd2.png)
![2nd](http://a.pomf.se/rmguqz.png)
![2014-11-29 deceptive stq](https://cloud.githubusercontent.com/assets/3148759/5234643/6524ae96-77ce-11e4-98cb-de96d615eef4.png)

**Comment by GrayHatter** [comment]
can any one duplicate this still?
