### ISSUE TITLE
Avatar generated from ToxID

### ISSUE THREAD

**Issue by d4ndo** [irungentoo/toxcore#1185]
Other than remembering the ToxID, an image can easily be recognized by a user. So why not show an image generated from each public ToxID in the friends list. (avatar).

I have implemented a similar feature at this project: http://www.checksumjack.org/
It creates a random art (polygon) from the hash digest. see screenshot 1 and 4.
https://github.com/d4ndo/checksumjack

Attack scenario:

Spoofing or faking other users in the friends list by changing to the same nickname and avatar.

**Comment by gracchus163** [comment]
this would be a client feature surely rather than toxcore.  especially if you are suggesting they are generated algorithmically from the toxid then the implementation can be up to the individual client developers

**Comment by GrayHatter** [comment]
re-submit to your favorite client
