### ISSUE TITLE
Ship *.so library files in Jenkins tars

### ISSUE THREAD

**Issue by nikwen** [irungentoo/toxcore#1188]
Hi,

I'm currently exploring the possibility of bringing Tox to Ubuntu for Phones (also know as Ubuntu touch).
In order to ship ARM binaries, we need to build *.so library files for libtoxcore but the only way of doing it which I've been able to come up with is quite complicated: https://plus.google.com/101390620047921378812/posts/7QDhgzETRWE

Therefore, I'm asking whether it would be possible to modify the following command executed in each Jenkins job

`tar --xz -cf libtoxcore.tar.xz bin include lib share`

to match the following

`tar --xz -cf libtoxcore.tar.xz bin include lib share build/.libs`

so that we do not have to care about building the so files.

Thank you very much in advance. :)

**Comment by GrayHatter** [comment]
ask in #tox-dev, this isn't a repo issue
