### ISSUE TITLE
Segfault on Raspbian

### ISSUE THREAD

**Issue by gjedeer** [irungentoo/toxcore#1197]
I just built libtoxcore on Raspbian on a Raspberry pi. It failed tests and segfaults were reported:

<pre>
root@raspberrypi:/home/pi/tuntox-build/toxcore# make check
make  check-recursive
make[1]: Entering directory '/home/pi/tuntox-build/toxcore'
Making check in build
make[2]: Entering directory '/home/pi/tuntox-build/toxcore/build'
make  encryptsave_test messenger_autotest crypto_test network_test assoc_test onion_test TCP_test tox_test dht_autotest 
make[3]: Entering directory '/home/pi/tuntox-build/toxcore/build'
  CC     ../auto_tests/encryptsave_test-encryptsave_test.o
  CCLD   encryptsave_test
  CC     ../auto_tests/messenger_autotest-messenger_test.o
  CCLD   messenger_autotest
  CC     ../auto_tests/crypto_test-crypto_test.o
  CCLD   crypto_test
  CC     ../auto_tests/network_test-network_test.o
  CCLD   network_test
  CC     ../auto_tests/assoc_test-assoc_test.o
../auto_tests/assoc_test.c: In function 'test_fillup':
../auto_tests/assoc_test.c:67:5: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
  CCLD   assoc_test
  CC     ../auto_tests/onion_test-onion_test.o
  CCLD   onion_test
  CC     ../auto_tests/TCP_test-TCP_test.o
  CCLD   TCP_test
  CC     ../auto_tests/tox_test-tox_test.o
  CCLD   tox_test
  CC     ../auto_tests/dht_autotest-dht_test.o
  CCLD   dht_autotest
make[3]: Leaving directory '/home/pi/tuntox-build/toxcore/build'
make  check-TESTS
make[3]: Entering directory '/home/pi/tuntox-build/toxcore/build'
Running suite(s): encryptsave
33%: Checks: 3, Failures: 1, Errors: 1
../auto_tests/encryptsave_test.c:60:F:save_friend:test_save_friend:0: Failed to create 2 tox instances
../auto_tests/encryptsave_test.c:120:E:keys:test_keys:0: (after this point) Test timeout expired
FAIL: encryptsave_test
/bin/bash: line 5: 31819 Segmentation fault      ${dir}$tst
FAIL: messenger_autotest
Running suite(s): Crypto
100%: Checks: 5, Failures: 0, Errors: 0
PASS: crypto_test
Running suite(s): Network
100%: Checks: 2, Failures: 0, Errors: 0
PASS: network_test
Running suite(s): Assoc
100%: Checks: 2, Failures: 0, Errors: 0
PASS: assoc_test
Running suite(s): Onion
0%: Checks: 1, Failures: 1, Errors: 0
../auto_tests/onion_test.c:136:F:basic:test_basic:0: Onion failed initializing.
FAIL: onion_test
Running suite(s): TCP
0%: Checks: 4, Failures: 3, Errors: 1
../auto_tests/TCP_test.c:36:F:basic:test_basic:0: Failed to create TCP relay server
../auto_tests/TCP_test.c:211:F:some:test_some:0: Failed to create TCP relay server
../auto_tests/TCP_test.c:373:F:client:test_client:0: Failed to create TCP relay server
../auto_tests/TCP_test.c:463:E:client_invalid:test_client_invalid:0: (after this point) Received signal 11 (Segmentation fault)
FAIL: TCP_test
Running suite(s): Tox
0%: Checks: 3, Failures: 3, Errors: 0
../auto_tests/tox_test.c:151:F:few_clients:test_few_clients:0: Failed to create 3 tox instances
../auto_tests/tox_test.c:374:F:many_clients:test_many_clients:0: Failed to create tox instances 0
../auto_tests/tox_test.c:490:F:many_group:test_many_group:0: Failed to create tox instances 0
FAIL: tox_test
Running suite(s): DHT
50%: Checks: 2, Failures: 1, Errors: 0
../auto_tests/dht_test.c:289:F:addto_lists_ipv6:test_addto_lists_ipv6:0: Failed to create Networking_Core
FAIL: dht_autotest
===============================
6 of 9 tests failed
Please report to https://tox.im
===============================
Makefile:2301: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 1
make[3]: Leaving directory '/home/pi/tuntox-build/toxcore/build'
Makefile:2424: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/pi/tuntox-build/toxcore/build'
Makefile:436: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/pi/tuntox-build/toxcore'
Makefile:753: recipe for target 'check' failed
make: *** [check] Error 2

root@raspberrypi:/home/pi/tuntox-build/toxcore# uname -a
Linux raspberrypi 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux

root@raspberrypi:/home/pi/tuntox-build/toxcore# git rev-parse HEAD
13dd76995f05fd4759c8f639322671536014e14c

root@raspberrypi:/home/pi/tuntox-build/toxcore# cat /etc/debian_version 
7.6
</pre>

I also compiled a program which links libtoxcore (the same system) and maybe its backtrace will be useful to you:

<pre>
(gdb) run
Starting program: /home/pi/tuntox-build/tuntox/tuntox 

Program received signal SIGSEGV, Segmentation fault.
0x00058c90 in memcpy ()
(gdb) bt
#0  0x00058c90 in memcpy ()
#1  0x000d102c in __pointer_chk_guard_local ()
#2  0x000d102c in __pointer_chk_guard_local ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
</pre>

**Comment by GrayHatter** [comment]
@irungentoo do you want to comment on this? or should we just close it as stale?
