### ISSUE TITLE
Long term public key shouldn't be shared with groupchat peers

### ISSUE THREAD

**Issue by zetok** [irungentoo/toxcore#1198]
Please change it, so that short term public key will be used for groupchats

**Comment by srkunze** [comment]
I support the separation of long-term public keys from group-chat-associated public keys.

**Comment by dubslow** [comment]
The technical discussion on the new groupchats is currently leaning towards sharing PKs.... because of TCP support, I think. Kinda sucks currently.... @irungentoo @JFreegman

**Comment by srkunze** [comment]
@dubslow Don't get me wrong, but what on earth does this have to do with TCP support? To me, both things are as separate as IP and TLS.

**Comment by dubslow** [comment]
Ask in #tox-dev, I haven't really been following the conversation closely

**Comment by GrayHatter** [comment]
@irungentoo close fixed in new groupchats
