### ISSUE TITLE
Can't connect to https://blog.libtoxcore.so/

### ISSUE THREAD

**Issue by jf99** [irungentoo/toxcore#1205]
Since a few days ago, i can no longer access https://blog.libtoxcore.so/. Firefox complains that the given certificate is only valid for tox.im and *.tox.im. For some reason, i cant make an exception either (there is no button to add an exception like it used to be) and when i type http instead of https, it redirects me to https. Does someone have the same problem?

Anyway, it would be good if the server provided a correct certificate for blog.libtoxcore.so.

**Comment by nurupo** [comment]
This is a bug tracker for the Tox C library, your issue is completely off topic here.

p.s.: Blog has moved to https://blog.tox.im/ . A redirect at https://blog.libtoxcore.so/ has been set up.
