### ISSUE TITLE
Broken link to blog

### ISSUE THREAD

**Issue by elpaso** [irungentoo/toxcore#1208]
https://blog.libtoxcore.so/

Has an invalid certificate and even if accepted, the link is a redirect to https://webcache.googleusercontent.com/search?q=cache:blog.libtoxcore.so/ wich gets a 404

**Comment by nurupo** [comment]
This is a bug tracker for the Tox C library, your issue is completely off topic here. Also, in the future search if someone has created similar issue before posting.

p.s.: Blog has moved to https://blog.tox.im/ . A redirect at https://blog.libtoxcore.so/ has been set up.
