### ISSUE TITLE
Current maximum allowed avatar resolution/filesize is too low

### ISSUE THREAD

**Issue by LittleVulpix** [irungentoo/toxcore#1221]
The maximum allowed resolution (and image filesize of 16kb) of an avatar is too low. Even mobile clients with a lot of contacts could easily cope with something more than the current limit.

It takes a lot of effort (in most cases) to make the avatar decent/presentable. Consider raising the avatar resolution/filesize limit to allow for better "expression and personalization" of the contacts. Steam has the right idea whereby you upload an avatar and it auto-resizes into 3 presets and the client can decide which size it wants to query.

**Comment by GrayHatter** [comment]
it's now 64KiB

**Comment by LittleVulpix** [comment]
Agreed
