### ISSUE TITLE
How can I contribute a translation?

### ISSUE THREAD

**Issue by vkehayas** [irungentoo/toxcore#1225]
Hi!

GitHub newbie here and I want to contribute a translation to Greek.
Can someone please point me where I can start?

**Comment by dubslow** [comment]
@vkehayas You need to choose which client you want to translate. Then find its GitHub repository (not this, the core library's repository), and find out how that client handles translations.

**Comment by suhr** [comment]
For example, to translate qTox:
* Fork [qTox repository](https://github.com/tux3/qTox)
* Run `lupdate qtox.pro -ts translations/el.ts` in the qTox dir
* Use Qt Linguist to translate qTox
* Add `translations/es.ts \` to `TRANSLATIONS` variable in `translations/i18n.pri` file
* Commit your changes

Github interactive introduction to git: https://try.github.io/

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it's a resolved support issue.
