### ISSUE TITLE
I want Tox to die.

### ISSUE THREAD

**Issue by dfortner** [irungentoo/toxcore#1226]
I hate how successful Tox is. Please die Tox. Why won't you die??? Why?

**Comment by dfortner** [comment]
Red alert
The document of https://mail.tox.im/prolapse.txt has been edited. Really looks like someone from the Tox Foundation is trying to cover this up. Hopefully we have the archive.today service available.

https://archive.today/KkSWp

This situation is eerie, to say the least.

**Comment by irungentoo** [comment]
Go shitpost somwhere else.
