### ISSUE TITLE
irungentoo, cut it out

### ISSUE THREAD

**Issue by TheLastProject** [irungentoo/toxcore#1227]
Seriously, what the FUCK is wrong with you.
![irungentoo_defacing](https://cloud.githubusercontent.com/assets/1885159/5804845/e5b6667c-a009-11e4-9a39-43dde81768ae.png)

**Comment by TheLastProject** [comment]
Stop defacing things.

**Comment by TheLastProject** [comment]
Man up and face this. At least lock it and contact him personally.

**Comment by TheLastProject** [comment]
This is really sickeningly sad.

**Comment by TheLastProject** [comment]
I'm siding with @dfortner, @Proplex, @notadecent and many others here. This is NO way to manage a project.

**Comment by zetok** [comment]
I have to agree with what @TheLastProject says. Please don't, @irungentoo

**Comment by irungentoo** [comment]
This repo is about toxcore and toxcore only.

If you want to discuss non toxcore related things go somewhere else.
