### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by again2** [irungentoo/toxcore#1229]
As the last issue was deleted by the user, for whatever reason, I'm opening it again so this matter can be settled once and for all. This should be the **only** issue on this repository to treat this matter, as @irungentoo stated. No other issues should be opened (unless this one is deleted or something). The relevant issue, now unavailable, follows:

http://s12.postimg.org/wlj6wj7mz/kqwgsg.png

**Comment by again2** [comment]
A reply for the last points raised by *ghost* would be nice, @irungentoo 
I feel this issue is still inconclusive and making many users doubt the Tox Foundation's actions.

**Comment by irungentoo** [comment]
This drama bullshit is over.
