### ISSUE TITLE
Searching for "Tox" on Google PlayStore finds Bleep

### ISSUE THREAD

**Issue by srkunze** [irungentoo/toxcore#1232]
Looks like something bad is going on there (at least to me). IMHO, they try to fool people in using Bleep, which is incompatible with Tox.

Is that intentionally?

**Comment by irungentoo** [comment]
Interesting though the explanation is most likely that many of the reviews of bleep mention Tox.

**Comment by srkunze** [comment]
Alright. I just wanted to check that because we installed it because we found it this way. ;)

**Comment by srkunze** [comment]
I think this can be closed.
