### ISSUE TITLE
Where did the uTox repository for Yum ??? 

### ISSUE THREAD

**Issue by Non77** [irungentoo/toxcore#1233]
Where did the uTox repository for Yum ??? 

Attention to page https://wiki.tox.im/Binaries -
pressure on the link https://repo.tox.im/tox.repo displayed error:

404 Not Found
nginx/1.7.8

**Comment by dubslow** [comment]
@stqism

**Comment by Non77** [comment]
And here they are? I use uTox!

**Comment by Non77** [comment]
Where did the uTox repository for Yum ???

Attention to page https://wiki.tox.im/Binaries -
pressure on the link https://repo.tox.im/tox.repo displayed error:

404 Not Found
nginx/1.7.8

**Comment by Non77** [comment]
# yum update
Loading mirror speeds from cached hostfile
https://repo.tox.im/rpm/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

Where did the uTox repository for Yum ???

Attention to page https://wiki.tox.im/Binaries -
pressure on the link https://repo.tox.im/tox.repo displayed error:

404 Not Found
nginx/1.7.8

Why do not you fix these errors?

**Comment by stqism** [comment]
@dubslow

I for the most part don't look at the sea of misplaced issues.

**Comment by Non77** [comment]
And you do not look! You do!!!

**Comment by Non77** [comment]
You are a very long time does not improve uTox. 
You ignore the wishes of the users. 
You ignore questions from users. 
You have real slackers. 
Therefore, the program Jitsi is much better than your uTox!

**Comment by ignisf** [comment]
@Non77, I find the tone of your comments unacceptable.

**Comment by Non77** [comment]
And I think that your actions ashamed! You have to work! And bug fixes! But you do not work !!!

**Comment by Non77** [comment]
Why do you still have not fixed this very simple mistake ???

 https://wiki.tox.im/Binaries -
pressure on the link https://repo.tox.im/tox.repo displayed error:

404 Not Found
nginx/1.7.8

**Comment by Non77** [comment]
Why do you still have not made the outbound ringtone ??? We have many times asked about this!!! You are shame!!!

**Comment by ameenross** [comment]
@Non77, it sounds like you are paying the developers.

**Comment by Non77** [comment]
Also, I do not pay developers Jitsi, but they all work.
I would have paid if you had eliminated the most glaring weaknesses.

**Comment by Non77** [comment]
network connection is unstable and is lost cyclically.  With older versions, this was not. 
Conclusion: with each new version uTox is getting worse.

**Comment by mannol** [comment]
@Non77 I hate to be the one to say this but, the developer that maintained uTox died in a car accident about the time yum repository stoped functioning. We are sorry for the inconvenience.

**Comment by Non77** [comment]
I offer my condolences...

**Comment by ArchangeGabriel** [comment]
@mannol Stop doing that. This is not funny.

**Comment by urras** [comment]
What exactly is the issue again?

**Comment by Non77** [comment]
Read from the beginning. Here there is always a problems.

**Comment by urras** [comment]
@Non77 Just fixed that. Try again?

**Comment by Non77** [comment]
Yes, no more errors:
https://repo.tox.im/tox.repo   and
yum update

New versions uTox no more?

**Comment by dubslow** [comment]
Ask in the uTox repository.

**Comment by Non77** [comment]
yum update  --> no more updates
