### ISSUE TITLE
Empty status messages

### ISSUE THREAD

**Issue by Rotkaermota** [irungentoo/toxcore#1235]
Empty status msg (with 0 len) not sent to other clients
Workaround - send 1 space char and trim tailing spaces in status msg update

**Comment by ProMcTagonist** [comment]
I disagree with core modifying status messages.

**Comment by Rotkaermota** [comment]
No no. No need to modify status message by core. I said that current toxcore does not allow to set empty status message, because zero-len status messages not sent to other clients. That's it.
My opinion: it is wrong. It is bad idea to suppress users to set empty status message.
And my current workaround in my client - as I wrote in my first message.

**Comment by ProMcTagonist** [comment]
I thought you were proposing that core trim trailing spaces, sorry.

I often blank out my status message to clear it and didn't know that wasn't going to any of my friends. That's a bug.

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it was fixed in the new API.
