### ISSUE TITLE
Message meta data

### ISSUE THREAD

**Issue by Rotkaermota** [irungentoo/toxcore#1236]
It will be nice to implement delivery of message-metadata with message text in one delivery action. Metadata - any bytes, that standard tox client should ignore, if it not understand that bytes.
1st application of metadata - send message creation time with message.
As you know, message receive-time not always equal to message creation-time. Comparing to skype - it shows message creation-time - not receive-time.
With metadata its possible to send other cool stuff, bbcodes, for example. Or emoticons.
Of coource it creates some fragmetation with other clients. You can create recomedations to clients developers. For example - use json, or something like, tag naming and so on.

**Comment by GrayHatter** [comment]
new PR coming soon-ish

**Comment by GrayHatter** [comment]
closed as incomplete issue 

Please list the problem, why it's a problem, and a proposed solution if you have one, and if so why you think your solution is a good fix.

**Comment by Rotkaermota** [comment]
It is not a problem. It just means, that reference functionality is very poor. I want to implement more good stuff in my client, but tox is so blinkered.
How can I send message create time (like skype do), for example?
Current tox protocol has big issue: it is very hard to implement new functionality with keeping compatibility. Message meta data is one possible solution: clients can safely extend its messaging functions without waiting when toxcore will support it.
Anyway, I no longer need the implementation of this suggestion. Just do nothing.

**Comment by GrayHatter** [comment]
dup; please see #1519
