### ISSUE TITLE
Seen whisper? 

### ISSUE THREAD

**Issue by o-jasper** [irungentoo/toxcore#1241]
I am sure you've heard of Ethereum. They're building non-blockchain decentralized net too. Couldnt find anything searching for whisper/libp2p/Ethereum in the issues, so decided to make an issue.

Some description of [Whisper](https://github.com/ethereum/wiki/wiki/Whisper).. At least both cpp-ethereum and go-ethereum have an implementation. Seems to do a slightly different thing than tox does.

[Libp2p](https://github.com/ethereum/wiki/wiki/libp2p-Whitepaper) might be interesting too. Probably be possible to put tox ontop of it, hard to estimate how well it behaves.

Note that the Ethereum browser has javascript apis to these things. This puts in the reach of people?

Another thing to note is that Ethereum is launching late Februari/March, so they're probably *very* busy.

**Comment by srkunze** [comment]
@o-jasper Tox is no cryptoplatform like Bitcoin, Nxt, Ethereum and the like. Nobody would want to pay for sending a message.

So, PoW, PoS or proof of whatever will never be done here (at least from what I see and how I perceive the tox project).

(btw. Ethereum will have a blockchain)

**Comment by o-jasper** [comment]
I think you categorized too quickly. Ethereum has a blockchain, but you do not need to touch it at all to use whisper or libp2p.

**Comment by irungentoo** [comment]
In the specs I see:
> Low-bandwidth Not designed for large data transfers.
> Uncertain-latency Not designed for RTC.

Tox is designed for low latency and high bandwidth. 

Is there code for whisper and libp2p or just whitepapers?

**Comment by o-jasper** [comment]
As i said, there are at least two implementations of it. Ethereum was crowdfunded @ 18.4M$ at the bitcoin price at the time, you know...

I thought you'd have a more "what can we take from that?"-approach. But i dont have enough insights myself to figure that out myself. If i get them i'll give it another shot.
