### ISSUE TITLE
The latest blog entry is 2 months old.

### ISSUE THREAD

**Issue by jf99** [irungentoo/toxcore#1244]
You should consider writing a few sentences about what you're currently doing. People want to be kept up-to-date.

**Comment by ProMcTagonist** [comment]
This should be in https://github.com/Tox/Tox-Foundation-Discussion/

**Comment by jf99** [comment]
Thank you for the clue, I didn't know about this. Next time the blog is being disregarded, I will post it there.

**Comment by jf99** [comment]
Wow, that's an update! Thanks for that. For the future, I hope you provide some (small) info more frequently.

**Comment by dubslow** [comment]
People are lazy. It's just that I felt slightly less lazy than everyone else yesterday.
