### ISSUE TITLE
Wierd warning when running apt-get update on Debian

### ISSUE THREAD

**Issue by heini** [irungentoo/toxcore#1246]
Hi,

since some days, when running apt-get update, I get the following warning at the end:

W: Size of file /var/lib/apt/lists/partial/repo.tox.im_dists_nightly_Release.gpg is not what the server reported 473 168

Note that I've already updated to the new repo as outlined in the wiki.

**Comment by irungentoo** [comment]
Apparently this is an issue with apt and not the tox repo.

**Comment by heini** [comment]
OK, I'll file a bug for apt-get, then.

**Comment by kjcole** [comment]
And now I'm getting that message but only with the tox repo. Reports of this type of problem with apt and other repos surfaced a few years ago, and it was then reported fixed.  Apparently not permanently.
