### ISSUE TITLE
Travis-CI occasionally fails at 'make check'

### ISSUE THREAD

**Issue by urras** [irungentoo/toxcore#1248]
Started happening in https://github.com/irungentoo/toxcore/commit/a576e451abe3c6ec87a28abb687638c9ca7d3f31.

[Example](https://travis-ci.org/irungentoo/toxcore/builds/49264455)

**Comment by dubslow** [comment]
This is a well known issue and has indeed been happening since the tox_test was added. @irungentoo always says things like "conditions have to be perfect" etc

**Comment by urras** [comment]
So, would this be something we need to talk to the Travis folks about?

**Comment by dubslow** [comment]
It sometimes fails on my system too, but talking to Travis may help. Ask irungentoo.

**Comment by urras** [comment]
Yeah, it failed 5/10 times on my system too. Same [error](https://travis-ci.org/irungentoo/toxcore/jobs/49264457#L1666).

**Comment by urras** [comment]
Also, I get the following error occasionally when I run make check:

```../auto_tests/tox_test.c:608:F:many_group:test_many_group:0: Bad number of group peers. expected: 32 got: 6, tox 29```

**Comment by urras** [comment]
Now I'm starting to get this error too:

```../auto_tests/toxav_many_test.c:291:E:AV_three_calls:test_AV_three_calls:0: (after this point) Test timeout expired```

**Comment by GrayHatter** [comment]
@irungentoo close stale
