### ISSUE TITLE
RPM install failing: 64-bit building with old keys?

### ISSUE THREAD

**Issue by phipolis** [irungentoo/toxcore#1249]
Installing qtox 64-bit on a yum system fails, referencing 0c2e03a0 -- isn't this your old key? This is a clean OS install, hadn't encountered the repo before.
```
warning: /var/cache/yum/x86_64/21/tox/packages/qtox-230.rpm: Header V4 RSA/SHA1 Signature, key ID 0c2e03a0: NOKEY
Retrieving key from https://repo.tox.im/pubkey.gpg

The GPG keys listed for the "Tox Nightly" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: qtox-1.0-1107.x86_64
 GPG Keys are configured as: https://repo.tox.im/pubkey.gpg
```

**Comment by urras** [comment]
Yeah, that's the old key. What if you try to re-add the repo/key?

**Comment by phipolis** [comment]
I didn't have the old key installed, I just installed the repo and key yesterday with the files as they stood yesterday. It appears the rpms, at least the 64-bit ones, are still signed with the old key.

```
$ rpm --checksig ~/Downloads/qtox-234.rpm            
~/Downloads/qtox-234.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#0c2e03a0) ```

**Comment by dubslow** [comment]
@stqism

**Comment by urras** [comment]
Actually I take that back. I'm pretty sure that's the new key.

**Comment by urras** [comment]
Still having issues?

**Comment by RussianPenguin** [comment]
Yes. I have same problem. Repository for fedora 20 x64.

Downloading packages:
warning: /var/cache/yum/x86_64/20/tox/packages/qtox-298.rpm: Header V4 RSA/SHA1 Signature, key ID 0c2e03a0: NOKEY
Retrieving key from https://repo.tox.im/pubkey.gpg


The GPG keys listed for the "Tox Nightly" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: qtox-1.0-1176.x86_64
 GPG Keys are configured as: https://repo.tox.im/pubkey.gpg

**Comment by dubslow** [comment]
The Jenkins signing key matches the pubkey I just downloaded from that web address, so I'm not sure what's going on here. 

```
gpg --show-key tmp/pubkey.gpg
pub  2048R/7DF12B85 2014-12-20 Tox RELENG (Tox build system) <build@tox.im>
sub  2048R/F7B49CD8 2014-12-20
```

**Comment by urras** [comment]
Pinging @stqism, again

**Comment by pierrese** [comment]
I have the same problem, on Fedora 21...
Any idea?

**Comment by zetok** [comment]
Is this still an issue?

**Comment by phipolis** [comment]
Redownloaded the repo, yum prompted me to import key 0x7DF12B85. Installation of qtox concluded successfully. Issue seems resolved.
```
Importing GPG key 0x7DF12B85:
 Userid     : "Tox RELENG (Tox build system) <build@tox.im>"
 Fingerprint: dbdc 8c5f d3c7 0ca6 846e 348b 4b11 1b5d 7df1 2b85
 From       : https://repo.tox.im/pubkey.gpg
Is this ok [y/N]: y
```

**Comment by pierrese** [comment]
For me too ! Thanks !

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it's a resolved support issue.
