### ISSUE TITLE
Store last peer connection info in tox_save.tox

### ISSUE THREAD

**Issue by LittleVulpix** [irungentoo/toxcore#1250]
Logging out and logging back into Tox causes the protocol to have to rediscover paths to all of the contacts. It could be useful (obviously security must be preserved!) to store the last known path in the tox_save.tox file so that upon reconnection, contactlist contact state could be restored much faster. This way, sometimes it takes 30-60 seconds for a contact to come online even though you know they are online.

Tox should know to first check for a path in the file and if it's not there, simply go ask DHT. If it's in the file, check if it's still valid; and if it is, used it. If not, ask DHT like normal.

**Comment by jf99** [comment]
This is a good idea imo. It also provides a way to connect to tox without going over the publicly known DHT nodes, which might get censored in some countries.

**Comment by fcore117** [comment]
seperated dht/nodes file would be even better idea.

**Comment by tttom** [comment]
I like the idea, it would take some load off those volunteered nodes. It shouldn't be limited to contacts necessarily. Perhaps also some stats should be kept to determine the likelihood of finding a node at a certain IP/port (at a given time).

**Comment by v6** [comment]
// , 

How could I open the tox_save.tox file? 

What format is it in?

**Comment by GrayHatter** [comment]
@irungentoo am I crazy or did you say you planned to implement something like this?

**Comment by GrayHatter** [comment]
@LittleVulpix did the DHT upgrades solve this issue for you?

**Comment by LuccoJ** [comment]
I see nothing in my ~/.config/tox directory that seems to store addresses of previously-discovered peers, so I don't think this was implemented...
It could be implemented by clients, too (since they can decide which addresses to bootstrap from), but only if toxcore gave them a way to know which nodes are connected at a given time.

**Comment by GrayHatter** [comment]
@LuccoJ the issue was speed of reconnection. That may have been fixed, even without using the original discription

**Comment by ProMcTagonist** [comment]
Toxcore is supposed to be saving this information already so it can bootstrap from them, according to past irc conversations...

**Comment by GrayHatter** [comment]
@ProMcTagonist my understanding was that it only applied to friends/contacts, not DHT nodes

**Comment by LittleVulpix** [comment]
@GrayHatter Well, tox connects to peers very quickly now, so the DHT fixes "fixed" this, even though it's not really that kind of optimization - it simply improved peer lookup speed significantly. This issue might still be worth looking into at a later point, but for now, I guess it's okay that it's been closed.

**Comment by GrayHatter** [comment]
@littlevulpix, I'm happy to reopen this if there's still an outstanding
issue that this would fix.

**Comment by LuccoJ** [comment]
Oh, yeah, the focus was different from what I was thinking. But last time I used Tox (which was just a couple of days ago), it still was taking 30 seconds or so for peers to be seen as online. I didn't notice a change in this.

**Comment by LittleVulpix** [comment]
@LuccoJ 30 seconds is fine I'd say?
@GrayHatter There is an issue of sorts where if you restart your client (maybe without closing connections gracefully), then it takes longer to establish connectivity to a peer.

It generally happens if (for example) you tell someone "brb restarting qtox", then you restart qtox and that one person you messaged when you restarted will be offline for 1-2 minutes (although they are online really). All the other people who were online on your list previously and whom you had not spoken to prior to the restart will appear as online within ~10-30 seconds. I assumed that a PR inspired by this issue could remedy this behavior.
