### ISSUE TITLE
Ending a call while call window is in OSX fullscreen mode results in an unclosable fullscreen desktop

### ISSUE THREAD

**Issue by smckee6192** [irungentoo/toxcore#1252]
Machines tested on were a late 2013 iMac and a mid 2013 Macbook air, both running OS X Yosemite 10.10.2. 
The Tox version does not seem available anywhere, but both Tox applications were downloaded tonight (2/6/15)

The resulting screen is completely black, and the escape key will not close it. The only way that I have been able to close it is by quitting Tox completely.

**Comment by irungentoo** [comment]
Is this a bug for qTox? If so please go report it here: https://github.com/tux3/qTox

**Comment by smckee6192** [comment]
Yes, that is where it should be. Sorry for the mistake.
