### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by SILENCE-GIVES-CONSENT** [irungentoo/toxcore#1256]
What are the dependencies of Tox?
Is openal-soft-tox a dependency? https://github.com/irungentoo/openal-soft-tox

Speaking of that, did you really fork openal-soft into openal-soft-tox instead of making PRs to the original project?
I already need openal-soft for many programs and now I'll have to install openal-soft-tox too, that's the exact same thing with a few lines of code added? What is this madness?

**Comment by dubslow** [comment]
The dependencies are clearly listed in the .md files of both toxcore and the various clients. They're very easy to find with no more effort than it takes to find the repository.

That other clone is for testing purposes. If the testing in uTox with that patch works, then it will be submitted to upstream. (To have the feature in uTox though you'd likely need to install the patched version anyways, even if it makes it into upstream -- package managers can sometimes be years behind upstream repositories.)
