### ISSUE TITLE
Discussions and Decision making

### ISSUE THREAD

**Issue by balasankarc** [irungentoo/toxcore#1260]
Hi,
I just became a user of Tox. While traversing through the issues, I saw that a discussion about adding a GPL exception happening there. I would suggest using loomio for making such policy decisions as issue tracker is clearly not the place for doing so.. Many FS projects now use this platform for discussions and decision making. Hence I think it is worth giving a try. http://loomio.org

**Comment by urras** [comment]
Hi @balasankarc,
We have a repo setup at https://github.com/Tox/Tox-Foundation-Discussion for this kind of thing

**Comment by balasankarc** [comment]
Err... I seriously don't think a git repo is the best tool for having discussions. It was never intended for that.

**Comment by zetok** [comment]
@balasankarc thing is, toxcore repo isn't a place for discussion about that stuff. If you want to propose change to how things are being done, you should post in repo linked by @urras, or to post your proposal on [mailing list](https://lists.tox.im). If you wish to discuss stuff there, I have some questions about your proposal.

Please close this issue, preferably linking to post to ML or relevant issue in linked GH repo.

(IMHO posting to ML would be better, but that's just an opinion)

**Comment by balasankarc** [comment]
Ah.. Ok.. Thanks. :)
