### ISSUE TITLE
Change an Already Sent Message

### ISSUE THREAD

**Issue by srkunze** [irungentoo/toxcore#1261]
Skype features the ability to change an already sent message. I found this to be useful. Can this be done?

**Comment by Impyy** [comment]
Duplicate of https://github.com/irungentoo/toxcore/issues/772

**Comment by srkunze** [comment]
Damn. I didn't find this one. Thanks, @Impyy 

Shall I close this issue now?

**Comment by aaannndddyyy** [comment]
Yes
