### ISSUE TITLE
Clearer commit messages

### ISSUE THREAD

**Issue by rrooij** [irungentoo/toxcore#1262]
First of all, compliments to the developers behind Tox. A free as in freedom Skype alternative is needed and I hope that Tox will succeed in its mission.

The issue:

When I look at the commit messages, I think that it isn't always clear what is being changed or what's going on. For instance, a lot of commits are mentioned as "Code cleanups".

Why not format the commit messages like this:

[module/c-file]: code cleanups

It's easier to find a specific revision when commit messages are like this. 

Another example:

https://github.com/irungentoo/toxcore/commit/ee3adf26413f11a83fcabb7e1cf394e2235a8d6c

Why not "[msi.c]: Fixed memory leak" as commit message instead of just "Fixed memory leak"?

**Comment by ignisf** [comment]
Yesterday I too raised my concerns regarding the commit messages on irc.

@robin007bond, I think that the files affected by the change do not be belong in the commit summary. However a description of each change AND the motivation behind the change do belong in the commit message.

Yesterday @irungentoo pointed out that the code clean-ups did not bring any logic changes that need to be described. While this might be true, IMO this does not warrant deviation from the basic template of a good commit message that I outlined above.

For example, https://github.com/irungentoo/toxcore/commit/c086a66725fc52aaa09de0463fb9dbae4e407eb7 IMO should read something like:

```
Rename ONION_DATA_FAKEID to ONION_DATA_DHTPK

Change all references to ONION_DATA_FAKEID in the code base to ONION_DATA_DHTPK <because the second better represents the .. etc etc etc insert motivation here...>
```

I get that it's a nuisance but it helps out people that don't hang around on IRC and want to keep up with changes in the codebase and also helps with gaining trust in the codebase itself as you can see for yourself how the devs think and work.

Again, keep up the awesome work :)

**Comment by ignisf** [comment]
As a (mostly) good example I would point out [libotr](https://github.com/off-the-record/libotr/commits/master)'s commit history. Again, not lengthy [Linux kernel-like](https://github.com/torvalds/linux/commit/fd71493d67977a49e293c96f213006ec9e30c4c9) commit messages, just short resume on the what and why.

**Comment by rrooij** [comment]
This is still a problem, for example:

https://github.com/irungentoo/toxcore/commit/097422a02c3f67edd98833f65e57d76f06c18766

https://github.com/irungentoo/toxcore/commit/815725ab843618e1008819fe1449d8473627a114

**Comment by rrooij** [comment]
Any updates?

There are still commits which are very vaguely described.

**Comment by GrayHatter** [comment]
@rrooij good luck herding cats! My suggestion would be to make this comment on every new commit, then maybe something better will happen...

otherwise, stale, and not a code issue

@irungentoo just so you're aware.

**Comment by ignisf** [comment]
Good luck with your project, I hope it becomes trustworthy one day.
