### ISSUE TITLE
New API Option: Port range

### ISSUE THREAD

**Issue by saneki** [irungentoo/toxcore#1266]
`uint16_t start_port` and `uint16_t end_port` members of `Tox_Options`. If set, would be used instead of the default range of 33445 - 33545.

If `start_port` or `end_port` is zero while the other is non-zero, will use the non-zero value as the only port. If `start_port` > `end_port`, will swap the values of `start_port` and `end_port`.

I'm willing to implement this and send a pull request, but was wondering if anyone had any feedback.

**Comment by dubslow** [comment]
Why? Almost everyone else will be using the standard ports...?

**Comment by aaannndddyyy** [comment]
Port blocking....

**Comment by fcore117** [comment]
Port changing is critical for future, very critical.
