### ISSUE TITLE
New API branch defines useless error codes

### ISSUE THREAD

**Issue by sonOfRa** [irungentoo/toxcore#1281]
https://github.com/irungentoo/toxcore/blob/new_api/toxcore/tox.h#L281

This "error code" has no reason to exist. When the function produces an error, the result is not defined. We should not rely on these kind of error codes. "INVALID" is not a status a friend can actually have, the API should not expose this.

**Comment by zetok** [comment]
Is this still relevant?
Searching for ``INVALID`` in ``tox.h`` didn't seem to bring anything relevant to friend statuses

(also, link is ded)

**Comment by sonOfRa** [comment]
No, this is no longer relevant.
