### ISSUE TITLE
new_api: rename private_key to secret_key; add TOX_SECRET_KEY_SIZE

### ISSUE THREAD

**Issue by iphydf** [irungentoo/toxcore#1282]
See:
https://github.com/tox4j/tox4j/blob/master/src/main/cpp/tox/core.h#L191-194
https://github.com/tox4j/tox4j/blob/master/src/main/cpp/tox/core.h#L646-652

**Comment by dubslow** [comment]
I've got the first part covered, see my PR

**Comment by zetok** [comment]
Is this issue still relevant? Quick search using github's search didn't return any occurrences of ``private_key`` except for ``other/fun/make-funny-savefile.py``

**Comment by iphydf** [comment]
Nope. Done.
