### ISSUE TITLE
Friend request

### ISSUE THREAD

**Issue by Diadlo** [irungentoo/toxcore#1284]
When I send friend request, friend accept request, but I don't get messeges about it (It looks like he don't accept). I try it with few people and they try it with their frends, and always we can't add friend. Sometimes I need only one time for add, sometimes about 5 time. Sorry for my English. Ask questions if something is not clear.

**Comment by xdevelnet-inc** [comment]
Client name? OS?

**Comment by Diadlo** [comment]
qTox, Linux

**Comment by xdevelnet-inc** [comment]
Well... that's weird.
It usually happend on Win clients when I test it.

I also heard, that qTox isn't best client for Win.

**Comment by Diadlo** [comment]
Yes, it is strange. On Windows man use uTox

**Comment by GrayHatter** [comment]
are you still having this issue?

**Comment by xdevelnet-inc** [comment]
Hm. You're asking because something is fixed inside toxcore?
I can test it this evening.

**Comment by Diadlo** [comment]
After this post. I add friend only once, and haven't issue
