### ISSUE TITLE
[CRITICAL USABILITY BUG] Tox contact's online status doesn't get restored after connection interruption

### ISSUE THREAD

**Issue by yurivict** [irungentoo/toxcore#1285]
I have qTox instance with user1 account running on my host, and another qTox instance with user2 running in the virtual machine. user1 and user2 are friends and see each other online status.

When VM network connection is brought down and then back up, user2 goes back to green status after a minute or so, but status of user1 inside user2 client, and status of user2 inside user1 client never go to green. 

This is a very bad bug, because simple short disruption of network connection causes both sides (friends user1 and user2) to permanently see each other as offline, when they are actually online.

I suspect this affects many/most users of tox, when one or both sides are on unstable connection.

**Comment by dubslow** [comment]
This is probably a qtox issue, doesn't belong here

**Comment by yurivict** [comment]
I could reproduce it 2 out of 10 times with qTox, but not with toxic.

**Comment by dubslow** [comment]
I'm planning to significantly overhaul a lot of qTox code for the new_api, which would include the connect and retry connecting code. Try again in a few weeks.

**Comment by yurivict** [comment]
@dubslow ok, thanks!

Unrelated question: did you consider using SQLCipher for the Tox database? Because currently tox clients load data file (different name for each kind of client), then file is optionally decrypted, etc. SQLCipher is an encrypted SQLite. And SQLite is super stable and reliable. And clients could also potentially share db, and lock it through SQLite, etc. And there are also standard tools to access SQLite databases, which is a big benefit.

**Comment by zetok** [comment]
>did you consider using SQLCipher for the Tox database?

Most likely it's not going to be used. Also, there is no such thing as "Tox database"

>currently tox clients load data file in proprietary format (different file name for each kind of client)

nope, it's all standardized for clietns. When time will come, clients that won't comply to standard will not have ability to call themselves Tox clients.

>clients could also potentially share db

DB can be only used for storing history, etc.
So.. nope, unless the way in which history (etc) is stored in db is standardized… If you want to help with that: https://github.com/Tox/Tox-STS

If that's all, please close issue.

**Comment by yurivict** [comment]
Thanks, closing the issue. Will retest after the update cycle.
