### ISSUE TITLE
Feature request: video compression options

### ISSUE THREAD

**Issue by atgote** [irungentoo/toxcore#1291]
First of all - the video transmission (as it was with screencast on uTox) as it has appeared was great! The picture quality was 100% as it seemed. However, some time later a high compression was enabled / added and picture quality for the moment is not so good (sometimes very bad for screencast). As far as I know for the moment the video compression is performed in the toxcore library. In our opinion it would be great to enable / add possibility to select compression ratio, allowing higher picture quality for users with higher bandwidth available... Maybe by default it must be set to some "Auto" or predefined (low quality) value, suitable for camera video transmission, but with availability to test / set up to highest quality level...

**Comment by GrayHatter** [comment]
AV scaling is optional in ToxAV, and then it's a client issue...
