### ISSUE TITLE
I2P & SAM - Not an issue, just looking for leads : -)

### ISSUE THREAD

**Issue by seventurns** [irungentoo/toxcore#1292]
Been trying to figure out the best way to get Tox working on I2P. Does this seem to be the best route:

"Using sam would be the way to do it.
tox dht would have to store key hashes instead of ip:port.
Then the client connects to localhost and instructs sam to open up a tunnel to the bootstrap nodes first, and later to any key hash it wants to connect to."

Or is there some method already out there somewhere ...? ....

**Comment by ElLamparto** [comment]
It is a great idea!

I2p has only the I2P-Messenger, for which the dev was abandoned in 2013.
By the way, there are things which Tox may "borrow" from I2P-Messenger: user announcement and search (!), the emoticons.... I can provide the souce code (C++).

**Comment by seventurns** [comment]
Thanks for the reply : - )

This particular approach is not my idea originally, just the best one i have come across so far....  It does seem to me important to treat i2p as simply a transport layer. And to keep the Tox client compliant enough to be easily updatable  with new builds. Dunno how hard that would be if once one starts mucking about with dht to store key hashes insteadof ip:port. 
 
You were mention some of the i2p-messenger functions - i have been wondering also about the idea of hanging some of the network functionality (discovery, announcement) on a torrent client, sort of like how vuze is doing things with their decentralized chat in their i2p plug in.

**Comment by ElLamparto** [comment]
Agreed. Still I think that i2p interface has low priority. In the toxcore I would implement - first of all - the bandwidth throttling for file transfers and the echo cancellation for audio.
Then adding user search would add a great deal of value to Tox! Since Tox is not meant to be a darknet communicator, I would think about the i2p integration afterwards.

**Comment by fcore117** [comment]
i agree too that tox should be fast and lightweight as possible with bandwidth control and other hi priority features. Maybe if someone wants i2p then should use/make separated project from toxcore.

**Comment by aaannndddyyy** [comment]
@seventurns: unless you write it in Java, I think Sam is the way to go. Bob only supports TCP. Toxcore would remain lightweight as you do not bundle an i2p router just as right now tor is not bundled.
But as addresses in i2p are different from addresses on the open internet, parts that use IP must be made more generic. If you do not only allow i2p addresses but also IP's, your core would still be compatible with mainline toxcore.
 That means the chat data is not sent to a friend`s IP but to local i2p router which sends it to the friend. The router must be informed about the address where to send it to.
The good thing is, that if you manage to get a patched toxcore to run on i2p, that also is most of what you will need to run it as an onion service.
You would have to decide whether or not you want to allow these users to be able to communicate with non-hiddenservice users.
Vuze does announcements of group chat id hashes to a dht, similar to how @alnf's groupchats are doing for fox. So this is already being worked on.
@ElLamparto the user search i2p messenger does is not very special: it simply publishes its address to a few hard-coded servers.

**Comment by seventurns** [comment]
@aaannndddyyy thanks for the detailed response. much appreciated.

**Comment by ElLamparto** [comment]
@seventurns, thanks a lot

**Comment by aaannndddyyy** [comment]
@seventurn: Are you going to do it?

**Comment by GrayHatter** [comment]
@irungentoo  close as suggestion/request, not in an issue with an actual fix

@* if you want toxcore to work on I2P, open a new issue with something that breaks compatibility, that has an actual fix.
