### ISSUE TITLE
The Core Needs Proper Documentation

### ISSUE THREAD

**Issue by Astonex** [irungentoo/toxcore#1295]
The core is in desperate need of proper documentation of the protocol and current code. Doing so will help others to be able to contribute to the core, and potentially spot any security concerns, and areas for improvement.

For example, a lot needs to be done in terms of bandwidth usage for Tox to become a more serious competitor for mobiles. Documentation of the protocol would help with this.

**Comment by irungentoo** [comment]
There are basic protocol docs in the docs folder in the repo and: https://github.com/Tox/Tox-Technical-Report

The reason the technical report is stalled at the moment is because I realized when I arrived at the point it is now that I wanted to change some things in the protocol so I stopped.

Unless I get help from someone who can write well the tech report will most likely stay in that state until Tox is stable.

**Comment by sonOfRa** [comment]
Concerning documentation, at least the public facing part of the new API is very well documented, and comes with a design document: https://github.com/tox4j/tox4j/blob/master/doc/core-design.md. Some work has also be done on specifying the DHT protocol: https://github.com/tox4j/tox4j/blob/master/doc/protocol.md

**Comment by Astonex** [comment]
@sonOfRa That documentation looks great. Why is none of it part of the Tox core repo where it is more easily found?

@irungentoo Those docs are literally nothing. Don't you think it's a better idea to write the protocol first and then implement it in code rather than the other way around?

**Comment by sonOfRa** [comment]
It's not part of core yet because new_api is still in progress. The design doc will need an overhaul once we're done, and then I will request it to be merged into the core repository.

**Comment by irungentoo** [comment]
@Astonex those ugly docs in the doc folder of the main repo are the docs I used to implement the protocol.

Writing proper docs that don't look like those takes a lot of time and I'm willing to help anyone that wants to do the writing.

**Comment by GrayHatter** [comment]
tox docs exist!!!
