### ISSUE TITLE
new_api: Cannot connect via SOCKS5

### ISSUE THREAD

**Issue by kytvi2p** [irungentoo/toxcore#1301]
With uTox 295bbc9 and Toxcore 6454552 I can no longer connect via a SOCKS proxy (Tor).

The following settings worked with the old API:

IPv6: No
UDP: No
Proxy (SOCKS 5):   Always Use 127.0.0.1 9050

**Comment by irungentoo** [comment]
This was a uTox issue: https://github.com/notsecure/uTox/commit/1ecacc3e31e2642a73b8839dfffd796b634ad8a0

**Comment by kytvi2p** [comment]
Oops, sorry about that.
