### ISSUE TITLE
Prevent jumbo frames in TCP...

### ISSUE THREAD

**Issue by ghost** [irungentoo/toxcore#1306]
... by redefining ```MAX_PACKET_SIZE``` to 1460 in ```TCP_server.h```

This would be mainly to prevent issues on older devices, and networks which utilize older hardware. Additionally, network-manager seems to default MTUs to 1500 on most consumer network devices anyway.

**Comment by GrayHatter** [comment]
@ghost have you seen any issues or errors?

**Comment by GrayHatter** [comment]
stale
