### ISSUE TITLE
crash when i try to use tox_encrypted_save

### ISSUE THREAD

**Issue by Mataes** [irungentoo/toxcore#1312]
Hi! i have a crash when try to use tox_encrypted_save in vc 2013 under windows.
i have 8Gb RAM. Is was on old api and on new i have it too.
Here is my call stack from vc2013. it crashes on this code:
		if (password && strlen(password))
		{
			size = tox_encrypted_size(tox);
			data = (uint8_t*)mir_calloc(size);
			if (tox_encrypted_save(tox, data, (uint8_t*)password, strlen(password)) == TOX_ERROR)
			{
                           ...

All data is normal:
		tox	0x05760278 {...}	Tox *
+		password	0x02dfb0f0 "111"	char *
		strlen(password)	3	unsigned int

Call stack:
 	libtox.dll!blockmix_salsa8() Line 1250	C++
 	libtox.dll!escrypt_kdf_sse() Line 255	C++
 	libtox.dll!crypto_pwhash_scryptsalsa208sha256_ll() Line 246	C++
 	libtox.dll!crypto_pwhash_scryptsalsa208sha256() Line 124	C++
 	libtox.dll!tox_derive_key_with_salt() Line 125	C++
 	Tox.dll!tox_encrypted_save(const Tox * tox, unsigned char * data, unsigned char * passphrase, unsigned int pplength) Line 17	C++
>	Tox.dll!CToxProto::SaveToxProfile() Line 97	C++
 	Tox.dll!CToxProto::MainOptionsProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 184	C++
 	user32.dll!_InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallDlgProcCheckWow@32()	Unknown
 	user32.dll!_DefDlgProcWorker@24()	Unknown
 	user32.dll!_DefDlgProcA@16()	Unknown
 	user32.dll!_InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallWinProcCheckWow@32()	Unknown
 	user32.dll!_SendMessageWorker@24()	Unknown
 	user32.dll!_SendMessageW@16()	Unknown
 	Miranda32.exe!OptionsDlgProc(HWND__ * hdlg, unsigned int message, unsigned int wParam, long lParam) Line 1125	C++
 	user32.dll!_InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallDlgProcCheckWow@32()	Unknown
 	user32.dll!_DefDlgProcWorker@24()	Unknown
 	user32.dll!_DefDlgProcW@16()	Unknown
 	user32.dll!_InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallWinProcCheckWow@32()	Unknown
 	user32.dll!_SendMessageWorker@24()	Unknown
 	user32.dll!_SendMessageW@16()	Unknown
 	comctl32.dll!Button_NotifyParent(struct tagBUTN *,unsigned int)	Unknown
 	comctl32.dll!Button_ReleaseCapture(struct tagBUTN *,int)	Unknown
 	comctl32.dll!Button_WndProc(struct HWND__ *,unsigned int,unsigned int,long)	Unknown
 	user32.dll!_InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallWinProcCheckWow@32()	Unknown
 	user32.dll!_DispatchMessageWorker@8()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	user32.dll!_IsDialogMessageW@8()	Unknown
 	Miranda32.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, wchar_t * cmdLine, int __formal) Line 269	C++
 	Miranda32.exe!__tmainCRTStartup() Line 618	C
 	Miranda32.exe!wWinMainCRTStartup() Line 466	C
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!___RtlUserThreadStart@8()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by GrayHatter** [comment]
can you still dup this?
