### ISSUE TITLE
Improvement proposal for ping datapackets

### ISSUE THREAD

**Issue by arucard21** [irungentoo/toxcore#1319]
I think the ping datapackets can be simplified, because it shouldn't be necessary to provide an encrypted ping ID. The goal of the ping datapackets is to know if you can get a response from the target node. This means you need to get a response and you need to know that response was sent from the target node. 

You can find out if you get a response to your request, by remembering to which nodes you sent a request. Whenever you receive a ping response, you can check if you sent a request to this node and mark it as having completed successfully. This should also weed out any ping responses that were sent without any request (either maliciously or accidentally). 

You can ensure that the response was sent by the target node by ensuring that you can verify that each datapacket was sent by the node it reports to be (in the node_id part of the datapacket). This can be done by providing a signature of the information in the datapacket along with that datapacket (an enveloped signature). This can be done with NaCl as described below.

Create signature:
`signature = crypto_sign( hash("request/response: + "node ID"), sender_private_key )`
Verify signature:
`crypto_sign_open(signature, sender_public_key) == hash("request/response: + "node ID")`

Technically, what this verifies is that the datapacket was sent by a node with access to the private key corresponding to the public key (client node_id) which is provided in the datapacket (which should only be the node that it reports to be) and that the message wasn't tampered with after it was signed (or the hash from the signature won't match the hash generated from the datapacket). This seems to fit the needs of the ping datapackets and removes the need for generating an additional ID or including a nonce in the packet, which simplifies the datapacket.

**Comment by codedust** [comment]
I don't really understand why the ping response should be immune to replay attacks? An attacker could easily wait for a ping request and replay the recorded response. Did I get something wrong?

**Comment by arucard21** [comment]
This proposed improvement actually doesn't try to prevent replay attacks for ping datapackets (both request and response) simply because it doesn't seem necessary. The only thing you can do by replaying the ping response, is to answer the ping request of another node by replaying a previously captured datapacket, making that node believe that the pinged node is still online. Any encrypted communication that follows can not be decrypted by the replaying node so those requests can not be answered. 

If you still wish to prevent replay attacks, you can just include a ping ID in the datapacket and make it part of the signed message. The ping ID wouldn't even need to be randomly generated, it could just start with 1 and increment with each use (though a random initial number would obfuscate the total number of pings sent). The clients would simply have to check that the ping ID is higher than the last known ping ID.

The reason I think encryption shouldn't be used in the ping request and response, is because encryption is intended to keep information hidden from other during transfer and the ping datapackets have no such information. As shown above, you can even send the ping ID in plain-text, as long as you sign the message. I think this will also contribute to making the code more maintainable in the future, since improvements to the encrypted communication would not need to be implemented here and the ping datapackets can be kept as small and simple as possible.

**Comment by codedust** [comment]
Pong messages that are vulnerable to replay attacks would be really useless imo. Why should you sign the request/response if an attacker could replay it.
Developers would also be confused because they expect the remote host to be up when they receive a valid ping response.

Therefore we should definitely add a ping ID to both the request and the response (as you suggested).
I would also add encryption simply because toxcore does not sign anything in the current implementation (see https://github.com/irungentoo/toxcore/issues/1313#issuecomment-89795939).

**Comment by arucard21** [comment]
From the NaCl documentation, it seems like `crypto_sign` should be possible as long as the `crypto_box_keypair` created a private key of `crypto_sign_SECRETKEYBYTES` bytes, but I can't be sure of that. If it is not possible with the same key, then the overhead of maintaining a 
separate keypair would outweigh many of the benefits this proposed improvement could have. However, I would still recommend using only incrementing ping ID's to avoid replay attacks from both the request and the response.

I would also like to comment on these 2 points you made:
- `Why should you sign the request/response if an attacker could replay it.` Signing something allows you to verify where it came from and to verify that it is still in the same state as when it was signed. Signing something and preventing replay attacks are separate matters that should be dealt with separately (signing for authenticity, ping ID to prevent replay attacks).
- `Developers would also be confused because they expect the remote host to be up when they receive a valid ping response.` A node could always go offline (even right after it sent a valid ping response), so developers always need to take into account that a node could be offline or unreachable at any moment. I don't think they would be confused by it.

**Comment by codedust** [comment]
:+1: Using incrementing ping ID's definitely seems to be a good solution.

> Signing something allows you to verify where it came from and to verify that it is still in the same state as when it was signed.

My point was that integrity and authenticity are worthless (in this case) if the ping response is always the same (and therefore vulnerable to replay attacks).


> A node could always go offline (even right after it sent a valid ping response), so developers always need to take into account that a node could be offline or unreachable at any moment.

My concerns are that an attacker could flood the tox network with recorded ping responses (possibily right after ping requests are send) and nodes wouldn't be able to determine anymore whether another node is up. A node could be connected to e.g. 10 "active" nodes from which only one is up and running and the other nine are down and seem to be up because an attacker replays ping responses.
Making sure that messages are transferred correctly is a completely different issue.

**Comment by arucard21** [comment]
Agreed, replay attacks should be prevented. 

So a ping ID should be included, and if we only encrypt and not sign the message, then the datapackage format is pretty much the same as before. The only improvement that needs to be made, is to use incrementing ping ID's and check it against the last known one. This comes down to basically the same improvement I suggested in https://github.com/irungentoo/toxcore/issues/1313#issuecomment-89826667, especially if we use the nonce as Ping ID. So maybe this is not necessary as a separate improvement suggestion.

**Comment by GrayHatter** [comment]
if you use deterministic pings, you open yourself up to additional attacks.

I'm going to need to see an argument as to what we gain by this suggestion.
