### ISSUE TITLE
Impossible comparisons between filenumber and MAX_CONCURRENT_FILE_TYPES

### ISSUE THREAD

**Issue by carbin** [irungentoo/toxcore#1321]
Checking if filenumber is >= to MAX_CONCURRENT_FILE_TYPES is done a few times in Messenger.c, eg. https://github.com/irungentoo/toxcore/blob/master/toxcore/Messenger.c#L2112

As filenumber is a uint8 and MAX_CONCURRENT_FILE_TYPES is defined as 256 this comparison will always be false as if filenumber is assigned to a higher value it will overflow and wrap.

**Comment by irungentoo** [comment]
This comparison is just there for extra safety if the MAX_CONCURRENT_FILE_TYPES define gets lowered in the future.
