### ISSUE TITLE
Add support for h.264

### ISSUE THREAD

**Issue by rbieb** [irungentoo/toxcore#1322]
Would be great to have.

@GrayHatter

**Comment by thousandsofthem** [comment]
i believe licensing issues prevents this

**Comment by GrayHatter** [comment]
http://www.openh264.org/ seems to be an option?

**Comment by GrayHatter** [comment]
Did some research on h.264 according MPEG LA (the licensor for 264) they believe that there are only two parties who are required to pay licensing fees to use H.264; the person distributing the codec (toxcore), and the last person distributing the content (that would be end users). Distributing video video for free to end users will be free for the life of the project http://www.mpegla.com/Lists/MPEG%20LA%20News%20List/Attachments/74/n-10-08-26.pdf So endusers are in the clear.  

However toxcore may not be as the distributor of the codec. As part of the openh264 codec from cisco, they've provided a indepth video https://vimeo.com/79578794 TL;DW you have to get the binarys from cisco's servers. leaving the only remaining question.

Is it worth the work to incorporate binaries that someone else compiled for us? Is the gain even worth it?

**Comment by fcore117** [comment]
Better to use vp9, binary download would be horror and adding more codecs to core would bloat up core. Using other binaries would add serious dangers too.

Other option if really h264 is even wanted is to use light h264(x264?) library and integrate it, move Tox to server where MPEG LA cannot get their hairy hands and ignore them.

**Comment by codedust** [comment]
Mozilla and the Xiph.Org Foundation are building [Daala](https://wiki.xiph.org/Daala), a free video codec with performance superior to H.265. It's will be used in Firefox's WebRTC implementation in the future and therefore it is designed for real-time communication. Using Daala would be a better option than using the nonfree H.264 codec imo.

**Comment by zetok** [comment]
@fcore117 switch to vp9 is planned in the future.. that being said..

@codedust it will take a **very long time** for Daala to mature (years), but it indeed looks promising. Who knows..?

**Comment by Tirifto** [comment]
I think Tox should just stick to libre software and formats. I'm for sticking to those, which means VP and eventually Daala.

**Comment by im-grey** [comment]
So exited for Daala.

**Comment by ProMcTagonist** [comment]
> I think Tox should just stick to libre software and formats.
+1
This really shouldn't be a novel idea.

**Comment by GrayHatter** [comment]
stale, nonfree and incomplete issue. Why do we need h.264 support?

**Comment by zoff99** [comment]
thats actually done now
@GrayHatter
