### ISSUE TITLE
Building works, toxcore doesn't

### ISSUE THREAD

**Issue by Sorunome** [irungentoo/toxcore#1323]
Hey, running on archlinux.
I'm trying the tox-git package from AUR which, as far as i know, should just fetch the latest git version from here and compile it.
The thing is, it builds fine etc. and I can build clients like utox fine, but messages never get through, contacts on the other end said they got a 4gb file to receive and other weird stuff like that, so I suspect there is something wrong with the encryption.

**Comment by zetok** [comment]
>I suspect there is something wrong with the encryption.

nope.

Incompatibility between APIs that clients use. Issue will be gone once all clients get on new API.

If that's all, please close the issue.

**Comment by Sorunome** [comment]
oh, ok, gotcha
