### ISSUE TITLE
Toxcore dll

### ISSUE THREAD

**Issue by SimonDanisch** [irungentoo/toxcore#1325]
Hi I'm trying to write a Toxcore wrapper for [Julia](http://julialang.org/) and running into a few issues.
First of all, are there pre compiled binaries for windows of toxcore itself, so that I can download them automatically? I haven't tried linux yet, but I guess compiling it on demand shouldn't be difficult.
So far, I took the windows binaries from the uTox and qTox, but there where symbols missing.
Not sure if that's because they're not compiled to be used like that or if it's some other issue.
Symbols missing for the example that I tried to run:
```
tox_self_set_name 
tox_self_set_status_message
tox_bootstrap
tox_iterate
tox_iteration_interval
```
Using dependency walker suggests, that these symbols are indeed not exported, so I guess the issue is not in my Julia code.

Best,
Simon

**Comment by Impyy** [comment]
You can grab pre compiled binaries from https://jenkins.libtoxcore.so/view/Libs/

**Comment by SimonDanisch** [comment]
Excellent!
This fixes it :)
Thanks for the quick reply.

**Comment by Renha** [comment]
https://jenkins.libtoxcore.so/view/Libs/ isn't accessible as for now

**Comment by Impyy** [comment]
We no longer use libtoxcore.so, try https://build.tox.chat/view/libtoxcore/ instead.

**Comment by Renha** [comment]
well thank you!
