### ISSUE TITLE
TCP heartbeat

### ISSUE THREAD

**Issue by reepr** [irungentoo/toxcore#1327]
All the Tox clients I've tried have issues connecting to the network when internet goes down when TCP is set. Everything is fine after restarting the app. TCP heartbeats or polling at an interval can reconnect after an outage?

NAT traversal doesn't have anything to do with it because I can connect and chat normal when it does.

TCP is good for battery life on phones and for Antidote, its the only option for connecting. Its what Antox uses out of the box.

https://github.com/subliun/Antox/issues/27

**Comment by GrayHatter** [comment]
stale, and poorly described issue
