### ISSUE TITLE
Tox_Options shouldn't rely on null-terminated strings

### ISSUE THREAD

**Issue by suhr** [irungentoo/toxcore#1328]
For now `Tox_Options` struct looks like this:

```c
struct Tox_Options {
...
const char *proxy_host;
...
};
```

This issue proposes to make it like this:

```c
struct Tox_Options {
...
const char *proxy_host;
uint8_t proxy_host_length;
...
};
```

Motivation: today C is probably the only popular programming language where null-terminated strings are used. While converting a native string to null-terminated one and passing it to a function that uses it only *once* can be easily encapsulated in bindings, using null-terminated strings in stucts causes problems. These problems lead to these solutions:
* Require C strings in exported bindings API. This is **ugly.**
* Get rid of the options struct, export one big `new` function. This is even more ugly.
* Add some `_Tox_Options` and convert it to `Tox_Options` in the `new` function. This is *kludgy.*
* Extend `Tox_Options` to `_Tox_Options` and store converted string in it, then just pass internal `Tox_Options` in the `new` function. This is even more kludgy.

Making Tox_Option not to rely on null-terminated strings will resolve these issues and will make bindings creation nice and kludge-free.

**Comment by irungentoo** [comment]
The functions that this is passed to accept a NULL terminated string as the argument which means it makes sense for it to be a NULL terminated string.

**Comment by suhr** [comment]
You mean, `addr_resolve_or_parse_ip` requires a null-terminated string?

**Comment by irungentoo** [comment]
functions like getaddrinfo() require a NULL terminated string.
