### ISSUE TITLE
tox_new error is wrong and confusing

### ISSUE THREAD

**Issue by JFreegman** [irungentoo/toxcore#1329]
According to this issue https://github.com/Tox/toxic/issues/328 a kernel that doesn't support ipv6 but tries to use the ipv6 option (default) will fail in tox_new with TOX_ERR_NEW_MALLOC. I've had two other people report this error to me and am only now realizing that they're all the same issue of lacking ipv6 support. It would be useful to have a more specific error so that I can properly decide whether or not to try to fall back to IPv4 instead of doing a catch-all (https://github.com/Tox/toxic/commit/4d73f8b24164a452b8dd3dbf42ccca318f123ba0). In any case, TOX_ERR_NEW_MALLOC is plain wrong.

**Comment by subliun** [comment]
This is also an issue on Android. Calling tox_new without network permissions (this prevents toxcore from opening sockets) fails with TOX_ERR_NEW_MALLOC. There needs to be a more specific error for this case.

**Comment by irungentoo** [comment]
https://github.com/irungentoo/toxcore/commit/d05e39274ca4ce27ddb02c0ec15c0ed1c46000a3
