### ISSUE TITLE
Unique identifier for groups

### ISSUE THREAD

**Issue by beemaster** [irungentoo/toxcore#1330]
At the moment group chats do not have unique identifiers (for example friends have such identifier which is public key). Imagine following scenario:

1) Open qTox and create 2 group chats (G0, G1) with same participants. They will have groupnumber 0 and 1.
2) Type some messages in chats to have some history. Close qTox.
3) Open uTox with the same data file. Delete groupchat 1 (G1) and add groupchat 2 (G2). Close uTox.
4) Now if you open qTox again, it will confuse G1 with G2. In other words, there is no way for qTox to notice that G1 was deleted.

The idea is to create GUID for every group chat, like a public key for friends. What do you think?

**Comment by suhr** [comment]
Already implemented in the new groupchats (see https://github.com/JFreegman/toxcore).

**Comment by beemaster** [comment]
Perfect, thanks!
