### ISSUE TITLE
Missing Raspberry Pi packages on repository

### ISSUE THREAD

**Issue by Overlord23** [irungentoo/toxcore#1354]
Hi,

As I have a Raspberry Pi lying unused, I would help by running a bootstrap node on it.
I found this article from Tox devel blog https://blog.tox.im/2014/11/30/tox-bootstrap-now-packaging-for-armhf/ so, I added the Tox repo and tried to install tox-bootstrapd, but no compatible package is found.
Browsing the repo from a web browser, I can't find any ARMHF compatible package.
Is that intended to be so or it's an issue?

**Comment by kalon33** [comment]
Hi Overlord23,

I frequently build Tox and Tor packages (unofficial ones) for Ubuntu 14.04LTS in my ppa: https://launchpad.net/~kalon33/+archive/ubuntu/gamesgiroll/, where I keep updated packages for my servers and various appliances (BBB...) so you will probably find what you want there.

But be careful as there are also some other updated packages that you may not want, and I provide these packages without any warranty (like free software is usually provided). That doesn't mean that I can't or won't help if needed, or update/upload packages to this PPA if requested.

Hope that it helps.

**Comment by Overlord23** [comment]
@kalon33 thank you for replying, 
I've checked your PPA but I didn't find tox-bootstrapd.
Probably I will compile it on my system as soon as I get some free time.

**Comment by kalon33** [comment]
@Overlord23 the toxcore source package produces multiple binary packages, namely https://launchpad.net/~kalon33/+archive/ubuntu/gamesgiroll/+files/tox-bootstrapd_0.0.0%2B20150527.r3393-1%7Eppa14.04%2B1_armhf.deb which depends on some other ones. You should probably add the PPA and install that package using apt-get, as dependencies are complex between toxcore modules, libsodium and tox-bootstrapd. I don't think you would be that worried with other packages from the PPA if you install it on a RPi.

**Comment by Overlord23** [comment]
Awesome, thanks! I will install it from your repo.

**Comment by GrayHatter** [comment]
consider pulling from build.tox.chat we have a repo set up there as well
