### ISSUE TITLE
Introduce “TOX_VERSION_UNSTABLE” in tox.h

### ISSUE THREAD

**Issue by suhr** [irungentoo/toxcore#1355]
Even though the new API is here, the tox API continues to change. And because of that, clients and users have to track these changes. Unfortunately, mismatch of installed toxcore version and version required by client may cause not only cryptic build and runtime errors, but even a data loss: https://github.com/tux3/qTox/issues/1731

This issue proposes to introduce a special “unstable” version in toxcore. This is a temporary API: in the future, when toxcore gets stable, this should be removed and semantic versioning should be used.

“Unstable” version is a number that *must* be incremented on every API breaking change. Clients should be able to check unstable version both at compile time and runtime. When build or client detects incompatible unstable version of toxcore, it should warn user about that and interrupt building or kill the client immediately.

This will prevent mysterious compile and runtime errors and save user data.

cast @tux3 @agilob @zetok

**Comment by LapFox** [comment]
:+1:

**Comment by ProMcTagonist** [comment]
+1

**Comment by monoman** [comment]
+1.

Project Mono has being this for more than a decade with success, in the
frontier between its native and managed components. IMHO it is a good
thing!!!

Rafael Teixeira
O..:.)oooo

**Comment by quininer** [comment]
+1

**Comment by GrayHatter** [comment]
toxcore will support semver soon everyone message @irungentoo and tell him to start semver for toxcore now!

**Comment by tux3** [comment]
"Soon™"
