### ISSUE TITLE
tox_new() probleme

### ISSUE THREAD

**Issue by Ogromny** [irungentoo/toxcore#1359]
I,
My code wont execute i crash at tox_new(), when i execute i get this:
```Erreur de segmentation (core dumped)```

```
#include "main.h"

/*
 * compiler: gcc
 * option:
*/

int main(void) {
  /* CONVERTION CLEF EN BINAIRE */
  uint8_t *clef_public = malloc(TOX_PUBLIC_KEY_SIZE);
  hex_string_to_bin(BOOTSTRAP_KEY, clef_public);

  /* CREATION D'UN TOX */
  Tox *m_tox = create_tox();

  /* PERSONNALISATION DU TOX */
  tox_self_set_name(m_tox, MON_NOM, strlen(MON_NOM), NULL);
  tox_self_set_status_message(m_tox, MON_STATUS, strlen(MON_STATUS), NULL);
  tox_self_set_status(m_tox, TOX_USER_STATUS_AWAY);

  /* ASSIGNATION */

  /* BOOTSTRAP */
  tox_bootstrap(m_tox, BOOTSTRAP_ADDRESS, BOOTSTRAP_PORT, clef_public, NULL);

  /* CONNECTION BOUCLE */
  while (true) {
    /* ITERATION */
    tox_iterate(m_tox);

    /* CHECK SI CONNECTER */
    int connecter = tox_self_get_connection_status(m_tox);
    printf("%d\n", connecter);

    /* SUSPEND L'ITERATION POUR Xs */
    usleep(tox_iteration_interval(m_tox) * 1000);
  }
  tox_kill(m_tox);

  return 0;
}

Tox *create_tox(void) {
  /* DECLARATION VARIABLE */
  TOX_ERR_NEW tox_err;

  /* CREATION TOX */
  return tox_new(NULL, &tox_err);
}

void hex_string_to_bin(const char *in, uint8_t *out) {
  size_t len = strlen(in);
  char *value = malloc(len);

  // si invalide
  if (value == NULL)
    printf("[ERREUR]: hex_string_to_bin\n");

  for (size_t i = 0; i < len; i++, in += 2)
    sscanf(in, "%2hhx", &value[i]);

  out = (uint8_t)value;
}

```
```
#ifndef MAIN_H
#define MAIN_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h> // strlen
#include <unistd.h> // usleep
#include "toxcore/tox.h"

#define BOOTSTRAP_KEY                                                          \
  "E398A69646B8CEACA9F0B84F553726C1C49270558C57DF5F3C368F05A7D71354"
#define BOOTSTRAP_ADDRESS "195.154.119.113"
#define BOOTSTRAP_PORT 334455

#define MON_NOM "TEST"
#define MON_STATUS "TEST"

#define SLEEP_TIME 5000 // 5s

int main(void);
void hex_string_to_bin(const char *in, uint8_t *out);
Tox *create_tox(void);

#endif

```

what is the probleme ?

PS: I'm french, sorry for my bad english :s

**Comment by codedust** [comment]
With the latest version of toxcore, your code doesn't crash at startup.


in main.h: `#define BOOTSTRAP_PORT 334455` should probably be `#define BOOTSTRAP_PORT 33445`
in hex_string_to_bin() `char *value` should probably be `uint8_t *value`

Try updating and recompiling toxcore.

**Comment by Ogromny** [comment]
I have the latest version of toxcore, i have recompiled main.c with, but again "Erreur de segmentation (core dumped)", 
but when i execute with su privilege, i get no error, but the program block at tox_new :/

**Comment by codedust** [comment]
Could you quickly explain your setup? Does `#include "toxcore/tox.h"` mean, `main.c` is stored inside the main folder of the toxcore git repo?

The best way to include toxcore would be to install toxcore system-wide (`sudo make install`). And then inlude it via `#include <tox/tox.h>`.

**Comment by irungentoo** [comment]
how do you compile this?

**Comment by Ogromny** [comment]
i include <tox/tox.h>
and i compile : gcc main.c -ltoxcore

**Comment by irungentoo** [comment]
@Ogromny are you sure your tox.h include matches the toxcore lib you are linking with: -ltoxcore?

**Comment by Ogromny** [comment]
Yes i am sure :/

**Comment by codedust** [comment]
Since one character of the publickey string represents only 4bit, `size_t len = strlen(in);` should be `size_t len = strlen(in)/2;` instead. Anyway, I don't think this is related to the segfault.

**Comment by Ogromny** [comment]
```
void hex_string_to_bin(const char *in, uint8_t *out) {
  size_t len = strlen(in) / 2;
  uint8_t *value = malloc(len);

  // si invalide
  if (value == NULL)
    printf("[ERREUR]: hex_string_to_bin\n");

  for (size_t i = 0; i < len; i++, in += 2)
    sscanf(in, "%2hhx", &value[i]);

  out = value;
}
```

But again segfault :/

**Comment by czarkoff** [comment]
sscanf expects *, not **. Also, why not compile your code with "-g" and use gdb?

**Comment by Ogromny** [comment]
Again segfault,
do you think it might come from my system ?

**Comment by Ogromny** [comment]
I reinstalled tox and now it's work :)

**Comment by codedust** [comment]
Nice! Good luck for your project!

**Comment by Ogromny** [comment]
Thank you :D
