### ISSUE TITLE
make check network_test fails

### ISSUE THREAD

**Issue by seanlaguna** [irungentoo/toxcore#1365]
Hello I have compiled toxcore from the github repo as of the most current commit (3299452dd947f77f0d30842bcf1470dc760816c4). I followed the compilation instructions and ran `make check` afterward to see how well the compilation process went. This is what happened:

```
=====================================
   tox 0.0.0: build/test-suite.log
=====================================

# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: network_test
==================

Running suite(s): Network
50%: Checks: 2, Failures: 1, Errors: 0
../auto_tests/network_test.c:66:F:addr_resolv_localhost:test_addr_resolv_localhost:0: Expected family AF_INET6, got 2.
```

Looks like a minor networking bug (or maybe the test is outdated)! Let me know if there's anything I can do to help fix this problem, whether it's a problem with my configuration or a problem with toxcore!

**Comment by GrayHatter** [comment]
not you're issue, this happens when the nextwork/DHT/system is slow to respond. Try running it a few times, and it'll all pass...
