### ISSUE TITLE
Failing to load repositories on Fedora 22

### ISSUE THREAD

**Issue by alexkaskasoli** [irungentoo/toxcore#1370]
I have a fresh Fedora 22 install, added the repo keys and ran `dnf update`:

    sudo dnf update
    Importing GPG key 0x7DF12B85:
     Userid     : "Tox RELENG (Tox build system) <build@tox.im>"  
     Fingerprint: DBDC 8C5F D3C7 0CA6 846E 348B 4B11 1B5D 7DF1 2B85
     From       : https://repo.tox.im/pubkey.gpg
    Is this ok [y/N]: y
    Tox Nightly         

But when I try to search for `tox`:

    [user@localhost] : ~ $ dnf search tox
    Warning: failed loading '/etc/yum.repos.d/tox.repo', skipping.
    Last metadata expiration check performed 19 days, 17:37:57 ago on Sat May 30 02:15:16 2015.
    ===================== N/S Matched: tox ======================
    perl-AutoXS-Header.noarch : Container for the AutoXS header
                          : files
    woodstox-core-javadoc.noarch : API documentation for
                             : woodstox-core
    detox.x86_64 : Utility to replace problematic characters in
             : file names
    fotoxx.x86_64 : Photo editor
    python-tox.noarch : Virtualenv-based automation of test
                  : activities
    woodstox-core.noarch : High-performance XML processor

**Comment by linux-modder** [comment]
which client is intended ?

**Comment by alexkaskasoli** [comment]
Hi @linux-modder , sorry for the delay.
I would like to run Toxic but I'm just wondering why the Fedora repos doesn't seem to work. Is it down?

**Comment by linux-modder** [comment]
@alexkaskasoli , as  seen below  if the  tox repo is  in play toxic  DOES show up I recommend:
'sudo dnf clean all  && sudo dnf install toxic'


{snipped} Tue, 23 June 19:20:02 EDT 2015 ~
 dnf info toxic
Last metadata expiration check performed 3 days, 7:07:38 ago on Sat Jun 20 12:17:17 2015.
Available Packages
Name        : toxic
Arch        : i386
Epoch       : 0
Version     : 0.6.0
Release     : 633
Size        : 2.6 M
Repo        : tox
Summary     : no description given
URL         : https://tox.im
License     : GPLv3+
Description : no description given

**Comment by alexkaskasoli** [comment]
@linux-modder Thank you, that solved my problem.
