### ISSUE TITLE
Tray icon and notification sound

### ISSUE THREAD

**Issue by leannecrow** [irungentoo/toxcore#1373]
Both do not work. I'm using qTox on ubuntu 15.04 straight from the PPA. When I receive a message, the icon begins to flash between "Light color tox" and "no-image-" icon. Like it's a place holder image.
![selection_003](https://cloud.githubusercontent.com/assets/8831324/8391531/febf3c54-1cdf-11e5-9b56-9fc16aab759d.png)

I have the sound enabled but it doesn't play anything when I receive a message.

**Comment by Impyy** [comment]
Please report this issue [here](https://github.com/tux3/qTox) instead.
