### ISSUE TITLE
[Feature request] Better visualisation for drag & drop effects

### ISSUE THREAD

**Issue by zetok** [irungentoo/toxcore#1378]
Dragging & dropping does different stuff when file is dragged to chat or to text input field.
To show visual difference between those actions, something like that could be used:
![20150630 qtox drag drop files to send](https://cloud.githubusercontent.com/assets/3148759/8441303/42b69ab0-1f6f-11e5-8525-ae93a7c2b988.png)

Those black-ish fields would be shown only when file is being dragged into qTox, and should be partially transparent.

**Comment by ProMcTagonist** [comment]
:+1:  +  can we do it in translucent Tox Green instead?

**Comment by zetok** [comment]
@ProMcTagonist if green would be used instead of black-ish, then it would look bad..

**Comment by zetok** [comment]
uh, I've just realized that I've opened issue in wrong repo… sorry for spam. https://github.com/tux3/qTox/issues/1947 ← where it rightfully belongs
