### ISSUE TITLE
real-time streaming

### ISSUE THREAD

**Issue by lucabaldesi** [irungentoo/toxcore#1385]
Hi everybody!
I'm playing with a distribution protocol for IPTV services and I'm 
currently looking for a library for
P2P communication.
What I need is a lossy service (UDP) which takes care of establishing 
connection between nodes
including NAT traversal and cryptography functionalities.

As far as I understand from the documentation, Toxcore can provide 
exactly this service by taking
advantage from the kademila DHT.
If I'm not wrong I can implement UDP sending/receiving using this couple 
of functions:
* tox_friend_send_lossy_packet
* tox_callback_friend_lossy_packet

Does it sound correct?
Does tox on its own generate other network traffic other than DHT 
messages (e.g., during bootstrap)?

I noted in the code the following calling tree:
tox_friend_send_lossy_packet
     --> send_custom_lossy_packet
         --> send_lossy_cryptpacket
             --> send_data_packet_helper
                 --> send_data_packet
                     --> send_packet_to
                         --> send_packet_tcp_connection
It seems like that lossy packet sending function gracefully degrades to 
TCP when something bad occurs, is
that correct? What can cause this behavior?

P.s. I firstly sent this message in the development mailing list but I've not received an answer yet. Is the mailing list still active?

**Comment by Dirius77** [comment]
The mailing list doesn't seem to really be a thing. And if I recall correctly, the thing that will cause it to degrade to TCP, is if it finds itself unable to punch through an use UDP.

**Comment by GrayHatter** [comment]
> The mailing list doesn't seem to really be a thing. 

Read only mode

**Comment by ProMcTagonist** [comment]
The mailing list domain has been seized by a malevolent third party.  A new mailing list may be put up eventually under tox.chat but it's low priority compared to the main site, the wiki, and jenkins.

**Comment by agilob** [comment]
Go to #tox-dev irc channel and ask about [toxvpn](https://github.com/denis4net/toxvpn) I don't know much about this project but sound like something you might want to consider.

**Comment by GrayHatter** [comment]
I'm going to close this and echo @agilob, only I'm going to suggest https://github.com/cleverca22/toxvpn/ instead

@cleverca22
