### ISSUE TITLE
Tox does not support Unicode

### ISSUE THREAD

**Issue by J2TeaM** [irungentoo/toxcore#1390]
I can not use Tox to chat in Vietnamese because it does not support unicode input. Screenshot:

![toxx-unicode](https://cloud.githubusercontent.com/assets/5250117/8726376/0fc28320-2c04-11e5-85de-8ead0c695000.PNG)

**Comment by LapFox** [comment]
This looks like a client issue

**Comment by suhr** [comment]
Not a toxcore issue. Also, what client do you use?

**Comment by ProMcTagonist** [comment]
Unicode is bloat, apparently.

You should complain at https://github.com/notsecure/utox/issues.

**Comment by suhr** [comment]
@J2TeaM Try to use qTox or Toxy.

**Comment by GrayHatter** [comment]
utox supports unicode, you can open an issue at the above link. But the problem seems to be that you don't have a supported font installed.

**Comment by J2TeaM** [comment]
@suhr : I'm using uTox. Thank you for your suggestion to use qTox, I've tried, and it's great, though the interface is not much different from uTox :+1:

![image](https://cloud.githubusercontent.com/assets/5250117/8745081/6514dbdc-2ca6-11e5-8859-1140d6f68b95.png)


@ProMcTagonist : Thank you for the link! I have reported this issue.
