### ISSUE TITLE
Sync Profile Across Devices

### ISSUE THREAD

**Issue by smalltock** [irungentoo/toxcore#1393]
For a while I ran the same profile on my desktop, laptop, and mobile device. I stopped doing this because I encountered a problem. When I add a contact to one device, the others do not synchronize. Of course this is to be expected, so each time, I would manually send my .tox profile to the other devices to update their contact list. This was already troublesome, but to make matters worse, this operation didn't seem ostensibly or outwardly feasible after having added contacts to more than one device without having synchronized between them.

It is plainly obvious, at least to me, why one would want to run the same profile on multiple devices. It cleans not only your own contact list, but that of those with whom you are friends.

For this reason, I request that if multiple instances of the same profile detect eachother on the network, that they synchronize contacts and any other necessary data. Thank you for your time :)

**Comment by agilob** [comment]
I think this is a toxcore issue and it was mentioned a few times [there](https://github.com/irungentoo/toxcore/issues). Anyone else wants to confirm?

**Comment by ProMcTagonist** [comment]
Toxcore problem that will be solved in the future.

**Comment by smalltock** [comment]
Looks like it has indeed been suggested. I swear I did a few searches before submitting this one and didn't come up with anything. I'm sorry for the duplicate.

**Comment by LuccoJ** [comment]
@smalltock in the meantime, you may perhaps use the open, distributed Syncthing to keep your .tox profile synced among different devices.

**Comment by GrayHatter** [comment]
every dev that I can remember thinks syncing a full profile across tox is a bad idea, so unless you can argue for it closed as a dup of #843
