### ISSUE TITLE
Clients should display toxcore version

### ISSUE THREAD

**Issue by blobgo** [irungentoo/toxcore#1395]
This is an idea for the guidelines: The tox clients should display the version of toxcore they use somehow/somewhere in it's UI.
Actually it may just be okay to display the commit hash. Later, when 0.xx releases will be published the version number may be enough.

This would maybe help to find incompatibilities (between client <-> core and between two different clients which chat together). So you can simply check out what toxcore the client internally uses and get out if it is one too old or whatever.

Related: https://github.com/irungentoo/toxcore/issues/1353, https://github.com/irungentoo/toxcore/issues/1355

**Comment by czarkoff** [comment]
Yes, and toxcore should have versions.

**Comment by strixaluco** [comment]
Indeed, this should be useful.

**Comment by blobgo** [comment]
As https://github.com/tux3/qTox/issues/2086 is already closed, because they show the toxcore version now I think this issue can be closed.
