### ISSUE TITLE
Website confusion 

### ISSUE THREAD

**Issue by herrniemand** [irungentoo/toxcore#1396]

**Comment by herrniemand** [comment]
toxcore current website is tox.**chat**. But there is tox.**im** as well. I am a bit confused about that

**Comment by optimumtact** [comment]
tox.chat is the offical website

tox.im is under the control of someone no longer affiliated with the tox project

**Comment by herrniemand** [comment]
@optimumtact WOW! I will inform my guys.
P.S. It is quite problematic that tox.im is still in top results. Maybe complain to google?

**Comment by herrniemand** [comment]
@optimumtact I already see it.
P.S. Good luck to you guys. Sad that it had happen.
