### ISSUE TITLE
Design a language-agnostic API between ProjectTox-Core and consumers

### ISSUE THREAD

**Issue by jbangert** [irungentoo/toxcore#140]
It would be nice if there were a language-independent API between ProjectTox-Core and applications on top of it, and a concise statement as to what the core handles and what it does not. Ideally, the core would expose nothing but an interface to establish different types of connections (unreliable, reliable) with different types (should be an arbitrary tag, like 'chat', 'video' , 'remote desktop') between and relay presence information about DHT nodes identified by their public key. Just like sodium provides us with a very small and simple crypto_box api, core should just provide a simple API, e.g. (rough draft, should probably change) 

joinDHT(bootstrap-node)
isPresent(clientID)  - true if node is known in the DHT, false otherwise
openChannel(clientID, reliable, type) - establish a 'connection' in core
sendMessage(channel,Message) - send message to connection 
closeChannel(channel)  - abandon a connection

while a 'connection' is established, the core will perform and maintain UDP hole punching, mask IP changes, etc. 

This API could either be provided as a C-interface, or possibly via some sort of remoting interface (i.e. protobuf-rpc on stdin/stdout), so that the core can be properly sandboxed (being the only component dealing with priveleged information) or implemented in a safer language (rust, go or haskell).

**Comment by codedust** [comment]
@irungentoo I think this can be closed now as the new API is already implemented.
