### ISSUE TITLE
Windows cross compile error

### ISSUE THREAD

**Issue by randoms** [irungentoo/toxcore#1401]
After you run

    $WINDOWS_TOOLCHAIN-gcc -Wl,--export-all-symbols -Wl,--out-implib=libtox.dll.a -shared -o libtox.dll *.o ../lib/*.a /usr/$WINDOWS_TOOLCHAIN/lib/libwinpthread.a -liphlpapi -lws2_32 -static-libgcc

you will get an error

    ../lib/libopus.a(analysis.o): In function `tonality_analysis':
    /home/randoms/build/opus-1.1/src/analysis.c:486: undefined reference to `net'

the fix is simple, you can find it  [here](https://github.com/xiph/opus/commit./8adff0bb31989deb616ca72d16fc3e791ed91b10)

Maybe you can replace the opus link with a better [one](https://github.com/xiph/opus).

**Comment by nurupo** [comment]
Can't reproduce. What is the system you are using and what is the cross-compiler version?

**Comment by randoms** [comment]
I used a vm, just as  guide said.
System Ubuntu 15.04 x64
compiler detail

    COLLECT_GCC=i686-w64-mingw32-gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-w64-mingw32/4.9-win32/lto-wrapper
    Target: i686-w64-mingw32
    Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --libexecdir='/usr/lib/gcc-mingw-w64' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++ --enable-lto --with-plugin-ld --enable-threads=win32 --program-suffix=-win32 --program-prefix=i686-w64-mingw32- --target=i686-w64-mingw32 --with-as=/usr/bin/i686-w64-mingw32-as --with-ld=/usr/bin/i686-w64-mingw32-ld
    Thread model: win32
    gcc version 4.9.2 (GCC) 

I

**Comment by GrayHatter** [comment]
Also can't reproduce. @ me if you still need help. Or find us in #tox on freenode for realtime support.
