### ISSUE TITLE
https://tox.chat: qTox Screenshot

### ISSUE THREAD

**Issue by ElLamparto** [irungentoo/toxcore#1405]
I realize it may not be a proper place for the issue, but it is important and I do not know where to put it otherwise.

On https://tox.chat there is a qTox screenshot. On the user list there is Alex with a message "you're going to DIE" and with a photograph of Alex Jones.

Personally I respect Alex Jones very much and - frankly - if it was my first encounter with Tox, I would keep away from it - just because of the silly screenshot. I also think that Tox must be politically neutral.

I suggest replacing that screenshot asap.

**Comment by Impyy** [comment]
https://github.com/Tox/Tox-Website/pull/41

**Comment by linux-modder** [comment]
@ElLamparto, While I could possibly  see you issue, although I personally  think you are a armchair  fan  if that as that is a KNOWN catch phrase of  Alex Jones from years back and its a Tag line,  AKA bio line Users can  change that  at will much like that  Avator for a  profile.

**Comment by o-jasper** [comment]
To be frank, I dont like Alex Jones, spouts too much bullshit. (I am anti establishment)

**Comment by ElLamparto** [comment]
@o-jasper, I don't mind your opinion on Alex Jones at all, but the main Tox page is just not a right place to express it. It is counter productive.

By the way, I do not like the phrases below either:
"So, what are you waiting for?, Select your OS and get started!"

This is pushing people and nobody likes to be pushed. Counter productive too.
