### ISSUE TITLE
Create a chat robot so new users can test the software before having any friends

### ISSUE THREAD

**Issue by najamelan** [irungentoo/toxcore#1406]
IM software works because you have friends that use it as well. As a new product Tox needs to attract new users. One thing I find a bit challenging is that I can't see the software work at all until I can convince someone to install and use it as well. 

If you would run a server with one or several AI bots people would be free to add as friends to test the software, it would make it live much more from the start. There is several FOSS ones available, like Alice: http://www.alicebot.org/about.html

**Comment by najamelan** [comment]
Ok,

I just found the groupbot on the wiki, that looks like a good start.

**Comment by GrayHatter** [comment]
@irungentoo close this as solved

**Comment by LittleVulpix** [comment]
There used to be a LoadTest, python test bot. you could add it and talk to it and it'd send you back whatever you said. It was perfect for testing; sadly, the pyTox developer no longer maintains it and the project died with the api break. It'd be nice to have a "single-user" bot like this again.

**Comment by zetok** [comment]
@najamelan there are already bots that may act in similar way:
* [Lee](https://github.com/zetok/Lee) - not really an AI, and given that it feeds on user input from groupchat, whatever it says may be.. questionable. ID: 90F4C2558794EDC54C62585541DC7105583D9E20B5B29F0034B5032A15F4CE3CEC4927D6D779
* Spambot - https://github.com/zetok/tox-rust-neurological-warfare-bot

**Comment by o-jasper** [comment]
Chatter bots are cool but not really this project?

**Comment by zetok** [comment]
@irungentoo this can be closed.
