### ISSUE TITLE
Background colors / images of chat area

### ISSUE THREAD

**Issue by Redee** [irungentoo/toxcore#1409]
Only white very bad for eyes.
Add background colors / images to chat area.

**Comment by Jeeppler** [comment]
@Redee which Tox client do you use? What is the name of the program when you use Tox?

**Comment by markus1540** [comment]
definitely not a core issue...

**Comment by Redee** [comment]
qTox for Windows latest version >>
![2015-08-29_160522](https://cloud.githubusercontent.com/assets/2652667/9562008/d21a5fbc-4e67-11e5-931b-f17b7fc635bd.jpg)

**Comment by suhr** [comment]
Create an issue at https://github.com/tux3/qTox/issues.

**Comment by Jeeppler** [comment]
@Redee 

1. please  create an issue at https://github.com/tux3/qTox/issues  (like @suhr wrote). Furthermore describe your issue better the next time, using a screen shoot to visualize your problem is always a good idea.

2. please close this issue
