### ISSUE TITLE
Keep group chat and history

### ISSUE THREAD

**Issue by Redee** [irungentoo/toxcore#1410]
Keep group chats after closing and auto-save history from them.

**Comment by Jeeppler** [comment]
@Redee Is this a functionality of the underlying toxcore library or is this an issue of the graphical interface (in your case qTox)?

To make this clear toxcore is just the underlying library which offers some functions for the client developers. There are many clients like uTox, qTox etc. build on top of toxcore. What you normally see on your desktop is one of the clients and *not* toxcore.

**Comment by suhr** [comment]
> Keep group chats

This is the new groupchats feature. They're still in development.

> and auto-save history from them

This is not a core feature.

**Comment by Redee** [comment]
@suhr thx for answer.

**Comment by GrayHatter** [comment]
@irungentoo close as replaced by new groupchats
