### ISSUE TITLE
fedora repo?

### ISSUE THREAD

**Issue by jontis** [irungentoo/toxcore#1412]

**Comment by Jeeppler** [comment]
:+1:  would be nice to have

**Comment by suhr** [comment]
Not a core issue.

Btw we still need a repo for packaging issues. There's https://github.com/suhr/Packaging but it's not official.

@irungentoo @nurupo @Zer0-One, please react somehow.

**Comment by Jeeppler** [comment]
In my opinion the distribution of an application like qTox should have a high priority per default. 
You should have packages for the following distributions in order:

1. Debian
2. Ubuntu
3. Fedora
4. Archlinux (has already AUR packages)
5. CentOS

and Windows should have a high priority too.

and maybe (FreeBSD)

To give you an conversation example, on how important this is:
Alice - software engineer and collaborator on qTox using Linux
Bob - uses Fedora
Carol - windows user
  
Alice: Oh, Tox and qTox are really a Skype replacement and it is decentralized.
Bob: Oh, what is the package name?
Carol: If there is an Windows installer, I will give it a try!
Alice: Yeah, qTox is so nice, but you have to compile it first.
Bob: Oh, no. The last time I compiled something it did not work at all.
Carol: What is compiling?

Such a conversation really suck. I mean Carol and Bob will still use Skype and Alice has no partner to communicate over Tox (qTox, uTox or other clients) with.

**Comment by zetok** [comment]
@Jeeppler I think that your example is a bit invalid here, since there are static binaries that they could use.

**Comment by victorheld** [comment]
@Jeeppler Aren't there the binaries over at the [tox.chat wiki](https://wiki.tox.chat/binaries) they could use?

**Comment by Jeeppler** [comment]
@zetok binaries are maybe step one, but hopefully one of the next fedora releases has the Tox library, qTox, uTox and Toxic in there repositories and hopefully soon community packages for Archlinux.

@zetok and @victorheld it is nice you have binaries again. The last time I looked they have not been that many binaries, so nice work :+1:

**Comment by Zer0-One** [comment]
We're basically done with the Debian repository. See https://wiki.tox.chat/binaries#debian, as well as https://wiki.tox.chat/developers/jenkins/packaging. Packages pushed from the build server are added to the repository every night at midnight.

Next on the list are Fedora and CentOS, but it's going to take time. I need you guys to be really patient.

As far as reporting issues related to build infrastructure, I put up a new mailing list: infrastructure@lists.tox.chat. If you need to report issues, just shoot a message to the list.

**Comment by Jeeppler** [comment]
@Zer0-One nice :+1:  keeping going :-)

**Comment by linux-modder** [comment]
@jontis , if you have not  compiled / used the new static binaries since the  old  repo died you are  seriously  behind for 1 

secondly, As a Fedora user myself your assumption that  users can't / won't compile is  utter bullshit.  #fedora-social  and  other irc channels (well documented  how to use for the un-aware) are  packed with helpers not to mention #tox* 

@Zer0-One, @zetok  for the repo testing or build testing feel free to  hit me up as usual for questions / checks

**Comment by jontis** [comment]
Not sure what happened here but I'll try to address the better comments.

@suhr understood, thank you.

@Zer0-One great, thank you. Just wanted the an answer to the question, even if I now understand I asked it in the wrong place. Thank you for answering.

About the rest: I really like this project and want to see it gain traction quickly. Having a repo helps. Sure, many of us can compile ourselves, but if we run many beta softwares and need to compile new versions every week, we just do that for a select few. Same with binaries, we don't check for new and reinstall every week. The strength of the repo is that the new software smoothly gets delivered.

**Comment by nurupo** [comment]
>The strength of the repo is that the new software smoothly gets delivered.

There is also a weak point that you have to trust our binaries to be secure. If we had reproducible builds, like what Tor and Debian do, then you would be more basis for trusting. So if any of you want to help us by setting up reproducible builds, you are very welcome.

**Comment by linux-modder** [comment]
Should have  both 32 and 64  builder / tester boxes  ready by  next week if
someone wants to spin me  up on the  needed steps.... (Fedora  and  any
additional linux  distros I can  fit on them (space wise limited to ~ 400Gb
atm)

**Comment by nurupo** [comment]
@linux-modder 
It's not an issue of not having build boxes. We have our own build boxes. It's more like we want someone to figure out how to do reproducible builds of toxcore, qTox (and by extension all of its dependencies: Qt, ffmpeg, etc.), uTox and others, and tell how to set it up : )

**Comment by jontis** [comment]
Fedora has started using this:
https://copr.fedoraproject.org/

It might be helpful for you.

**Comment by linux-modder** [comment]
Due to  ffmpeg   it  is  not  qualified :(

Corey W Sheldon
Fedora Ambassador, North America

**Comment by aaannndddyyy** [comment]
I don't know about fedora, but for Debian/Ubuntu/... KYTV does some good packaging and handles all dependencies properly. 
He is not member of the tox team, but a Tails and I2P dev. So it is not official, but you can use his packaging scripts (it's all transparent and free open source, of course), build for yourself and host the resulting files for yourself, and don't have to worry about Debian, Ubuntu and derivatives anymore.
Here you can find the launchpad repo, containing the source packages, binaries for ubuntu and the packaging scripts: https://launchpad.net/~i2p.packages/+archive/ubuntu/i2p
Tested on Debian, Ubuntu, Mint, Trisquel.

**Comment by nurupo** [comment]
@jontis that sounds like a regular build system with a package repository.We already have them.

I said explicitly that what we would like help with is reproducible builds, similar to what Tor, Bitcoin and Debian do. Google "reproducible builds", since you all seem to miss the point thinking that we either don't have build servers or package repository or both.

Also read [Reflections on Trusting Trust by Ken Thompson](https://www.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf) and [Countering Trusting Trust through Diverse Double-Compiling by DavidWheeler](http://www.acsa-admin.org/2005/papers/47.pdf) to understand what it's all about.

**Comment by jontis** [comment]
You are absolutely right that I might be missing the point. This is not my area of expertise, I'm just a low level user.

What I tried to convey is that it is really good to be included in a distributions most standard repositories to accumulate users and gain traction for the project, and, lets face it, if you don't gain traction and users, most of your project will be dead and the time you put into it was wasted.
The normal repositories for Fedora is, if you include non-koscher software, as ffmpeg is if I understood @linux-modder corectly, is http://rpmfusion.org/ and that's where you want to be to reach a large audience. Secondary, a personal repository would be better than nothing, but it's not remotely as good as being in the standard repos. If all goes down the drain, publishing source files and telling users to compile or build themselves might get you some developer class users. 

I'm taking the time to write this because I really want this to reach mainstream so I can reach many of my normal connections with Tox. I hope this is your goal as well.

**Comment by linux-modder** [comment]
@jontis,

The creation of a repo that would be in the  `official`  repos as it
appears you are leading to is not possible in part due to ffmpeg and
 Fedora Licensing Policies.

@nurupto,
you should be able to build / run createrepo on Fedora docker images or
OpenQA stacks to create valid repos for fedora however.



linux-modder
Fedora Ambassador, North America

**Comment by jontis** [comment]
@linux-modder , yes? Therefore http://rpmfusion.org/ ?

**Comment by nurupo** [comment]
@jontis What's currently being worked on is a Tox package repository with static binaries of clients and later toxcore, and [as you can see](https://pkg.tox.chat/), the current plan is to provide packages for CentOS, Debian, Fedora and Gentoo.

**Comment by linux-modder** [comment]
NOT rpmfusion it would be its own repo...

linux-modder
Fedora Ambassador

**Comment by suhr** [comment]
> As far as reporting issues related to build infrastructure, I put up a new mailing list: infrastructure@lists.tox.chat.

@Zer0-One Unfortunately, mailing lists are opposite to user friendly and ain't suitable as a bug tracker at all.

**Comment by tblah** [comment]
I understand that you have no reason to trust me but if anyone is interested I run a nightly repo for Fedora 22 x64 on copr. Currently it is only toxcore and toxic but I should get some more clients added this week.

http://copr.fedoraproject.org/coprs/tblah/tox-nightly/

**Comment by storrgie** [comment]
@tblah It's awesome you're doing those, I think there is moves to make the jenkins server build RPMs for the tox clients, someone might want to peek at your spec files.

I think for clients like qTox that have ffmpeg dependency that you'd actually be in violation of copr policies for building/hosting. So it will be essential for the Tox project to build their own packages and host their own trusted/signed repository.

**Comment by tblah** [comment]
Good point about ffmpeg. Where should I send my spec files?

**Comment by Zer0-One** [comment]
@tblah mind posting what you have to the dev mailing list?

**Comment by zetok** [comment]
@tblah you may be interested in adding that to https://wiki.tox.chat/community_builds

**Comment by GrayHatter** [comment]
stale
