### ISSUE TITLE
'Disk full' causes loss of all chat history

### ISSUE THREAD

**Issue by yurivict** [irungentoo/toxcore#1415]
I am using qTox, had disk full condition and rebooted. After this chat history is blank.

If, for example, data was in SqLite DB, this wouldn't have happened. I believe clients just rewrite the whole DB every time, and this makes it error prone.

**Comment by suhr** [comment]
Chat history is not a toxcore issue. And yes, qTox uses sqlite.
Please report the bug at https://github.com/tux3/qTox/issues.
