### ISSUE TITLE
Provide git tags for toxcore version

### ISSUE THREAD

**Issue by blobgo** [irungentoo/toxcore#1416]
In https://github.com/irungentoo/toxcore/issues/1395 I found out that toxcore now has versions.
So please provide git tags for these release (versions)...

**Comment by GrayHatter** [comment]
ageed, but toxcore doesn't have verisons yet... Everyone tell @irungentoo to start semver now

**Comment by rugk** [comment]
Wouldn't it be a better idea to leave this issue open until @irungentoo starts semversioning?
