### ISSUE TITLE
Hacking port 33445

### ISSUE THREAD

**Issue by neilnelson** [irungentoo/toxcore#1422]
For example, upon turning my computer on this morning and before starting uTox I was getting a steady stream of udp packets, several a second, to Tox port 33445 from two IPs I do not have contacts on. Since Tox is P2P perhaps there is a valid reason for the traffic but at the moment I am blocking this traffic. Let me know otherwise.

**Comment by LapFox** [comment]
This is known as the DHT. These are the nodes which connect you to the network so you can receive friend requests from people

**Comment by neilnelson** [comment]
I will let the traffic through. Another curious aspect is that it looks like Tox traffic is running consistently around 30k bytes/second, with a wide range, and sometimes peaks around 100k bytes/second which seems a little high.

**Comment by LittleVulpix** [comment]
@neilnelson This is also normal (sort of) because since there is no centralization, the nodes must actively partake in (re)distributing the traffic. To decrease the data usage, you can enable tcp-only mode - but this slows down file transfers as you then rely on other nodes in the tox network to relay all of your traffic even though you could for example make a direct connection with the person you're trying to talk with.

**Comment by neilnelson** [comment]
Perhaps there is a page giving detail on what the Tox traffic is. You mentioned that nodes could relay traffic which on initial thought seems unnecessary since it would be easier, immediate, and a common design to just communicate between the two IPs in the communication. I was thinking that the Tox traffic, other than my own initiated Tox traffic, was merely address related information in the manner of a look-up to assist others in connecting, this might be called meta-data. The transfer of encrypted content, the messages and data from one person to another, through my computer and network, relaying, would be a problem in that even though the content is encrypted beyond my ability to decrypt, I could be held responsible in the manner of an accessory to that traffic. I am providing a means of the traffic. Relaying would seem to make sense for anonymization, which brings up the just noted problem, or for broadcasting to many IPs beyond a person's immediate bandwidth. I think we would need consent of the computer owner to use their computer for broadcasting.

**Comment by GrayHatter** [comment]
@neilnelson the only traffic you'll ever relay for other users is DHT traffic. That is traffic only used to help locate contacts.

**Comment by LittleVulpix** [comment]
I believe that if you use tcp-only mode, you are having other nodes not only relay DHT traffic but also your encrypted traffic, for example if you send a file to someone whilst in a tcp-only mode, your traffic will appear to the target to be coming from one of the nodes along the way (I am actually not sure myself how these are chosen, perhaps it's only the bootstrap nodes or nodes that are running in a daemon mode, i.e. not "regualar" tox network users?)

**Comment by vikstrous** [comment]
I thought the onion routing is used only for friend discovery, is it not?

**Comment by GrayHatter** [comment]
stale

**Comment by hardhub** [comment]
Is it possible to limit such traffic?
Specify some rate or similar things.
I think it is too much packets per second for chat.

P.S. I am using qTox

**Comment by hardhub** [comment]
Approximately it sends/receives 600 packets per minute per one instance.
Maybe it is possible to install own server and communicate with the world through that server and each node will have the same DHT traffic obtained from such server?

**Comment by hardhub** [comment]
@GrayHatter 

Maybe it is time to reopen issue and rename to something related to traffic limits?
I think for now my meta traffic is much greater than my payload.
And such big traffic will be a problem for mobile devices.

**Comment by GrayHatter** [comment]
I'm not likely to reopen this issue.

But if you'd like to open an issue for the sheer number of packets toxcore sends. That should be fine.... but I'm pretty sure one already exists for that.

**Comment by hardhub** [comment]
OK

I found it... It can be this one: https://github.com/irungentoo/toxcore/issues/1581
