### ISSUE TITLE
GitHub Wiki Pages

### ISSUE THREAD

**Issue by TheElf** [irungentoo/toxcore#1429]
Links on the wiki homepage are broken, They still point to the old domain wiki.tox.im rather than wiki.tox.chat

easy fix. just wasn't able to edit it myself

**Comment by x368** [comment]
on which page and which links?? please be more specific

**Comment by JacobHenner** [comment]
@x368 Most of the pages claim that the page from the github wiki has been moved to the tox.im wiki. The corresponding pages do not exist on the tox.chat wiki, so it's not a quick find-and-replace to fix it. 

Afaik, @irungentoo, the documentation is being organized at https://github.com/Tox-Docs/Text 
Does this mean the docs on the GitHub wiki are deprecated, and if so, are the links to the old wiki going to be replaced with links to pages on the new wiki, or is the github wiki and tox.chat wiki going to be removed altogether in favor of docs in a separate repo, or in docs/ on the master repo?

**Comment by GrayHatter** [comment]
@irungentoo turn off the wiki for toxcore please and thankyou!
