### ISSUE TITLE
Display names in client controlled by remote user

### ISSUE THREAD

**Issue by TheElf** [irungentoo/toxcore#1430]
A small security concern here,

While users will always have a unique Tox Id, it is worth noting that as it stands now, a user's name is controlled by the user themselves.

This means that a user may change their name unexpectedly causing confusion. The only current defense for this is to only add friends that you trust not to do this, but I think a more elegant way to deal with this is to allow users to add nicknames to contacts that are controlled by them. This removes the possibility of impersonation.

If our goal is an accessible and secure option, I think that users should by default freeze display names and maybe prompt them to allow renaming when a user wants to change the name.

**Comment by ameenross** [comment]
Probaby a duplicate of #756

**Comment by TheElf** [comment]
yea, you're totally right. thanks for using the search feature better than I did. 

Closing as duplicate.
