### ISSUE TITLE
consider applying for stripe's open source retreat

### ISSUE THREAD

**Issue by vikstrous** [irungentoo/toxcore#1433]
https://stripe.com/blog/open-source-retreat-2016

**Comment by Jeeppler** [comment]
@irungentoo could apply there to work three more months on the project!

**Comment by ProMcTagonist** [comment]
Sounds very helpful. Why not go for it?

**Comment by LittleVulpix** [comment]
I don't know. @irungentoo is a very private person and I don't even think anyone knows his real name/etc (maybe a very select few in the inner circle do), and I'm pretty sure his name or location has never been revealed to the public. I don't think he'd care much to actually go somewhere.
