### ISSUE TITLE
a possibly unsettled part of the core design?

### ISSUE THREAD

**Issue by x368** [irungentoo/toxcore#1435]
After use of the interfaces of the clients, reading discussions on github and reading some of the core code I am convinced that certain protocol features were adopted from environments like irc and skype without due consideration, despite the quite different premises of secure communication compared to the previous IM/VOIP art.

(The usability and security properties of a "nickname" are exactly the same as the ones of a "status message". Why does the protocol support them both, "a bit differently", doubling the number of the structures and  codepaths? Why not distinguish them, if necessary, by just a single bit or by several bits "remote info of kind #N"?)

The client developers treat now "nicknames" like if they were "real names" backed by a trusted authority (to name the contacts in the list). They are __not__.

Tox is expected to have a robust bookeeping of the identities. Nevertheless clients tend to _only_ show the volatile _pseudonymous_ "nickname" information for attribution of messages in chat. __Why__?

I am creating this issue in toxcore because it looks like it is the core which is at the core of misunderstandings (no pun intended).

The users of the API easily misinterpret the assumptions and the intentions of the library and of the protocol.

It is hard to change the API but the longer errors are kept the more harm results. It is also harder to change later than earlier.

As a very minimal change I would suggest make naming of the API functions and data to correspond to the semantics:

    "friend" -> "contact".
    "name", "status message" -> "published pseudonym", "published activity"

**Comment by GrayHatter** [comment]
stale, dup of #1434  and I'm not convinced by this argument
