### ISSUE TITLE
Separate documentation from master repository

### ISSUE THREAD

**Issue by JacobHenner** [irungentoo/toxcore#1437]
Since both a wiki and a separate documentation repository exists, would it be possible to move the still-relevant files from /docs/ elsewhere, and delete the rest? This will remove some clutter in the repo, and make updating files easier.

**Comment by TheElf** [comment]
+1

**Comment by aviau** [comment]
> This will remove some clutter in the repo, and make updating files easier.

How so? Why not just fix the docs?

The further the doc is from the code, the worse its going to be.

Whenever tox is kinda-stable. Every commit to toxcore should also modify the documentation accordingly. This is easier when the doc is in the same repo.

**Comment by JacobHenner** [comment]
Doc fixes won't require pull requests. Putting it on the wiki would allow all contributors to edit it quickly, without additional the commits. I think it'd also be easier to keep the docs up to date this way.

**Comment by irungentoo** [comment]
it's going to be removed (probably replaced with the new docs) when the new docs are done.

**Comment by cebe** [comment]
> Whenever tox is kinda-stable. Every commit to toxcore should also modify the documentation accordingly. This is easier when the doc is in the same repo.

:+1: code changes should come with doc changes in one PR. Editing docs on github is as easy as editing a wiki so there is no reason to keep the docs out of the repo.

**Comment by aaannndddyyy** [comment]
@aviau +1

**Comment by JacobHenner** [comment]
I suppose it's /as easy/, but I feel like the necessity to make the changes, commit them, and have them accepted in a PR is a practical deterrent from updating the docs, especially for small changes.

**Comment by GrayHatter** [comment]
https://github.com/Tox-Docs/Text

**Comment by cebe** [comment]
@GrayHatter any comments on the arguments for having the docs in the same repo?

**Comment by GrayHatter** [comment]
IIRC once all of the documentation is complete, the text or markdown version will be merged in. But until then, any and all of the progress will be in a separate repo.

**Comment by cebe** [comment]
k, fine with me.
