### ISSUE TITLE
Security: Tox bypasses Proxy if not available

### ISSUE THREAD

**Issue by ovalseven8** [irungentoo/toxcore#1441]
Hello,

because it is probably a core issue, I wanted to create a note here in the repo.
https://github.com/tux3/qTox/issues/2287

Especially for Tor users a potential security problem.

**Comment by irungentoo** [comment]
Toxcore only uses the proxy for TCP and not UDP. If you want to use the proxy for anonimization purposes (and not for connecting better purposes) you need to disable UDP. Your client should have a 'force proxy' option that does this.

That's what I think the issue is in this case.

**Comment by GrayHatter** [comment]
stale
