### ISSUE TITLE
What happened to GSOC Student "DrakeFish" and why is his Github account deleted?

### ISSUE THREAD

**Issue by fishdrake** [irungentoo/toxcore#1442]
We need transparency of the Tox Foundation on this issue.
https://github.com/drakefish

**Comment by ameenross** [comment]
Unsubscribing.

**Comment by Impyy** [comment]
We know just as much as you do, he disappeared. 
We didn't hear from him after he stopped working half way through GSoC. Some time after that, his account was deleted.

Please close this.

**Comment by dcharles525** [comment]
gr8 b8 m8 i'll r8 8.88888888/8 l8r

**Comment by ProMcTagonist** [comment]
![5b6d66e8edaf3554c28409dc0e79cb4f7b0900f6eb5bbb2a32a45a89754082f3](https://cloud.githubusercontent.com/assets/4358079/10196856/d3ba88b0-6749-11e5-91c2-c02266eed27a.png)

**Comment by stal888** [comment]
![1437773925340](https://cloud.githubusercontent.com/assets/774591/10211846/8154e12a-67ac-11e5-8f11-fe4a13ede7a2.jpg)

**Comment by subliun** [comment]
Deep down, we have a little irungentoo in all of us. Some people have more than others. DrakeFish had 100%

rip

**Comment by LittleVulpix** [comment]
@subliun What... does that mean I should actually have a little bit of epic programmer inside me? Why has no-one told me before.. rip.

**Comment by GrayHatter** [comment]
@irungentoo close and lock. 

@* any issues/questions that don't involve toxcore code should go to irc://irc.freenode.org/tox
