### ISSUE TITLE
Remove unused text files from repo

### ISSUE THREAD

**Issue by JacobHenner** [irungentoo/toxcore#1446]
i.e. AUTHORS, ChangeLog, unless there are plans on using them in the near future.

**Comment by GrayHatter** [comment]
IIRC they're required by something for distribution... or something...

**Comment by JacobHenner** [comment]
@GrayHatter I figured it might be something like that, so I wrote an issue report instead of submitting a PR. If they're truly required, can they be at least be filled with something?

**Comment by GrayHatter** [comment]
that's not a bad idea, find out why they need to exist then fill them with
that reason.

**Comment by GrayHatter** [comment]
fixed by #1449
