### ISSUE TITLE
Can't login with different username/ID

### ISSUE THREAD

**Issue by idenkov** [irungentoo/toxcore#1447]
Installed qTox on two different Ubuntu machines, with two different users registered.

I can't see an option to type new username on the login screen - it is dropdown field with the users registered on each machine, if I want to login with user registered on different machine can't see how to do this.

**Comment by ProMcTagonist** [comment]
There is no login. "Accounts" are local datafiles. Tox is completely P2P. Multiple device support is being worked on, though, so don't worry :)

If you want to use the same account on multiple devices right now, you can manually copy your .tox file over to ~/.config/tox/, but running two instances with the same profile simultaneously is not supported. In the future there'll be a protocol for syncing messages and friends between multiple profiles transparently.

For future reference, the qTox repo is over at https://github.com/tux3/qtox. You can check it out every so often to see how things are going.

**Comment by idenkov** [comment]
Thanks a lot for the detailed info. Sorry if that was already stated somewhere, but I didn't find solution/explanation.
