### ISSUE TITLE
Symbian port - help

### ISSUE THREAD

**Issue by rigzbe** [irungentoo/toxcore#1451]
Hi, I'm just typing here because I didn't find better place to ask. Will be Tox client released for Symbian^3 (belle)?

I know that Symbian is dead OS but it is still in usage. 

If anyone can write tox client for it I can be a alpha/beta tester. I do not know how to write programs.

**Comment by JacobHenner** [comment]
I'm unaware of any efforts towards developing a Symbian client. Since toxcore and the clients which implement it are separate, any interested developer can create a Symbian client without coordination from the toxcore devs.

**Comment by GrayHatter** [comment]
stale without an actual issue that can be addressed.
