### ISSUE TITLE
Question - Automatic gain (volume) control?

### ISSUE THREAD

**Issue by Gert-dev** [irungentoo/toxcore#1455]
Hello

I noticed that some voice clients, such as Mumble, perform automatic gain control that automatically normalizes the volume of clients. This applies to 1-to-1 voice chats but is probably most relevant for group chats, as it ensures that all participants have an equal volume and it makes fine tuning of microphone and volume settings a lot easier. Is such a feature perhaps already on the roadmap of Tox? Perhaps it is already implemented but there is some option I need to toggle in my client (or it needs to support it)?

I've been searching through the tickets (open and closed) for synonyms to volume, gain, loudness, etc. but couldn't find any tickets related to this, I apologize if this has been asked before.

Thanks in advance

**Comment by GrayHatter** [comment]
Toxcore is a protocol for transferring data, and should make it as easy as it can. Adjusting or altering the data is a nono!

Please resubmit this to your favorite client. Or to https://github.com/irungentoo/filter_audio

**Comment by Gert-dev** [comment]
Will do and wasn't sure where it belonged, thanks for your fast response.
