### ISSUE TITLE
[Request] In chat Picture/youtube link resolution

### ISSUE THREAD

**Issue by Vastrix** [irungentoo/toxcore#1457]
When a link, resolving into a picture or youtube video, Show the picture/(play the video, might be difficult? :s) in chat.

Kinda like the textual IRC client: ![Textual](https://www.codeux.com/textual/private/images/v500media/YosemiteLightFullscreen.png)

If you guys don't do requests (yet?) Than feel free to ignore this issue ;)

Cheers o/

**Comment by JacobHenner** [comment]
This would be a feature implemented by the clients, not the core library.

Cheers,
JH

**Comment by Vastrix** [comment]
Like a "plugin"? :o

**Comment by quininer** [comment]
https://github.com/tux3/qTox/issues/1903 ?

**Comment by Vastrix** [comment]
uhh yea.. "Onebox" ha, never heard of it..

So yea, I'll just go support that guy over there.. Sorry for wasting your time.
Keep up the good work! :D
