### ISSUE TITLE
Stuck on avatars importing 

### ISSUE THREAD

**Issue by StSav012** [irungentoo/toxcore#1458]
qToX (both qtox and qtox-unity) doesn't load. The last thing writes to the terminal is,
```[time_stamp] src/persistence/historykeeper.cpp:178 : Debug: "Try import avatar for: UID."```
Then doesn't respond anything.
Neither any of my contacts, nor me have avatars loaded.

I'm running Ubuntu 14.04 LTS 64 bit, qtox-unity has just been updated to 117-c07aee1, qtox has just been installed for checking.

*update:* After I put a picture for the avatar, I got another message:
```[time_stamp] src/persistence/historykeeper.cpp:184 : Debug: "Import avatar for: UID."```
For further actions, though.

**Comment by zetok** [comment]
Thanks for the report, though this is a toxcore repo, and this issue is a client bug.

I've opened an issue in qTox repo, so that you can close this one, and any additional info should be put in issue in qTox repo `:)`
