### ISSUE TITLE
Fuse Filesystem over Tox

### ISSUE THREAD

**Issue by merlink01** [irungentoo/toxcore#1459]
Only an Idea:
It would be great to have the possibility to use Tox on a PC as Filesystem Server.
After allowing the access of a path for a friend he has the possibility to mount the Filesystem with fuse (Linux/Mac) or dokan(Windows).

So the file-exchange between friends and groups could be much more intuitive.

If this is to complicated to implement there could be workarounds like tunnel ftp or sftp (ssh) through Tox.

**Comment by GrayHatter** [comment]
Take a look at https://github.com/cleverca22/toxvpn
