### ISSUE TITLE
realloc() usage is leaving copies of keys everywhere in ram

### ISSUE THREAD

**Issue by cleverca22** [irungentoo/toxcore#1463]
https://github.com/irungentoo/toxcore/blob/master/toxcore/net_crypto.c#L1360

if the realloc cant grow the region, it will allocate a second area of the requested size, copy everything over, free the old one,and return the new location back

that will cause a copy of all shared_keys's to be left behind, and there is no safe way to clear them because malloc() may return the old ram to another thread

the only solution i can see, is to allocate each Crypto_Connection seperately, and store an array of pointers to them

the keys would also be protected more if that was done with sodium_malloc and sodium_free on the Crypto_Connection instances

**Comment by TheNain38** [comment]
Using [sodium_malloc](http://doc.libsodium.org/helpers/memory_management.html#guarded-heap-allocations) and [sodium_free](http://doc.libsodium.org/helpers/memory_management.html#guarded-heap-allocations) is a must

**Comment by TheNain38** [comment]
Correct line: https://github.com/irungentoo/toxcore/blob/0d0b74f5a8662a0b3b7c4da3537d1e8942f20656/toxcore/net_crypto.c#L1360 because the new commits moved the line he was speaking of.

**Comment by GrayHatter** [comment]
I believe this was fixed in #1506
