### ISSUE TITLE
BWControler is misspelled

### ISSUE THREAD

**Issue by helium-software** [irungentoo/toxcore#1464]
The name of the bandwidth controller structure and the corresponding filenames should contain a double "l".

Easy way to fix (not worth a fork and pull request):
```bash
sed -i 's/\(contro\)\(l\)\(er\)/\1\2\2\3/gi' $(find toxav/ -type f)
mv toxav/bwcontroler.c toxav/bwcontroller.c
mv toxav/bwcontroler.h toxav/bwcontroller.h
```

Thank you,
helium-software

**Comment by GrayHatter** [comment]
There's no way that writing and testing that `sed` command is faster than creating and committing a PR.

**Comment by TheNain38** [comment]
Can be closed
