### ISSUE TITLE
[swscaler @ ] Warning: data is not aligned! This can lead to a speedloss

### ISSUE THREAD

**Issue by igpg** [irungentoo/toxcore#1471]
I'm using 
community/toxcore 3645-1 / arch linux and 
aur/qtox-git r2712.2fed672-2 installed: r3871.db52ef6-1 (99)
    Powerful Tox client written in C++/Qt that follows the Tox design 
    guidelines.

today's build which compiled correctly, of course all the dependencies were installed but when an audio call is established an extremely I mean *extremely* metalic voice is "heard" meaning you can't understand a thing from it.

The error looks like a problem in sync as I found similar issues with ffmpeg however the result is not working.

**Comment by mannol** [comment]
This seems like a problem with [qTox](https://github.com/tux3/qTox) so it's best to report it there.

**Comment by igpg** [comment]
thanks opened there
