### ISSUE TITLE
restore video recv

### ISSUE THREAD

**Issue by Rotkaermota** [irungentoo/toxcore#1472]
0. Alice recive video frames.
1. Alice calls toxav_call_control with TOXAV_CALL_CONTROL_HIDE_VIDEO
2. ok. no video received. Alice does not recv video frames.
3. Alice calls toxav_call_control with TOXAV_CALL_CONTROL_SHOW_VIDEO
4. <b>fail: still no video received by Alice</b>
5. Bob should set video bitrate to 0 then restore normal video bitrate to restore video transmission

**Comment by GrayHatter** [comment]
@Rotkaermota any error? Can I see the source code?

**Comment by Rotkaermota** [comment]
Issue alredy fixed:
https://github.com/irungentoo/toxcore/commit/4df59de5049a44ce4d0145526978aa94c10047c8
