### ISSUE TITLE
/etc/init.d/tox-bootstrapd doesn't work on OpenSuSE 13.1

### ISSUE THREAD

**Issue by Chewie9999** [irungentoo/toxcore#1473]
The daemon control program in /etc/init.d called tox-bootstrapd errors when trying to run it on OpenSuSE 13.1

The first error is on line 29 of the current source:
. /lib/init/vars.sh
This file doesn't exist anywhere on the filesystem.

Secondly, on line 90:
status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $? 

fails, I think because the "status_of_proc" function doesn't exist in /lib/lsb/init-functions (loaded on line 43).

I can provide this file and others if required to help with the diagnosis.

Thanks,

**Comment by optimumtact** [comment]
I don't know if it was ever written for anything other than debian/ubuntu systems

**Comment by GrayHatter** [comment]
stale
