### ISSUE TITLE
Extend tox URIs for joining calls

### ISSUE THREAD

**Issue by esainane** [irungentoo/toxcore#1475]
In tox, I would like to be able to send and receive URIs allowing recipients to join an active call.

Other actions for the URI scheme were discussed in #592.

From STS at https://github.com/Tox-Archive/Tox-STS/blob/master/STS.md#tox-uri-scheme , this appears to be limited to adding new user IDs.

In TCS, the only mention of URIs I could find were in https://github.com/Tox/Tox-Client-Standard/blob/f42c87bb03e17d645d18fcd18cc0540c1a4f49b2/user_identification/tox_id.md , describing QR codes for tox URIs.

**Comment by ProMcTagonist** [comment]
+1, deeplinks are handy

**Comment by Spencer-H** [comment]
This would be incredibly useful, and a feature that either Skype doesn't have, or doesn't use. I don't recall if their URI allows for more than 1 on 1 calls. But the ability to send a URI or a QR code to invite people to a call would be amazing.

**Comment by Renha** [comment]
why there are "under_discussion" tag, while there are no actual discussion?

**Comment by GrayHatter** [comment]
because I don't see a convincing argument that this is even a toxcore issue. It would be up to clients to implement this.

**Comment by quininer** [comment]
Maybe you should move to https://github.com/Tox/Tox-Client-Standard

**Comment by Renha** [comment]
@GrayHatter thank you for explaination. i think tag probably should be added after comment like yours or @quininer s, not before

**Comment by GrayHatter** [comment]
client issue
