### ISSUE TITLE
Crash on call

### ISSUE THREAD

**Issue by PowaBanga** [irungentoo/toxcore#1488]
Hi, every time when I try to call or I receive a call sounds or video, qtox crash...

I can send the terminal log here if somebody retest that with me ...

this is my id tox BD358EB75DF529DB4C20A6DE8F4D48920F70409E1495D66FC137B99ED6BA3861B4D96A1DAF2F

or you can join me on my jabber : powabanga@ jappix.com

or here sure :p

ubuntu-gnome 15.10 AMD64

**Comment by GrayHatter** [comment]
you're looking for https://github.com/tux3/qTox/issues
