### ISSUE TITLE
Website is in mixed russian/english

### ISSUE THREAD

**Issue by varnav** [irungentoo/toxcore#1489]
Hello! https://tox.chat/ website is a mix of russian and english text in my browser.
How I can help with translation?

**Comment by Spagy** [comment]
This is the repo for the current website https://github.com/Tox/Tox-Website, translation seems to have stalled. As far as I can tell the project has moved away from Transiex without having another solution ready as a replacement (I may be wrong about that).

This is the repo for the new website (in beta) https://github.com/tox/tox.chat, looks like it's using a homemade Nodejs translation system.

**Comment by GrayHatter** [comment]
@zer0-one

**Comment by GrayHatter** [comment]
@optimumtact too
