### ISSUE TITLE
debian jessie repo dependency error in qtox

### ISSUE THREAD

**Issue by mova** [irungentoo/toxcore#1494]
using `deb https://pkg.tox.chat/debian nightly jessie`  when installing qtox gives:
``qtox : [Depends on]: libvpx1 (>= 1.0.0) [but is no installable].
        [Depends on]: qtbase-abi-5-3-2 which is a virtual package and is not provided by any available package.``
using `deb https://pkg.tox.chat/debian nightly release` fixes that.

**Comment by GrayHatter** [comment]
you're looking for https://github.com/tux3/qTox
