### ISSUE TITLE
Don't enforce censorship

### ISSUE THREAD

**Issue by olivia88** [irungentoo/toxcore#1496]
How convenient.
10 seconds after JX7P posted on https://github.com/irungentoo/toxcore/issues/1495 the thread was locked, so I couldn't reply.
Now he got the "final word".

If you give me some time, I'll continue answering his arguments here.
Also, we didn't even give @subliun time to defend his point of view (which Tox developers disrespected on last thread).
Finally, we must hear @irungentoo explanation for this unresolved mess.

**Comment by olivia88** [comment]
If you give me some time, I'll continue answering his arguments here.
Also, we didn't even give @subliun time to defend his point of view (which Tox developers disrespected on last thread).
Finally, we must hear @irungentoo explanation for this unresolved mess.

**Comment by suhr** [comment]
Of course, this time there's no Tox-Discussions repo again. Brilliant!

I reserve https://github.com/suhr/Tox-Discussions for this purposes. Make thread there if this one gets locked again.

**Comment by olivia88** [comment]
@suhr that repo you mentioned has 2 followers, this one has thousands. Putting this issue on a ghost repo where nobody sees it is a bad attempt of hiding it.
Please don't do this. Tox is still about freedom of speech, right? Right?

**Comment by suhr** [comment]
@olivia88 You can cast anyone you want. I've just created a place.

Decision of course is yours.

**Comment by olivia88** [comment]
I'll quote my friend @nachfuellbar on this one.

> I'm just a user but even if this concerns should be invalid, i think this repo is the only place more people can follow this
> It's sad even the second developer of antox retired from this project and nobody seem to care

Don't you agree with this, @suhr ? I don't want to make anyone mad, but this is just the best action from what I can see. Opinions?

**Comment by CRImier** [comment]
@olivia88 
Many of your points do not seem valid. You seem like a person for whom is fine to make up points even if the issue is real, which for me (as a bystander, though) it seems. However, you're not getting any support from me personally and I'd advise everybody to do the same until you have something more than a pile of innacuracies backed up by a couple of valid points. Make your point clear, dammit.
Also, it's not about freedom of speech if people choose not to listen.

**Comment by GrayHatter** [comment]
We don't enforce anything, just handling trolls
