### ISSUE TITLE
Audio notifications customizeable

### ISSUE THREAD

**Issue by dpalic** [irungentoo/toxcore#1503]
hello tox team,
you did a great piece of work with TOX! Appreciate it

Can you help me on how to setup better to hear audio notifications if a message is arriving?
Also if possible how can I add some better visible notify on the persons in the chat window?

Are there already options for this?

**Comment by Renha** [comment]
Hi! What exactly Tox client (yeah, there are number of them) are you using?

**Comment by dpalic** [comment]
we have the same issue under linux and windows. For windows I can share you on monday the version, for linux: v1.2-244-gaef447d. 
And windows was installed today from tox.chat (so latest)

**Comment by ProMcTagonist** [comment]
send a screenshot of each client please

**Comment by GrayHatter** [comment]
tox.chat actually has a few outdataed builts, so might not be the newest. Either way, this is an issue for your client, not for core.

Feel free to ask for help finding the right client.
