### ISSUE TITLE
Message timestamps should indicate initial message send time rather than the time it was recieved

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1509]
For instance, last night I said goodnight to someone on Tox, however they had already gone offline by the time I sent the message, I then went to bed and quit Tox, then the next day (today) when I logged onto Tox the other person was already online, and Tox sent them the message which it had not been able to send them yesterday as they had gone offline before I tried to send it.
Though there was one slight confusing thing, the message timestamp on both ends seems to show the successful delivery time rather than the first send time, so then the goodnight that I sent yesterday, looks like I sent it when I first signed in today which is very confusing...

So rather than this I think when I first send the message regardless of whether they are online or not, it should also send the first send time with the message so that when it is finally received it indicates the correct time when the message was intended to be sent.

I am running Ubuntu GNOME 15.10 with GNOME 3.18.

I first filed the report [here](https://github.com/tux3/qTox/issues/2863) but I was then directed here.

**Comment by SeventhSonOfASeventhSon** [comment]
Sorry, copied and pasted wrong title in initially!

**Comment by GrayHatter** [comment]
What's to stop a client from forging the timestamp?

**Comment by SeventhSonOfASeventhSon** [comment]
@GrayHatter, There are many things that probably could be forged and done in the clients, that doesn't mean we stop having new features that someone could do something not intended with. But I don't think that the forging of timestamps is such a big worry, I mean, so what if it does? A user could choose to sort messages via apparent sent timestamps but also by received timestamps (the current method).

But something definitely needs to change because if I say something the previous day relating to that day, it will only cause confusion if it looks like I sent it the next day!

The source code of clients could probably be altered a lot to do a lot of bad and unintended things, but I think that you could put some restrictions in place for this so it is not super easy to do, but editing the source code, like with anything, could probably do it.

**Comment by GrayHatter** [comment]
@SeventhSonOfASeventhSon we need reasonable offline messaging, that would solve this issue too.

**Comment by SeventhSonOfASeventhSon** [comment]
@GrayHatter That's another topic, but how exactly would that be implemented properly? Or 'reasonably'?

**Comment by Renha** [comment]
if we couldn't be sure about how old message is, we shouldn't show or use it.

**Comment by Renha** [comment]
@GrayHatter some kind of proxing over other peers?

**Comment by SeventhSonOfASeventhSon** [comment]
@Renha, Well we should at least provide the option optionally (and maybe it can be made so that it is on for some contacts but not others) to users like me who want it and trust their contacts, plus you can also show when it was received as well, but sort it by the other number. And I don't see such a large problem with this, you can make the user fully aware that the time may not be correct. You could also make it so that it won't trust it if it says that it is older than, or was sent during the time that both clients were online, then it could only be the time after that so it's not like they could just shove another message in wherever they like.

Maybe some users won't trust their contacts not to forge it and lie, but that doesn't mean that you shouldn't accommodate users who do trust their contacts and want a non-totally confusing ordering system.

**Comment by nurupo** [comment]
Messages you sent through tox have no timestamp information at all, it doesn't make sense to have them as to core supports only online messaging, i.e. when both parties are online, so the timestamp you see is added by clients when a message is received. The feature of queueing unsent messages and seding them when the receiver comes online is not a feature of toxcore -- toxcore doesn't support offline messages as of now, it supports only online messaging -- it's a feature of clients. Adding a fix of a client feature into toxocre is wrong. Client should either fix its feature or stop misusing toxcore for what it's not meant to be used (as it doesn't support offline messaging, yet).

**Comment by GrayHatter** [comment]
This isn't really a code issue. If you'd like to open a new one. It should be more focused around the idea "Toxcore should send timestamps". 

But I'd think you'd be hard pressed to get people to agree with JUST that idea. It really should be the client deciding and sending the time stamp. So you'd be better served with something closer to "Toxcore should allow clients to send extra arbitrary data with messages"

**Comment by SeventhSonOfASeventhSon** [comment]
Ok, I think I'll open a new issue then as you suggested @GrayHatter.

**Comment by SeventhSonOfASeventhSon** [comment]
Ok, I have created a new issue on that [here](https://github.com/irungentoo/toxcore/issues/1519) @GrayHatter.
