### ISSUE TITLE
Even if a long message exceeds the limitations for how long a single message can be if it is one message then when received should be shown as one message

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1510]
I have noticed that there is a character limit on messages, though it does not prevent you from actually typing in the box more than a certain amount of characters, when sent the message may become divided up into a few messages. And this is fine, but I think it might look nicer if even though it is sent as multiple messages, when received each message has a count with it to show where the message starts and where it ends, so for instance if I send a message which does not need to be split up into multiple messages then the counter for that message is set to `1`, then the next message I send as it is not a continuation of the previous one also is sent with `1` as the count, however lets say that that messages was split into two messages, so the next one is actually part of it, so the next one will have a counter of `2` (and the counter would go up as much as needed), then when we get a message which is no longer a continuation of that long message, the counter is reset for it back to `1` and then the receiving client knows which messages to display as one long message, and which ones are separate messages.

I original filed a report on this issue [here](https://github.com/tux3/qTox/issues/2865) however I was told that I should also report it here.

**Comment by Renha** [comment]
what receiver client should do, when she'll get messages with counters 1, 2, 4, 7?

**Comment by SeventhSonOfASeventhSon** [comment]
@Renha: Why would it do that? You mean if the other messages are not sent or received successfully? Well, if so then obviously it would try and [resend them](https://github.com/irungentoo/toxcore/issues/1486), but if it still doesn't work, or until it does, it would just shove them all together as one big message and draw a line like this one:

---

With probably some big text in the middle (you could make it colourful, look quite nice, and noticeable) which indicates to you that there were some parts of the message there but they haven't been received successfully yet.

**Comment by nurupo** [comment]
This is probably a 10th duplicate issue. Try doing a search to see this discussed already

**Comment by GrayHatter** [comment]
closed as dup per @nurupo
