### ISSUE TITLE
Allow cancelling requests for users to join group chats

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1513]
For instance, let's say I have a group chat with some people about something private, and then I accidentally add someone to the group chat who shouldn't see it, it would be really good if one could cancel the request for the person to join before they accept it.

I initially made the request [here](https://github.com/tux3/qTox/issues/2880) with another request as well, but was told that this would need to be implemented in toxcore.

**Comment by Impyy** [comment]
Perhaps this is something that could be implemented in the new groupchats. But I'm not sure how that would work.
@JFreegman ?

**Comment by GrayHatter** [comment]
the new groupchats already have kick and ban . I'm going to close this, because no one is going to work on old groupchats in the meantime.
