### ISSUE TITLE
Allow changing of NoSpam automatically

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1515]
Currently if a user is being spammed with friend requests or something similar then they change their NoSpam at the end of their ToxID, however I think (even though this feature would probably be off by default) that it would be good and some users would find it useful if one could automate this and set it to update the NoSpam every week or month or something, or perhaps the user would be able to specify how often it should change.

**Comment by Impyy** [comment]
Maybe clients should implement detection for friend request spams and display a message that says: "Tox has detected that you're being spammed with friend requests. Would you like to change your nospam to counter this attack?". 

Automatically changing the nospam is a bad idea, though. Let's say you give a friend your Tox ID, but before your friend has a chance to add you, toxcore changes your nospam. This means your friend is no longer able to add you. Granted, that's not very likely to happen if the interval is 1 month, but this could still cause a lot confusion.

**Comment by Impyy** [comment]
Actually, toxcore wouldn't have to be touched at all. This can be implemented client-side.

**Comment by nurupo** [comment]
This has nothing to do with toxcore, reopen this issue in a client bugtracker. Toxcore allows to change nospam whenever you want. The actual changing should be done by clients.

**Comment by SeventhSonOfASeventhSon** [comment]
Sorry, I actually accidentally opened it here, I meant to open it in qTox but somehow got confused with the tabs... Anyway, I have put this issue [here](https://github.com/tux3/qTox/issues/2881).
