### ISSUE TITLE
Allow users to publicly show certain profile information

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1516]
Though most will probably not want this, some may, especially if you are setting it up as more a company communication or something like that, and you want those with your ToxID to be able to view your profile picture and username as well as your status (though you would be able to choose which of these things would be private - well, your friends would be able to see them as well as yourself, but not anyone else - and which would be public) without having to send you a contact request, and instead just being able to search for your ToxID, and if you have allowed any of this information to be public and they have your ToxID then they would be able to find you, otherwise it would not return any results for privacy reasons.

**Comment by Impyy** [comment]
This is hard to do without exposing at least some private information, even if the user chooses to disable this 'feature'.

Maybe https://toxme.io/ is what you're looking for, though.

**Comment by GrayHatter** [comment]
yeah, that's not really the job of core. If anyone strongly disagrees, then I'll reopen this, but I don't see this as easy to do safe, and/or high demand feature.

**Comment by subliun** [comment]
This is a good idea.
