### ISSUE TITLE
How is the ToxID created?

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1517]
How exactly is it decided upon which ToxID a user should be given? And is it possible for two users to get the same ToxID if they are randomly generated or are there servers with them listed there or something?

**Comment by Impyy** [comment]
Tox ID's are randomly generated. There used to be a nice page that explained it all but I can't find it right now.

Please don't create issues for all of your questions by the way. Try to look things up on wiki.tox.chat or join us in #tox-dev on freenode if you have more questions.

Anyways, it consists of a 32 byte public key, 4 byte nospam and 2 byte checksum.

**Comment by SeventhSonOfASeventhSon** [comment]
@Impyy, So it's possible then for two or more users to get the same one even though it's very unlikely (though will become more likely the more people use Tox)? And what would happen then if two or more users managed to get the same one? Or maybe I have misunderstood something?

**Comment by SeventhSonOfASeventhSon** [comment]
Also, something which slightly concerns me is, is it possible for a user to edit the source code of their client in order to make it give them a specific ToxID? Could they then cause any trouble with that?

**Comment by Impyy** [comment]
Assuming everyone uses a cryptographically secure CSPRNG, duplicate Tox ID's will never happen because we are never going to get anywhere near 2^256 public keys. But if it happens, it will result in undefined behaviour.

Also no, it's impossible to infer the private key while knowing only the public key.
I suggest you read up on some of the basic concepts of public key cryptography.

**Comment by SeventhSonOfASeventhSon** [comment]
@Impyy, It's a big world, you might one day, or what if a system is set up specifically just to make accounts all day in order to get duplicate ones?

I use public key cryptography so I understand and know lots about it, this was just a simply misunderstanding as I slightly misunderstood what you meant.

**Comment by Impyy** [comment]
>It's a big world, you might one day, or what if a system is set up specifically just to make accounts all day in order to get duplicate ones?

There are approximately 16541727033902313631938712144098272550467140666520080577065369143987 keys for every single person on this planet (if my math is correct).

And no computer will ever even count till 2^256. It's just not going to happen.

**Comment by SeventhSonOfASeventhSon** [comment]
@Impyy, The processing power of computers is getting stronger every day, and there are super computers which could probably do this if the government got interested in attempting to spy like this on Tox users (if it is possible to use this to spy on users).

You should design a tall wall with just a gap over the top and claim that it's impossible to get a tall enough ladder, because maybe it's very unlikely, but other than luck, there's not much preventing someone doing it however unlikely it is... Plus this is making me think of the plot for one of those disaster movies where there is a big whole in a system because nobody ever thought anybody would find it so they just left it there... This probably won't change your mind, but I have a bad feeling about this, and who knows, someone might read this and make a really popular film of this! ;P

**Comment by ovalseven8** [comment]
>  The processing power of computers is getting stronger every day

Yes, but it's limited by the physics.
But in theory, you're right. It's possible that you can get a Tox ID that somebody else has already.

But no reason to worry. Here explained using the example of Bitcoin: https://www.youtube.com/watch?v=ZloHVKk7DHk

**Comment by GrayHatter** [comment]
closed because it's a question not an issue.

@SeventhSonOfASeventhSon this is a great question for IRC, not toxcore's github
