### ISSUE TITLE
If one or more users are offline in a group chat messages fail to send

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1518]
I have not quite figured out yet whether the issue is here if a user is not online in a group chat but has actually joined and then users send messages there, but this is basically what just happened to me:

I created a group chat, I invited a friend there, we spoke a bit, I then invited another friend there who is currently offline and was offline when I sent the request so they haven't accepted the request yet, but now when I try to send a message in group chat I just get this:

![message_failed_to_send](https://cloud.githubusercontent.com/assets/11575271/12619534/5614b82a-c510-11e5-8678-d9208685fe69.png)

And the other person in the group chat who is online says that they did not receive my messages. They also tried sending messages to me there and though it told them that they sent it without error and it now shows up in their message history, I did not receive it, and as I am talking with them in the normal direct chat as opposed to the group chat, I know that the issue is with the group chat and not with the internet connection or something.

I reported this issue [here](https://github.com/tux3/qTox/issues/2879) but I understand that it is more to do with the toxcore.

---

**OS Information:**

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 15.10
    Release:	15.10
    Codename:	wily
    Flavour: GNOME
    GNOME Version: 3.18

**Package Information:**

    qtox:
      Installed: 471-a3802bd
      Candidate: 471-a3802bd
      Version table:
     *** 471-a3802bd 0
            500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
            100 /var/lib/dpkg/status

**Comment by GrayHatter** [comment]
Yeah, that's qTox's mishandling of current group chats. You can convince them to fix it. (Sounds like they wont). Or wait for new group chats, (which tux3 said he wouldn't implement as they are now.)

**Comment by JFreegman** [comment]
@grayhatter this is actually a core issue.
