### ISSUE TITLE
[RPMLint] Program returns random data in a function

### ISSUE THREAD

**Issue by susnux** [irungentoo/toxcore#1520]
When packaging toxcore for openSUSE I encountered a RPMLint error:

     I: Program returns random data in a function
     E: toxcore no-return-in-nonvoid-function ../other/bootstrap_daemon/src/log.c:78, 95

Because the functions ```int level_syslog(LOG_LEVEL level)``` and ```FILE *level_stdout(LOG_LEVEL level)``` do not provide a default return.
I use a simple patch, if you want you can use it:

http://pastie.org/10701281

**Comment by GrayHatter** [comment]
your patch is a redirect to this page.

Can you open a PR instead?

**Comment by susnux** [comment]
@GrayHatter Yes if you prefer a PR I can do it.

**Comment by GrayHatter** [comment]
Just makes it easier on all of us!

Thank you!
