### ISSUE TITLE
Have the ability to have an "About me" section where users can put what they want

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1526]
I recently wrote [this](https://github.com/tux3/qTox/issues/2940) report on the qTox GitHub page:

> Though not all will have a use for this, for some this will just be something nice to have, but for others this will be something rather useful in some ways to put information that there aren't other fields for that they want their contacts to know without having to message each one about it. So I think that an "About me" section would be very useful (it would probably be located in the "Profile" section where one can set their username and status).

But was told that toxcore needs to implement this so I thought I would file a report here too because I think that it would be really nice if clients could implement this

**Comment by SkyzohKey** [comment]
It should be possible to do this using custom packets (defined in the TCS).

**Comment by fuloating** [comment]
I also thought about this earlier on #tox. and some commented that tox is meant to be IM, not facebook. So just commenting that there are people who like and don't like this idea :)

**Comment by GrayHatter** [comment]
I'm going to close this for that reason.

1) you're not going to get developer support from anyone who's already a contributor
2) you can already implement something like this inside a client with the custom packet api that already exists [on client connect you can send arbitrary data/updates for this section]

I'll be happy to reopen this one, or you can open a new issue that has a much better defined proposal for this.
