### ISSUE TITLE
DNS Issue

### ISSUE THREAD

**Issue by hacker-owl** [irungentoo/toxcore#1529]
```
# nslookup -type=TXT bot._tox.<mydomain>.
bot._tox.<mydoamin>     text =

        "v=tox1;id=DDC2EA4032A6BA8911B15717F40B4CF4BA3913B6D6A0AA45ADE82270DCB0602BA0A9B5C8B2FC"

# nslookup -type=TXT groupbot._tox.utox.org.
groupbot._tox.utox.org  text =

        "v=tox1;id=56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855D34D34D37CB5"
```

I am bassically trying to write a tox1 dns server, and I am encountering some problem, or bug.
this is the nslookup result where I get from my PC, I cannot find any problem with it, but when I intend to add my bot with a client, it fails. But there is no problem with adding the official group bot, or adding the bot directly with id.

**Comment by GrayHatter** [comment]
i think #tox-dev on freenode would be more helpful.

they're gonna ask to see your source

**Comment by SkyzohKey** [comment]
The problem isn't your code but due to the fact that qTox/uTox hard-coded the "authorized" ToxDNS servers. This is stupid but this is the current way it works...

**Comment by ProMcTagonist** [comment]
Isn't toxdns deprecated in favor of an http api now?

**Comment by GrayHatter** [comment]
@ProMcTagonist not yet

**Comment by ProMcTagonist** [comment]
t. utox developer

**Comment by GrayHatter** [comment]
No, more because toxdns is still supported and included in the toxcore repo, and there's no mention anywhere in toxcore about http.

**Comment by SkyzohKey** [comment]
@GrayHatter @tux3 Any plan to recode the DNS system u use to make it working with every toxdns server ? Without hard-coding values in a file ofc. It should be fairly simple to achieve.
For reference Venom did it without any hard-coded values, so you can see how it works in this file: [ToxDNS.vala@naxuroqa/Venom](https://github.com/naxuroqa/Venom/blob/master/src/core/ToxDns.vala)

**Comment by GrayHatter** [comment]
@SkyzohKey not for utox. 

If there is a high demand maybe but I'm hoping to have a name system in place inside of toxcore within 3mo.

**Comment by SkyzohKey** [comment]
3mo ? 3 months ?

**Comment by subliun** [comment]
Yes toxdns is deprecated in favour of the toxme [https api](https://github.com/subliun/toxme/blob/master/doc/api.md). Antox, Toxic, Toxy, and qTox (the major clients) all have support for this api and the toxme dropped support for toxdns two months ago. The https api does not require hardcoded authorised servers.

imo toxdns should be removed from core, there's no reason to have an inferior solution hanging around.

**Comment by GrayHatter** [comment]
@subliun except that https is vulnerable to MITM attacks. 

And didn't you leave tox?

**Comment by LuccoJ** [comment]
That must be why the internet at large, including and specifically banking and other financially sensitive sites, all use HTTPS. Because it's "vulnerable to MITM attacks" without further qualifications.
I don't really like using semi-centralized systems for identifying users on Tox, but let's try to address real, specific concerns about a given technology...

**Comment by subliun** [comment]
@GrayHatter this "problem" was [solved weeks ago](https://github.com/subliun/toxme/commit/4111e7f7c698311e10a8bc4752998cef3413613a). Even if https is broken (which it isn't and almost certainly never will be), you can still verify that toxme has not been mitm'd.

I'm not sure what my departure from Antox development has to do with anything, please try to stay on-topic.

**Comment by quininer** [comment]
I think dns is not a bad choice, dnssec also can withstand a middleman. 
HTTP based but also good, easy browser parser.
