### ISSUE TITLE
Feature request: Incognito mode

### ISSUE THREAD

**Issue by henrikor** [irungentoo/toxcore#1551]
Thanks for great app! And great work! Stolen laptops, police razzia etc. combined with users who doesn’t know to install disk encryption, or to turn of logging make logs an important security concern.

Incognito mode which forces non-logging for every member in a chat would be great.

**Comment by SkyzohKey** [comment]
IMHO Incognito-mode should only load a .tox file. It shouldn't save settings, chat history, etc.

**Comment by ProMcTagonist** [comment]
>forces non-logging for every member in a chat

not possible

**Comment by henrikor** [comment]
I don't know how complicated it would be in Tox. You don't have to force non-logging for every member either. Maybe it's better that you invite to participate in an incognito chat, and then the client will turn of chat history etc. The point here is not to make it bulletproof against people who want to log anyway. You normally will trust the person not to want logging, but maybe not the competence to turn it off.

I'm not developing on Tox, so I leave it to you who do to decide if this is feasible in som way or not.

**Comment by GrayHatter** [comment]
This can't be done by core. This is a feature that could be picked up by a client, but as you said, there's no way to force it.
