### ISSUE TITLE
Tox Nodes are not using TCP 443.

### ISSUE THREAD

**Issue by gqmrtgma** [irungentoo/toxcore#1557]
connecting to TCP 672 194.249.212.109:h
connecting to TCP 808 178.62.250.138:33
connecting to TCP 860 78.225.128.39:334
connecting to TCP 960 192.210.149.121:3
connecting to TCP 940 195.154.119.113:3
connecting to TCP 1004 205.185.116.116:
connecting to TCP 1104 104.167.101.29:3
connecting to TCP 1184 23.226.230.47:334
connecting to TCP 1156 76.191.23.96:334
connecting to TCP 1204 103.38.216.87:33
connecting to TCP 1220 192.254.75.102:3
connecting to TCP 640 46.38.239.179:334
connecting to TCP 1216 130.133.110.14:3
connecting to TCP 656 212.71.252.109:33
connecting to TCP 604 192.99.168.140:33
connecting to TCP 712 108.61.165.198:3
connecting to TCP 752 178.21.112.187:3
connecting to TCP 728 195.154.109.148:
connecting to TCP 780 80.232.246.79:33
connecting to TCP 724 198.98.51.198:33
connecting to TCP 704 144.76.60.215:33
connecting to TCP 692 192.3.173.88:3344

Why Tox's nodes are not 443? Filtered network are not allowing abnormal ports.
How about using 443 TCP, like most of Tor nodes offer?

**Comment by gqmrtgma** [comment]
https://github.com/Antox/Antox/issues/279

**Comment by gqmrtgma** [comment]
Also, how can I set up one(node)(, if it's easy of course)?

**Comment by nurupo** [comment]
[It does try to use standard ports such as port 443 (https) and 3389 (windows remote desktop port)](https://github.com/irungentoo/toxcore/blob/master/other/bootstrap_daemon/tox-bootstrapd.conf#L29), but binding to ports <1024 requires special privileges, and the user the bootstrap daemon runs as is unpriveleged for security reasons, so binding to port 443 fails. There is a way to do it properly without causing security issues, but it's not coded yet. As a workaround, people running tox-bootstrapd using systemd can uncomment [this line](https://github.com/irungentoo/toxcore/blob/a40fd1bb6c4769683c11b3e308279c17a0acbc5a/other/bootstrap_daemon/tox-bootstrapd.service#L14), which would allow the daemon to bind to privileged port.

>Also, how can I set up one(node)(, if it's easy of course)?

[Here are instructions on how to run tox-bootstrapd on SystemVinit, systemd and Docker.](https://github.com/irungentoo/toxcore/tree/master/other/bootstrap_daemon)

The easiest way is to use Docker, as it will install all the dependency packages, build toxcore for you, set config files, etc.

For SysVinit and systemd, you will have to configure tox with `--enable-daemon` flag, have libsodium-dev and libconfig-dev installed, and follow the instructions on that link.

**Comment by nurupo** [comment]
If you decide to run a node, make sure you update it every so often (once a month would do).

**Comment by GrayHatter** [comment]
@nurupo @gqmrtgma if it's a linux box http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l/1762807#1762807

**Comment by nurupo** [comment]
@GrayHatter yes, that's another workaround.

**Comment by mrkiko** [comment]
Issue #1523 maybe discussed a little bit this aspect.
Thank you for your idea of setting up a "standard"-port based node.
Those are crucial in my (maybe misinformed) opinion to get Tox usable on a wider set of networks.

**Comment by fcore117** [comment]
I agree that more 443 or even port 80 nodes are needed, i traveled on cruise ship month ago and tox could not come online but Skype did.

**Comment by LittleVulpix** [comment]
https://github.com/irungentoo/toxcore/commit/98446e0818f3954cba42fdc5f8560a823d455ee4 made this setup work for SysVInit boxes, it works for normal ones as well. You can use tox.nodes.chat website to see which nodes are running @ 443 and bootstrap off of them explicitly.

**Comment by mrkiko** [comment]
Thank you LittleVulpix and everyone for those suggestions, code and comments. I'm happy to see costructive work going on.

Regarding the technical thing: has someone tried bootstrapping off of those nodes? I remember at some point i succeeded coming online, but after some time I got disconnected; as if Tox was trying to connect to different nodes but couldn't.
It's a delicate problem in my opinion. tox behaves in good sense fashion in this case, and this is good. However, working around setups like this (allowing only 80,443,etc ports) probably requires something more "rude", something unfortunately requiring more resources and setup, more time.
This can be a problem. I unfortunately don't have an answer.

**Comment by IlyaIndigo** [comment]
qTox SHOULD NEVER use the Web ports !!!
This is me on Skype is always hated, and here you are again out of the box it offers.
The ports 80 and 443 should only for apache or nginx!

**Comment by LittleVulpix** [comment]
@IlyaIndigo you misunderstand. Qtox doesn't use those port, this is only for the DHT network (i.e. the dht servers that you connect to). Those need to be able to run on 443 because since it is the "https" port, most firewalls (even company firewalls) allow access to this port.

If you only use qtox or a tox client in general, it doesn't actually use 80 or 443 but in general just 33445 upwards.

**Comment by LittleVulpix** [comment]
@irungentoo this can be closed, there are several tox nodes that run on 443, and their list can be obtained here: https://nodes.tox.chat/

The issue with binding to low ports was fixed by https://github.com/irungentoo/toxcore/commit/98446e0818f3954cba42fdc5f8560a823d455ee4

**Comment by IlyaIndigo** [comment]
@LittleVulpix Thank you for the clarification.
