### ISSUE TITLE
How can I set up "Tox node - Tor Hidden Service Edition"?

### ISSUE THREAD

**Issue by gqmrtgma** [irungentoo/toxcore#1559]
My internet doesn't offer global IP, so I can't help nodes.
However, I fully know how to set up Hidden Service(tor).

It'll be nice if you make tox-node server SIMPLE. For example,

# apt-get install tox-help-node
# nano /etc/tox_node.conf

> # Tox Node
> # Welcome to beta
> LOG_DO_IT = 1
> LOG_FILE = /dev/null
> LISTEN_PORT = 82
> LISTEN_IP = 127.0.0.1
> MUST_USE_PROXY = 1
> PROXY_IP = 127.0.0.1
> PROXY_PORT = 9050
> PROXY_TYPE = "SOCKS5"
> # endo of config file

(= listen localhost:82/tcp. Then, tox-node must use proxy if it wants to connect outside.)
(= LOG_DO_IT eq 0 ... dont log anything(for SSD server which don't wanna write to disk)

# service tox-node restart
(= restart to see effect)

$ etc /path/to/torrc (and edit for Tor hidden service)

ta da!

Tor====>Tor---ToxNode

**Comment by gqmrtgma** [comment]
If I set Antox or uTox to use Tor(localhost), they will use xxxxxxxxxxxxxx.onion:82 instead of "clearnet" IP address, in result enhance security and privacy.

**Comment by gqmrtgma** [comment]
LOG_DO_IT = 1
LOG_FILE = /dev/null
SELF_NODE_NICKNAME = I_Am_Hero
SELF_NODE_HOSTNAME = xxxxxxxxxxxxxxxxxxxxxx.onion
LISTEN_PORT = 82
LISTEN_IP = 127.0.0.1
MUST_USE_PROXY = 1
PROXY_IP = 127.0.0.1
PROXY_PORT = 9050
PROXY_TYPE = "SOCKS5"

(added SELF_NODE_)

**Comment by ProMcTagonist** [comment]
Why close?

**Comment by GrayHatter** [comment]
@ProMcTagonist what issue exists in toxcore?

**Comment by ProMcTagonist** [comment]
It seemed like @gqmrtgma was asking to be able to set up and use .onion bootstrap nodes.

**Comment by gqmrtgma** [comment]
That's right @ProMcTagonist... At first I saw this issue is closed, I thought "Well, tox decided not to honor anonymous connection anymore".

Yeah, why close? "Connecting to .onion nodes if uTox|Antox using Tor" has huge benefit on security and privacy, rather than using normal IP address access.

I posted this issue for hope that I can set up a simple ".onion tox node server" to help tox network.
Close. Ok. Your choice.

**Comment by GrayHatter** [comment]
I closed the issue, for a few reasons.

First it was/is very difficult to follow, with a lot of erroneous data. The
title has nothing to do with the issue/request.

And as for supporting domain.onion you'd need to bake tor support into
toxcore. And I don't think there's enough demand for that.

I could be wrong, but either way this issue needs a lot of work it make it
something I'd reopen.

**Comment by ProMcTagonist** [comment]
Is there a toxcore guide to issue formatting?

**Comment by GrayHatter** [comment]
Clear title, obviously readable.

Ideally: easily skimmable

**Comment by ProMcTagonist** [comment]
@gqmrtgma It sounds like if you rewrite this issue with some more clarity and focus we can get it open.
