### ISSUE TITLE
Let's talk distribution

### ISSUE THREAD

**Issue by drewcrawford** [irungentoo/toxcore#156]
Hi guys,

I left a [comment](https://github.com/irungentoo/ProjectTox-Core/issues/58#issuecomment-21739515) on #58, but it seems like that discussion is basically a licensing flamewar.  And it's hard to have a reasonable licensing discussion if there is *no clear plan for how to distribute the software to begin with*.

Really what *I'd* like to know is what the plan is to roll this thing out.

1.  To get widespread adoption (and it really isn't clear to me if that's a goal), you're going to need to write UIs for maybe a dozen windowing systems / platforms.  Windows has a thing, OSX has AppKit, Linux has GTK, Qt, etc., iOS has UIKit, Android has a thing, etc.  **Where does this code go?**  Does it get checked into ProjectTox-Core?  Does somebody set up a dozen little repos that consume ProjectTox-Core as a library?  What is the vision here?

2.  Who do you envision maintaining these ports?  Do the current contributors to core have enough time and energy to maintain ports?  Is there a search ongoing for a maintainer for one or more platforms?

3.  Is the goal here to have a single, unified Tox experience on all the platforms, or is the goal more to create an ecosystem of "Tox-compatible" software?  If it's the former, is there a search ongoing to find someone who is willing to form a legal/taxable entity to formally distribute the software through the official platform channels?

My very sincere concern is that the technical work can progress because that is easier than achieving consensus on these questions, but that strategy only delays the problem.  And it gets harder to solve as time goes on and more contributors become invested, with potentially conflicting goals.  So to avoid becoming yet another failed encryption project, it is super critical to get stuff like this decided and to start already carrying it out.

**Comment by GrayHatter** [comment]
stale, we have a distribution system care of the Tox Project
