### ISSUE TITLE
travis-ci not working?

### ISSUE THREAD

**Issue by tycho** [irungentoo/toxcore#1563]
https://travis-ci.org/irungentoo/toxcore

"This is not an active repository"

Also the badge shows the build is "failing", presumably because of the above...

**Comment by cebe** [comment]
[travis is working fine](https://travis-ci.org/irungentoo/toxcore/builds), no idea why it shows this message, mabe because master has a build that is very old.
Build is failing because toxav.h is not up to date with toxav.in.h.

**Comment by chipitsine** [comment]
anyone care to sync toxav.h and toxav.h.in?

**Comment by GrayHatter** [comment]
it will in the `new` branch
