### ISSUE TITLE
NSA Officers writing Botnet software?

### ISSUE THREAD

**Issue by SecUpwN** [irungentoo/toxcore#1565]
Good morning @irungentoo and `Tox` developers! I have been using `Tox` for quite a while back in 2014 and uninstalled it at some point since I did not need it any longer. Now I am at the point again that I'd like to use a secure, cross-platform and open source communication platform. In the back of my head, I remembered the website address to be [redacted] (I now know that your official address is **https://tox.chat**). But what does the statement on that first linked site mean? I read between the lines on your GitHub Issues here that [redacted] belongs to a now kicked (?) Tox developer, but would you please be so kind to give me and other users a round-up of the current situation? **A statement on your `README` about that would be perfect, it really was a knock-off for me installing your software and I will refrain from doing so until this Issue has been clarified in public.** This is the statement:

[redacted]

-- redacted by @GrayHatter

Reason : I try to avoid link farming on this repo

**Comment by ProMcTagonist** [comment]
some guy who never wrote any code and got banned for stealing thousands of dollars put an april fool's post on his blog because trying really hard to be funny is his way of attempting to weasel back into the community via reddit

**Comment by SecUpwN** [comment]
Thanks for responding, @ProMcTagonist. Do you have any references to back this up? What I don't understand is why this april fools post seems to be about a "stolen Tox logo" and there does not seem to be any official clarification of the Tox project itself. This "april fool's post" really draws away users from the project and should be clarified in broad public, especially directly under the [compromising reddit post](https://www.reddit.com/r/projecttox/comments/4c90he/more_than_6months_ago_campaign_for_improvements/d1g83vt).

**Comment by GrayHatter** [comment]
Us developers try to avoid commenting on trolls and/or jokes.

The post (that I redacted) is both. 

If you're actually concerned, you're welcome to come discuss it with us in the IRC channel #tox on irc.freenode.net. Otherwise, this is for issues related to toxcore code, not other stuff.

Thanks, your friendly neighbourhood developer.
