### ISSUE TITLE
Ability to set birthday and be alerted to the birthdays' of friends

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [irungentoo/toxcore#1566]
**I requested the following in [qTox](https://github.com/tux3/qTox/issues/3157) but was told to make the request upstream instead for this to be allowed:**

> 
> In other IM programs such as Skype there is a rather fun and possibly even useful feature which allows you to enter your date of birth so that when it is your birthday your friends are alerted to this fact and there is something like a picture of a present or cake next to your profile (maybe next to the status icon - which shows if you are online, away, busy, or offline).
> 
> I think this would be a nice feature to have in qTox. There of course also have to be privacy settings for the date of birth, or perhaps it should be made so that one does not have to enter the year, but if they do their friends will be alerted to their age too.
> Friends would also be able to set if they wish to receive birthday notifications about their contacts, they could even perhaps be able to say which friends they want to receive these sorts of alerts from, and perhaps the people with the birthdays should also be able to set who receives the notifications about this.
>

**Comment by GrayHatter** [comment]
I'm going to close this. It's not a toxcore feature. 

If you want to open a different issue (the ability to share metadata/information) That might help qTox in writing in this feature. 

Otherwise, as this issue is written, it's already possible, use `tox_friend_send_lossless_packet()`
