### ISSUE TITLE
An idea to connect Tox from current mobile network.

### ISSUE THREAD

**Issue by verycrypt** [irungentoo/toxcore#1567]
If you're against PRISM, you might want to read this idea.
How about creating a connection point which serve mobile-to-Tox-network connection?

example:
+1.111.9999 (Official Tox Incoming Number: OTIN)
Ext.No. 66352 (User can register and get a number)

PRISM-affected user(Google,Skype,3G,4G,etc): "NSA"
uTox user: "TOX"

---

[NSA]--->+1.111.9999.66352.--->Mobile Phone Network--->OTIN---tox network--->[TOX]

Hint:
1. In some countries, "Incoming calls" are always $0(free).
2. We should alert the phone caller using this voice message:
"You are calling from NSA network. Consider using Tox instead. Connecting to Tox user now, standby."
3. If we achieve this, no one will use SIP/OSTEL/www.poptox.com network anymore!

Arguments:
"TOX network is unstable!"
I disagree; in my test on low-speed internet(with proxy & UDP disabled), tox chat's speed is fast enough to handle realtime communication.

"How did you buy +1.111.9999 number?"
I don't know; buying it from Skype or something?

"How did you serve outgoing?"
What's the point of using unencrypted mobile network?

**Comment by verycrypt** [comment]
I don't know about other country, but currently, these countries are $0 incoming calls.

India
Japan

**Comment by dangowrt** [comment]
On Mon, Apr 25, 2016 at 03:56:43AM -0700, verycrypt wrote:
> "How did you buy +1.111.9999 number?"
> I don't know; buying it from Skype or something?

sipbroker.com did something similar a decade ago.
check didww.com or telecallmart.com for incoming numbers.
there used to be ipkall.com, but apparently they are closing down :(

**Comment by GrayHatter** [comment]
I'm going to close this because it shows a shocking misunderstanding of both SIP and POTS
