### ISSUE TITLE
error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL

### ISSUE THREAD

**Issue by wisekaa03** [irungentoo/toxcore#1571]
~/qTox/libs/libtoxcore-latest ~/qTox
Running autoreconf -if...
configure.ac:292: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:293: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in configure_aux "."/configure_aux

**Comment by askmatey** [comment]
Have you installed `libtool`?

**Comment by entangledloops** [comment]
Same error for me. Just running `autorecong -if` with no changes to any scripts produces this error. Building on an NVIDIA Jetson (32-bit arm7l).

**Comment by mh5** [comment]
Do you have libtool installed? If not, install it first. This solved the issue for me.

**Comment by lilianmoraru** [comment]
For people that have `libtool` installed but in a custom path, you need to either:
- `export ACLOCAL_PATH="/custom/path/libtool/share/aclocal"`
or
- `autoreconf -I /custom/path/libtool/share/aclocal`

**Comment by MagicSen** [comment]
thanks, @lilianmoraru it works.

**Comment by ChihweiLHBird** [comment]
It would be nicer to have a hint about `libtool` is missed.

**Comment by codedust** [comment]
This repo is not maintained any more. See https://github.com/irungentoo/toxcore/issues/1663
