### ISSUE TITLE
Looking beyond WhisperSystems

### ISSUE THREAD

**Issue by HulaHoopWhonix** [irungentoo/toxcore#1573]
WhisperSystems is not just being indifferent to users who want to run Tor and a libre mobile OS but openly hostile to any server federation efforts. They are refusing to open source their VoIP server implementation too:

https://archive.is/zmsPz
https://archive.is/H0tZ

Moxie's argument that centralization is necessary to implement protocol changes fast enough to stay competitive is clearly unfounded. There are plenty of libre P2P chat networks who are also evolving.

I propose you reach out to the Copperhead Android guys and have Antox included as a default chat application for this privacy-centric ROM.

**Comment by GrayHatter** [comment]
closing because not a toxcore issue... #tox on irc.freenode.net is probably a better place for this topic
