### ISSUE TITLE
uTox crashes upon connecting to friend (alpha 0.9.1 build downloaded tonight, immediate issue upon post update execution))

### ISSUE THREAD

**Issue by MaverickJsmith** [irungentoo/toxcore#1579]
As of nearly an hour ago (5/22/2016 ~8pm PST) a friend and I were going to use uTox to chat. An update was found (uTox Alpha 0.9.1), installed, and we found that the instant our Tox clients connected (First run post update) to each other, they both froze. We have tried setting UDP to "no", setting IPv6 to "no", I have tried rebooting my computer, opening a DMZ, about everything else my IT knowledge will allow.

Behavior I have seen in detail:
- Tox  is executed, connects to network. ~15 seconds later Tox connects to friend, instantly freezes (Taskbar for window adds "Not Responding"), window turns the bright white "frozen" shade when interaction with window is attempted beyond waving mouse cursor over it, but windows "Program is not responding" promt never appears until attempt to shut down Tox is tried.

- Tox will shut down immediately and swiftly. 

- While "frozen" resource monitor will show Tox communicating (sending and receiving), and if left open long enough, new connections (up to one witnessed thus far) created while Tox is supposedly "Not Responding"

I don't know what's going on. I've looked for logs and as far as I can see my uTox hasn't created any. I don't know how old new this build is but it is at least a 48 hours~ old since that was the last time my friend and I used Tox and it updated.

I wish I had more info for you guys but that's all I got, if there's anything I can do to provide more information I'm all ears. I'll try anything you guys suggest and give you detailed info back on the results. If my friend and I have to roll back to the previous build we will but this has ground a project of ours to a halt.

Any help you guys could give is greatly appreciated.

Thanks for your time.

**Comment by GrayHatter** [comment]
https://github.com/GrayHatter/uTox/issues/
