### ISSUE TITLE
Building with Code::Blocks on Windows

### ISSUE THREAD

**Issue by proxifier** [irungentoo/toxcore#1592]
I'm trying to compile sample code which found on wiki.tox.chat(chatbot).

1. Copy source code and make a new file, "source.c"*.
2. Download "toxcore-master.zip" from here, copy all folders inside it to the same folder(*).
3. Open Code::Blocks and load source.c. Changed "#nclude <tox/tox.h>" to "include <toxcore/tox.h>".
4. Click Build.

Got:
fatal error: sodium/utils.h: No such file or directory

Ok, so how can I download it on Windows?
I don't want to use Linux to build Windows EXE files, because I'm not a Linux developer.
I prefer using CodeBlocks on Windows to create/develop software.

Any advice except Linux thing?

**Comment by proxifier** [comment]
> Changed "#nclude " to "include ".

WTF Github...
I wrote:

> include tox/tox.h
> to include toxcore/tox.h

**Comment by GrayHatter** [comment]
We don't offer support for arbitrary build environments. You can try asking on IRC for support, you'll likely have better luck there. Or you can use one of the methods we support... https://github.com/irungentoo/toxcore/blob/master/INSTALL.md
