### ISSUE TITLE
Need some detailed explanation about sample code.

### ISSUE THREAD

**Issue by proxifier** [irungentoo/toxcore#1594]
Having well-written example helps many people to understand the code better.

https://wiki.tox.chat/developers/client_examples/echo_bot

> Tox *tox_new(const struct Tox_Options *options, TOX_ERR_NEW *error);
> Tox_Options struct can be used to specify such options as whether toxcore should be using a proxy for routing the network traffic

Okay, so what is the options, and how can I use them?

> string IPPort = '127.0.0.1:9150/SOCKS5';
> Tox *tox = tox_new(IPPort, NULL);

Some detailed function explanation, such as this one ( https://secure.php.net/manual/en/mysqli.construct.php ) will be great.

**Comment by SkyzohKey** [comment]
http://ricinapp.github.io/toxcore/toxcore/ToxCore.Options.html ← Just transpose this (Vala) to C and you go. :)

**Comment by proxifier** [comment]
Ty.
