### ISSUE TITLE
Need some details: Does Tox leak my IP address? 

### ISSUE THREAD

**Issue by proxifier** [irungentoo/toxcore#1596]
> https://wiki.tox.chat/users/tox_over_tor_tot
> "Does Tox leak my IP address?" section of https://wiki.tox.chat/users/faq

How will my 'friend'(also via Tor or non-tor) see my IP address(I'm via Tor).
127.0.0.1, 10.x.x.x(my local network IP), or Tor's exit node IP address?

**Comment by Zer0-One** [comment]
The bug tracker is not for general Q&A, please take it to IRC, or the mailing lists.

**Comment by proxifier** [comment]
@Zer0-One

Can anyone tell me where's the IRC is!?
https://wiki.tox.chat/start?do=search&id=IRC&button=
https://tox.chat/faq.html

Also, why not set up a "Group" using Tox? It doesn't make sense to use IRC. Tox support Group chat, right?

**Comment by cebe** [comment]
> Tox support Group chat, right?

not yet in a way that is useful like IRC.

#tox on freenode: https://freenode.net/

**Comment by proxifier** [comment]
I tried webchat on freenode, looks like it hates Tor, so I'll pass.

Moving this Question to https://github.com/Tox/tox.chat/issues/109
