### ISSUE TITLE
Tox is really dying, isn't it?

### ISSUE THREAD

**Issue by proxifier** [irungentoo/toxcore#1597]
This[1] caught my attention. I also looked at Tox Staticts and found that

ONLY 2,200 PCs USING TOX WORLDWIDE[2].

Seriously?
We need to bring people from "The Tor Project" "Ring.CX" or something.
Because the fact that "Tox" is not famous, I think we need more recommendation(advertise by human) by media websites.

1 https://www.reddit.com/r/projecttox/comments/4phc85/is_tox_dying/
2 https://toxstats.com/

**Comment by rmsEfx** [comment]
Yep, serious promotion in need ...

**Comment by vladimiry** [comment]
It's just not usable thing until lost connection issues is not fixed. So in my opinion it would be better to not announce it to the new people, since user the first impression might be negative due to the lost connection issues.

**Comment by proxifier** [comment]
If the user is in office where Internet is always available, he/she won't got automatic disconnection.

If the user use a Internet which serves poor availability(e.g., lost connection frequently, global IP frequently changed by ISP), then he/she will suffer disconnection issue.

To me, the latter can can be solved/partially-resolved by using "Tox" with "Tor" SOCKS5 proxy.
Try this combination if your Tox is unstable. Extra Privacy(IP masked by Tor) and Connection Stability guaranteed by me ;-) (tested on 5 PCs and 1 Android)

**Comment by vladimiry** [comment]
> If the user use a Internet which serves poor availability(e.g., lost connection frequently, global IP frequently changed by ISP), then he/she will suffer disconnection issue.

It's not the only possible reason of the disconnection issue. For me it happened after hibernate/sleep mode, ie not due to the poor internet connection.

**Comment by proxifier** [comment]
Disconnection issue should be discussed at #2820 I think, but, I'll answer anyway.

> it happened after hibernate/sleep mode

Of course this will happen. Why? Because if you sleep or hibernate(hard sleep) your computer,
all process will be stopped by the OS. The connection to the Internet terminates itself or by the OS automatically. Internet packet have its own Time-To-Live. There's no "persistent" connection on the Internet.

When you awake your computer, all your running software does not have any connection to the Internet. This is expected.

So, how qTox/uTox/Antox fix this? Simple, detect "awake from sleep/hibernation". And "reconnect itself".

**Comment by vladimiry** [comment]
>  detect "awake from sleep/hibernation"

Obviously yes, but seems Tox has not such feature implemented, at least at the time when I tried it. In my experience any decent communication applications do have this feature implemented. So for me Tox is not usable since I'm not going to reconnect manually every time I expect Tox doesn't work properly.

**Comment by GrayHatter** [comment]
This isn't a toxcore issue... find a different place to spread FUD
