### ISSUE TITLE
GrayHatter changed the title without user permission ( and this one too)

### ISSUE THREAD

**Issue by ghost** [irungentoo/toxcore#1598]
No, I'm enforcing a strict no FUD, or trolling on this toxcore repo.

You may troll, complain, meme, s**tpost, other, on any of the other sites that'll allow it. 

OR on IRC too...

But not in the issues section of toxcore!

-- Edited without care by @grayhatter

**Comment by proxifier** [comment]
Also, YOU said TOX is DYING. Yes, you. Let me repost your word here.

> https://github.com/irungentoo/toxcore/issues/1598
> <@grayhatter> rip tox

Do not offend the collaborators by changing the title to FUD next time.
Again, I did not say anothing about FUD.
