### ISSUE TITLE
Consider DP5 for Online Presence

### ISSUE THREAD

**Issue by haraldh** [irungentoo/toxcore#1605]
Whitepaper: http://www.cypherpunks.ca/~iang/pubs/dp5-popets15.pdf

Presentation:  https://www.youtube.com/watch?v=DX1fP-TO02M

Code: git://git-crysp.uwaterloo.ca/dp5

**Comment by ProMcTagonist** [comment]
This seems to be totally useless for Tox, which has no central server. Adding centralization to manage presence would make Tox worse, and would be an anti-feature. 

As it stands, Tox bypasses the concerns that spawned DP5 entirely by doing away with centralized servers.

Is there something I'm missing?

**Comment by askmatey** [comment]
This is an anti-pattern. Tox is all about decentralization.

**Comment by haraldh** [comment]
Well, it's about querying more than one DP5 server.
Everyone could run a DP5 server to make it more unlikely that one DP5 server is hiding information from you.
Of course as noted by the author, it does not scale very well.
Just wanted to inform about the existence of such mechanism.

**Comment by GrayHatter** [comment]
Never hurts to have more information. May you wanna post it all to the reddit as well? https://www.reddit.com/r/projecttox/
