### ISSUE TITLE
toxav: why stick to only one image format?

### ISSUE THREAD

**Issue by Mikhael-Danilov** [irungentoo/toxcore#1607]
If we extend toxav api to allow more or less arbitrary pixel format chose we can avoid couple of format conversions between camera and encoder.

Any drawbacks (aside that this need to be implemented ?)

**Comment by isotoxin** [comment]
Disagree.
toxcore is not graphic library. Image format conversion isn't toxcore job

**Comment by Mikhael-Danilov** [comment]
Hmm... looks my first post is not clear enough.
I'm not propose to do image format conversion inside of toxav.
I'm propose to allow toxav clients have broader format selection from many already supported by libvpx.

**Comment by isotoxin** [comment]
> I'm propose to allow toxav clients have broader format selection from many already supported by libvpx.
libvpx supports only one image format
There are third party lib (libuv) in sources of libvpx, that allows to convert image formats, but client must use libuv itself.

**Comment by Mikhael-Danilov** [comment]
libyuv... Well... Yes this renders issue irrelevant as long as vp8 is only video codec for tox.
Thanks.
