### ISSUE TITLE
Toxencryptsave should provide functions for multi-part encryption

### ISSUE THREAD

**Issue by initramfs** [irungentoo/toxcore#1608]
As of right now toxencryptsave provides a few functions for key derivation as well as symmetric encryption of data (with the added convienence of saving the salt, nonce and other cipher parameters at the start of the file).

However, these functions expect all the data to be encrypted/decrypted presented up front, as a pointer to the data. If the data is file-based, not only does this require completely reading the file, it also requires the entire contents of the file be loaded in memory. When considering that functions in this library can be used for encrypting chat history, the filesizes involved can easy hit sizes that are not feasible to be completely loaded in memory (especially for embedded or portable devices). This also becomes an issue where I/O itself is slow (such as files over an NFS mount) where encryption/decryption that could've been done parallel to the I/O is delayed until I/O is complete.

Thus, should this library's use-cases involve providing tox clients with a standardized way to encrypt arbitrary tox-related data, the library should be expanded to support multi-part encryption where the plaintext (or ciphertext for decryption) can be given in small chunks as to conserve I/O and memory resources.

**Comment by GrayHatter** [comment]
If you're encrypting chat history, you should be encrypting messages, or days. Not the entirety of the history. It makes saving, loading, destorying and grepping easier. Then you can encrypt days of logs instead of weeks, months, years.

If you want to be really fancy, encrypt each message by itself. Then you can seek through messages, loading/decrypting them only as you need to.

**Comment by initramfs** [comment]
@GrayHatter I'm using chat history as an example of a potential "arbitary data" blob that is large in size. Besides, some clients opt to using DBMS to manage chat history (as such, encrypting parts of the DB becomes harder) and encrypting each message on it's own generates quite a lot of overhead. But this is beside the point.

If this library was never meant to handle data of large sizes, then I rest my case. I brought it up because of the way the documentation phrased it (from `tox_pass_key_encrypt`):

> Encrypt arbitrary with a key produced by tox_derive_key_*.

Somwhat implying this was meant for bulkb data encryption.

**Comment by GrayHatter** [comment]
If you're using a DBMS, why can't you just use the encryption system built into that software?

ToxES will handle any* amount of data that you give it. Memory management, and I/O is left to the developer as nearly all of Toxcore is, so I think I might be misunderstanding you on this one. Is the problem that ToxES doesn't segment the data sizes for you? If so, why do you think ToxES is best suited to decide what parts should be encrypted when?


*some restrictions apply.

**Comment by initramfs** [comment]
Perhaps I have a gross misunderstanding of the code, but it seems that ToxES' encryption functions, namely `tox_pass_encrypt` and `tox_pass_key_encrypt`, expect the "full data" to be given. I say this because apparently every invocation of the function generates a header, random salt and nonce to be used. As such, for effective use, all the data to be encrypted/decrypted must be done in one go (i.e. a single invocation of the function).

What I suggest is the additional of functions that allow you to initialize a encryption/decryption operation and then repeatly invoke some update function that will perform encryption or decryption on the particular segment of data passed. A good example of this would be the [Cipher](https://docs.oracle.com/javase/8/docs/api/javax/crypto/Cipher.html) in Java, particularly the [update()](https://docs.oracle.com/javase/8/docs/api/javax/crypto/Cipher.html#update-byte:A-) function.*

This way, you could encrypt as you go (if you excuse the poor phrasing). For an example, consider a 100 MB blob of data, the existance of this "update" function would allow you to say, call update() on the whole blob at once, or call it twice on the first and the second 50 MB, or call it 10 times on 10 MB slices and so forth, all resulting in the same result. The goal being that, you could essentially write code that: reads a buffer of data (say 64K), decrypt the buffer and proceed to immediately use it (and vice versa).

And again, I'm really not suggesting what ToxES should be used for, just that given it's generic nature, it could be modified to handling large pieces of data easier, allowing for more use-cases (and thus me asking earlier, does ToxES already have a specific use case in mind that limits it to small files/data?).

I'm perfectly aware that other libraries that provide symmetric encryption exist (particularly ones in DBMS as well), but ToxES provides good integeration with the existing "tox user password" and offloads the burden of good file security from tox clients. I'm merely suggesting a way to improve handling with large data files.

*sorry for a java example, I would come up with a C/C++ example but I don't have the docs for any at my disposal right now.

**Comment by GrayHatter** [comment]
Are you sure you read the whole of ToxES? 

Either the functions to do what you want are already added (Read part 1, which comes after part 2 in the .h file) Or you're likely to want to handle the encryption on a much lower level. I.e., you'll have to create and manage the keys and block sizes yourself.

Other than that, there's really no good way to use a convenience library to do complicated data management. There are functions as a part of the NaCl library but they're not used inside Toxcore. (Because crypto_box provides better security, and toxcore is happy to split data into known block sizes)

**Comment by initramfs** [comment]
Yes I've read both parts, the part one function `tox_pass_key_encrypt` prepends the encrypted ciphertext with a header consisting of:

> the output data consists of, in order: salt, nonce, mac, enc_data

(as stated in the comments for the implementation).

If you had a 20 MB file and called it, specifying 20 MB as `data_len`, you'd get a file that looks something like this:

    | Magic | Salt | Nonce | MAC | 20 MB of ENC DATA |

but if you called it twice, with `data_len` being 10 MB and `data` pointing to the start and then the 10 MB mark (on the second invocation) of the data buffer, you'd get:

    | Magic | Salt | Nonce 0 | MAC 0 | 10 MB of ENC DATA | Magic | Salt | Nonce 1 | MAC 1 | 10 MB of ENC DATA |

a different result to the above.

---

Upon further reading the documentation of libsodium, it does not seem possible to implement what I proposed in this issue. I guess I'll close it for now... If I have time, I'll see if I can work on a PR that actually implements what I said (if that's even possible).
