### ISSUE TITLE
release tarballs

### ISSUE THREAD

**Issue by ng-0** [irungentoo/toxcore#1610]
Hi,

it would be great if you could make releases once in a while so that packaging is easier and does not require checking out a commit of this repository.

Thanks

**Comment by GrayHatter** [comment]
any reason you can't use https://github.com/irungentoo/toxcore/archive/master.zip

**Comment by GrayHatter** [comment]
https://github.com/irungentoo/toxcore/archive/master.tar.gz might work as well, but I haven't tested it.

**Comment by felix-salfelder** [comment]
same situation here (packaging for major GNU/linux distro). git snapshots are not suited well.

* snapshots are inofficial
* version is missing
* history is missing,
* there's no checksum,
* files generated by autotools are missing.

(maybe there are more reasons)

... so could you please `make dist` and provide tox-0.0.0.tar.gz (preferrably at a canonical place such as https://tox.chat/download.html?) also: please merge #1609

thank you!

**Comment by GrayHatter** [comment]
None of the above are too likely here. You should reopen this issue on
https://github.com/TokTok/toxcore

**Comment by felix-salfelder** [comment]
what is TokTok? (never heard of it)

**Comment by GrayHatter** [comment]
it's a fork that's see development

**Comment by felix-salfelder** [comment]
thanks. seems to make more sense to try [here](https://github.com/Tox/tox.chat/issues/116).

**Comment by ng-0** [comment]
For a reason, see this comment https://github.com/Tox/tox.chat/issues/116#issuecomment-241252433

**Comment by ng-0** [comment]
As [this](https://github.com/Tox/tox.chat/issues/116) has been close, can we continue this dicussion here?

**Comment by ng-0** [comment]
I am closing this now. Anyone who feels this needs to be addressed should reopen it. 

https://github.com/irungentoo/toxcore/issues/1610#issuecomment-241283078

**Comment by felix-salfelder** [comment]
i have started some packaging [here](https://anonscm.debian.org/git/pkg-voip/tox.git/). maybe there are 10,000 users waiting for a release, maybe it's just me. anyway: asking here seems to be a natural thing to do.

(I don't know, how to reopen. perhaps only the issue/project owner can do such things?)

**Comment by ng-0** [comment]
I have packaged it for Guix, currently pending review.

Why I closed this is that it is upstreams decision not to do a release. As a person who packages their software I can make suggestions and ask, but I want to work as close as possible with them. So if they decide not to do release numbers and prefer git, svn, fossil, or whatever instead of tarballs it is their choice and I have to work with that. As much as I'd love to see versions where one can point to and use (see thread), I have to accept their choice for their software.
In Guix we can include software which is in version control, pinned to a checkout and its calculated hash. I assume Debian has equal options, or is this a major block for you?

**Comment by felix-salfelder** [comment]
> Why I closed this is that it is upstreams decision not to do a release.

havent heard a reply from a/the presumable author yet. so actually i don't know.

> In Guix we can include software which is in version control, pinned to a checkout and its calculated hash

what do you do if the library interface changes in a newer version? without version numbers, this will likely break all of the reverse dependencies, when updating the library package. it's a question of time, but obviously, this will happen. who will be responsible then?

note that debian (for good reasons) ships and uses *shared* libraries whenever technically possible.

i think if somebody is willing to take care of a package with extra complications, (s)he is welcome. i consider messing with nontrivial internal things during packaging close to forking. and i am not willing to maintain a fork.

typically upstream authors understand the problem sooner or later. `configure.ac` clearly indicates that there was at least one author involved, who knows how to do releases and versions properly. so as long as these traces of sanity are in place, i'm sure i will prefer waiting to taking any other action.
