### ISSUE TITLE
there is no qtox-unity 

### ISSUE THREAD

**Issue by ZamanOof** [irungentoo/toxcore#1611]
after follow instruction from 
[https://tox.chat/download.html#gnulinux](https://tox.chat/download.html#gnulinux)
in the last step to install qtox-unity 
but there is no qtox-unity package  and try this command to show unity package
`cat /var/lib/apt/lists/pkg.tox.chat* | grep "unity"`
there was't unity  package .

**Comment by GrayHatter** [comment]
you want the tox/tox.chat repo

**Comment by ZamanOof** [comment]
so how can i get it?
regards

**Comment by cebe** [comment]
@ZamanOof please report the issue here: https://github.com/tox/tox.chat/issues
