### ISSUE TITLE
Push Notification service

### ISSUE THREAD

**Issue by KOLANICH** [irungentoo/toxcore#1614]
Now the ones who want to connect their service to mobile app have to use push services by major companies : Google, Amazon, Yandex, Baido. It works in the following way: preinstalled (Google, Yandex, Baido) or manually installed (GMS or MicroG on custom roms, Yandex, Baido and Amazon) apps maintain connection to vendors' services and  exchange messages with them, when a dev's app sends a notification it uses vendors' services API. It allows to lower power consumption and save mobile traffic as it reduces number of connections the device has to maintain at the cost of centralization.

When a user uses Tox, his device has to maintain a lot of connections anyway (and the battery is drained extremily quick, at least when using Antox). I think Tox can be used to transport these notifications to devices instead of centralised services. The service owner install Tox and triggers its API instead of third-party service using tox address uploaded by an app instead of vendor-generated ID.

**Comment by GrayHatter** [comment]
Any client can do that already. You just need to hook your app into toxcore.

**Comment by KOLANICH** [comment]
This will cause very high power consumption due lot of tox clients running in the device. It is not a trouble to devs implement own message service at cost of traffic and power consumption, it would be less consuming than tox. But another way is to use the service built into tox client with the same api and controlled by the same android permissions other services are controlled.

**Comment by GrayHatter** [comment]
Eventually we hope to have the power and data usage fixed to a much more reasonable level. In which case then it shouldn't be a problem. That said, it's really not the goal of toxcore to be a push message service. So while the goals are similar, and somewhat aligned, toxcore isn't really intended to fit that niche.
