### ISSUE TITLE
Contacts who are both online sometimes don't see each other as online until restart

### ISSUE THREAD

**Issue by yurivict** [irungentoo/toxcore#1618]
I have two connected accounts, one using qTox, and another using Antox, both being online  for a long time. At some point I noticed that they both don't see each other as "online". After I restarted qTox, they see each other in "online" status again.

This is a very bad problem because the core function (seeing the contact online) is broken.

**Comment by LittleVulpix** [comment]
Duplicate of https://github.com/irungentoo/toxcore/issues/1349

**Comment by SkyzohKey** [comment]
@GrayHatter duplicate spotted, can u close ?

**Comment by yurivict** [comment]
Is this fixed in the latest devel branch? I use toxcore-0.151112_2 - is this an outdated version?

**Comment by GrayHatter** [comment]
@yurivict no, but someone else already opened this issue
