### ISSUE TITLE
UDP packet loss (unsupported UDP) should be reflected in the cient UI

### ISSUE THREAD

**Issue by yurivict** [irungentoo/toxcore#1619]
Currently clients have an option "Enable UDP". In practically, UDP will sometimes fail because it might be filtered out in the firewall, or in the proxy server. For example, Tor proxy will always filter out UDP because Tor doesn't support UDP.

Client needs to know if the UDP option is actually working. There should be a feedback allowing to show to the client that UDP is or isn't actually working.

When I select both "Enable UDP" and SOCKS5 proxy pointing to Tor, I am always wondering if UDP packets are actually sent directly to peers, bypassing the proxy, or Tox silently falls back on TCP.

**Comment by GrayHatter** [comment]
This exists, the connection callback you get will tell you if they're connected to TCP or UDP

**Comment by iphydf** [comment]
@yurivict file this issue on your favourite client's (or all of their) issue tracker(s).
