### ISSUE TITLE
toxcore cannot bootstrap when connected to DNS64/NAT64 

### ISSUE THREAD

**Issue by dvor** [irungentoo/toxcore#1620]
I've tried to submit Antidote to the AppStore but it was rejected by Apple because it doesn't work on NAT64 network.

How to reproduce:
- one computer creates NAT64 wifi network ([instruction for macOS](https://derflounder.wordpress.com/2015/10/05/enabling-an-ipv6-only-network-using-internet-sharing-on-el-capitan/))
- connect other computer (or phone) to this network
- launch tox with installed fresh profile, IPv6 enabled, UPD doesn't matter
- observe
- toxcore cannot connect.

Same issue was observed when using latest uTox and qTox.

If you will switch to normal network, let tox to connect, switch back to NAT64, try to connect again - _sometimes_ it may work, but quite often it doesn't.

It would be nice if anyone can tell me how to debug / where to look to fix this issue. I'm quite stuck, also release to the AppStore is blocked by this.

**Comment by GrayHatter** [comment]
@dvor have to tried with ONLY ipv6 bootstraps? 

My first instinct tells me that Tox will find it's place in the DHT, the the only close-peer connections you have are IPv4, that'll break stuff.

Also, you could also try with a private tox network, that's ONLY on IPv6, but that's very hard to maintain. Toxcore will very aggressively bridge any network it can.

Finally, I suggest you consider toktok/c-toxcore for future issues and pulls.

**Comment by GrayHatter** [comment]
according to @dvor the issue seems to be fixed by enabling TCP only mode. This makes me think that

**Comment by GrayHatter** [comment]
@dvor reopen this if you haven't worked it out. But IIRC, you did get it working.

**Comment by dvor** [comment]
No, issues wasn't fixed yet. I'll clone it to c-toxcore.
