### ISSUE TITLE
Repo instructions error

### ISSUE THREAD

**Issue by ilu33** [irungentoo/toxcore#1623]
No idea where to report errors on the website so I try here:

Page "https://tox.chat/download.html#gnulinux" says for Debian:
`echo "deb https://pkg.tox.chat/debian stable $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list`
This will only work on Ubuntu but does not work in a "branded" debian jessie. Just listing the correct entry for Debian would really help instead of some "catchall" code which doesn't catch all in reality.
What is the correct entry needed in tox.list for jessie?

**Comment by GrayHatter** [comment]
This isnt the place, but @nurupo or @optimumtact will help you out

**Comment by GrayHatter** [comment]
or @encrypt

**Comment by cebe** [comment]
@ilu33 the correct repo for debian Jessie is `deb https://pkg.tox.chat/debian stable jessie` as far as I see and the code above prints that to the file for me. What exactly is not working for you?

**Comment by optimumtact** [comment]
he's using something that is a branded version of jessie and hence not officially supported.

**Comment by nurupo** [comment]
I have already replied to this guy's email a couple hours ago.

**Comment by ilu33** [comment]
Thank you for your help.
The code results in "deb https://pkg.tox.chat/debian stable <brandname>" which obviously will not work if the brandname is something else but jessie.

... hence not officially supported ...
It's so easy to include those versions by just supplying the correct line which everybody interested can add manually.
