### ISSUE TITLE
If umask is 0077, /usr/local/include/tox has wrong permissions

### ISSUE THREAD

**Issue by genodeftest** [irungentoo/toxcore#1626]
Steps to reproduce:
1. set your and root umask too 0077
2. clone toxcore repo
3. configure and build toxcore
4. (as root) install toxcore

What happens:
`/usr/local/include/tox/` and `/usr/local/lib/pkconfig/` are created with permissions 700 (`rwx------`)

What should happen:
`/usr/local/include/tox/` and `/usr/local/lib/pkconfig/` should be created world-readable (755 or `rwxr-xr-x`)

Affected version:
Git version from today

**Comment by GrayHatter** [comment]
Is there a reason you want the public tox header directory or files to be world unreadable by default?

Or is this just because you happen to notice unexpected permissions?

**Comment by GrayHatter** [comment]
Also, is there a reason you expect Toxcore to ignore the umask?

**Comment by genodeftest** [comment]
> Is there a reason you want the public tox header directory or files to be world unreadable by default?
No, I don't want these to be unreadable by default.

> Or is this just because you happen to notice unexpected permissions?

Yes. Umask 0077 is non-standard, but a reasonable valid configuration.

> Also, is there a reason you expect Toxcore to ignore the umask?

Yes, toxcore does ignore umask for all other files which are correctly installed, except the two folders noted above. Also most other tools are installing correctly with umask 0077.

**Comment by GrayHatter** [comment]
@genodeftest a umask of 0077 would be `rwx------` so if your umask is set to `0077` and tox is installing `rwx------` then it's obeying your umask.

**Comment by genodeftest** [comment]
> a umask of 0077 would be `rwx------` so if your umask is set to `0077` and tox is installing `rwx------` then it's obeying your umask.
I know, but it shouldn't. When installing software, the umask should be ignored.

**Comment by GrayHatter** [comment]
Why?

**Comment by genodeftest** [comment]
> Why?

Because otherwise the installed software is not working properly. Umask is there to prevent users from accidentially leaking information through files in their /home, in /tmp or /etc (as root) and other places. There is no use in having globally installed files in /usr/local without being readable by everybody.

**Comment by cebe** [comment]
does the umask of unprivileged user still apply when you run `sudo make install`? Shouldn't the umask of root apply then?

**Comment by genodeftest** [comment]
Ok, the folders listed above become `rwx------` during installation.
While running `make install` as root, the folders are created by this command:
`/usr/bin/mkdir -p /usr/local/include/tox` and `/usr/bin/mkdir -p /usr/local/lib/pkconfig/` respectively. Instead they should be created by `/usr/bin/mkdir -m 755 -p /usr/local/include/tox` et al. For files, the permissions are correctly set during `/usr/bin/install -c -m 644 [filename]`.

Running `make install` with umask manually set to 0022 works fine too.

**Comment by cebe** [comment]
are you setting the umask for root?

- If you compile toxcore as unpriv user with a prefix to store it in your home dir you want the umask to apply.
- If you install it globally via sudo, as far as I know (have not tested it) the umask of root applies, which should not be 0077, at least I see no reason why you would do that.
- If you install as root, the same applies as above.

**Comment by genodeftest** [comment]
> are you setting the umask for root?

Yes, I am.

**Comment by cebe** [comment]
I see no reason to do that. Root is not a user that should have personal data in its home directory. It is used to manage the system and therefor a umask of 0077 does not make sense for it.

**Comment by GrayHatter** [comment]
I can't think of a good reason why Toxcore should ignore ANY users umask.
