### ISSUE TITLE
Disable DHT relaying

### ISSUE THREAD

**Issue by palikacska** [irungentoo/toxcore#1629]
I use [uTox](https://github.com/utox/utox) and [Isotoxin](https://github.com/isotoxin/isotoxin) and noticed that all two Tox clients generate some traffic at around 1kB/s. Checked it with a sniffer and looks like encrypted data. Did some Google search and I suppose it's DHT traffic coming from the bootstrap node I connect to. Can DHT traffic relaying be disabled?

I'm behind a firewall (restricted work network) and no other clients or nodes can connect to me. I also cannot connect to any other nodes that do not default to port 443. So I think it's nonsense for me to relay traffic. Or relay among whom? The only node I can communicate with is a TCP relay bootstrap node.

**Comment by pranomostro** [comment]
Hello @palikacska,

most of the development now occurs at toktok/c-toxcore.
I think your issue will find more attention there.

**Comment by GrayHatter** [comment]
You can also disable UDP and use TCP only. Though, UDP is generally consider better for a few reasons.
