### ISSUE TITLE
Login is unreadable on certain dark QT themes

### ISSUE THREAD

**Issue by Malsententia** [irungentoo/toxcore#1632]
![Example](http://i.imgur.com/AA2ow1b.png)

(disclaimer, first time using tox)
I was using a system theme called kvantum ArcDarkTransparent; switching that Breeze Dark fixed the login box, but many parts of the UI are still glaringly white, and look rather out of place with most other apps I use. Perhaps an option to use native colors could be provided? Even when I switch the tox theme to none, or breeze, or kvantum, glaring bright white everywhere.

**Comment by GrayHatter** [comment]
you're looking for https://github.com/qTox/qTox 

Also, does qTox really have a password strength meter? Is it based on feel? or an actual valid measure?

**Comment by Malsententia** [comment]
Oh my bad, I could have sworn I was there. I had both open. Herp derp.
