### ISSUE TITLE
Loosing connectivity with all contacts forever, being online

### ISSUE THREAD

**Issue by UralZima** [irungentoo/toxcore#1634]
Hello. I use latest toxic-9999 and tox-9999 on gentoo. Toxic is connected through Tor with udp disabled.
Toxic reports v0.7.2_r1747

After long use, it loose any connectivity with all contacts, but toxic showing it is online. People on qtox seeing me offline forever, me too.

Right after I restart toxic, connectivity is immediately restored and I see online people, and they see me.

This happens every day (or once per 2 days) for long time. Now when people started reaching me by phone, saying WTF where are you on tox? I decided to create this issue.

Please help.

P.S. I created this issue on toxic, but I think it is CORE-related.

**Comment by doggodanubus** [comment]
I am not a developer. It would however be interesting to have some wireshark captures of this. Have you tried another client?
I have a client on my phone atox and qtox home pc with two different accounts. Neither has show offline in over a week now.

**Comment by GrayHatter** [comment]
Not sure how I missed this before, but the last time this bug came up, it was a consume grade router's NAT table getting filled. Restarting the router/ap, or upgrading to one without a buggy NAT table should fix this issue. Feel free to reopen on the toktok repo if it's still an issue.
