### ISSUE TITLE
What happened with Tox project?

### ISSUE THREAD

**Issue by UralZima** [irungentoo/toxcore#1635]
Hello. What happened with Tox project? Why it is not updating anymore since sep 2016? There are many known unresolved issues. I am worrying. Also, wtf is happening with old domain tox.im? Wth info is there? I heard that this guy stolen money, but now I don't understand what is happening. @irungentoo, can you clarify a little bit? I hope devs weren't killed by ns@

Thanks

**Comment by GrayHatter** [comment]
https://github.com/TokTok/c-toxcore/pulls

**Comment by UralZima** [comment]
Thanks for the url. I didn't knew that. Tox.chat and gentoo overlays still points to irungentoo's github. 
On which lib default clients are built? qtox and utox already uses new fork? Should I update my toxic to new toxcore lib from another repo now?

**Comment by zetok** [comment]
@UralZima `toxic::gentoo`

**Comment by im-grey** [comment]
Yes,
