### ISSUE TITLE
Tox DNS causing KDE Accessible to start automatically in Debian?

### ISSUE THREAD

**Issue by mYnDstrEAm** [irungentoo/toxcore#1640]
I'm running Debian 9.1 with KDE. KDE Accessible kept starting automatically. I had to uninstall it and also had to uninstall tox-dns as it required kaccessible.

Full report including the contents of the accessibility.conf file can be viewed [here](https://unix.stackexchange.com/questions/388218/why-does-kde-accessible-the-screenreader-start-automatically-and-how-to-preven).

Is Tox DNS responsible for this behaviour? Why does it even require KDE Accessibility? Can this dependency please be removed?

**Comment by NyxCode** [comment]
Why would this be related to toxcore?

**Comment by SkyzohKey** [comment]
Tox DNS has been removed from tox a loooong time ago. Checkout the new repository for up-to-date ToxCore => https://github.com/TokTok/c-toxcore

**Comment by mYnDstrEAm** [comment]
I was using the Debian repository which [was shut down in February](https://blog.tox.chat/2018/02/shutdown-of-the-debian-and-ubuntu-package-repository/)
