### ISSUE TITLE
Is tox ready for production or only for testing?

### ISSUE THREAD

**Issue by matteoraggi** [irungentoo/toxcore#1645]
Hi, a friend asked me a solution for videochat and screensharign encrypted, he would use this whitelabel app for work. Can I suggest tox to him or this is not enough stable yet?

**Comment by SkyzohKey** [comment]
You should ask in the TokTok/c-toxcore repository instead. Most of the development to not happens here anymore

**Comment by matteoraggi** [comment]
Done, thanks https://github.com/TokTok/c-toxcore/issues/855
