### ISSUE TITLE
Disable the communication with other tox nodes.

### ISSUE THREAD

**Issue by PmAbi1993** [irungentoo/toxcore#1646]
Can we disable our tox server instance connecting to other bootstrap nodes. The bandwidth used by our instances are huge.

**Comment by SkyzohKey** [comment]
Development have move to [TokTok/c-toxcore](https://github.com/TokTok/c-toxcore). This repository is no longer maintained, please re-open your issue on the c-toxcore issue tracker. ;)

**Comment by chipitsine** [comment]
maybe it makes sense to archive this repo ?

**Comment by PmAbi1993** [comment]
Thank you @SkyzohKey for notifying me :) . I'll re-open it in the correct Repo.

**Comment by GrayHatter** [comment]
@SkyzohKey I'm still maintaining this repo, wtf are you talking about?
