### ISSUE TITLE
[Feature suggestion] A bridge to Matrix

### ISSUE THREAD

**Issue by homebeach** [irungentoo/toxcore#1648]
A bridge between Tox and [Matrix](matrix.org). Here is corresponding issue on [Matrix side](https://github.com/turt2live/matrix-wishlist/issues/145).

**Comment by ghost** [comment]
Linking this here: https://github.com/Sorunome/mx-puppet-tox

**Comment by GrayHatter** [comment]
politely decline to support this... you can ask your clients for support though...
