### ISSUE TITLE
Double unlocking in the ac_iterate 

### ISSUE THREAD

**Issue by ryancaicse** [irungentoo/toxcore#1659]
Hi, developers, it seems there could be a double unlocking error when **!reconfigure_audio_decoder(ac, ac->lp_sampling_rate, ac->lp_channel_count)**, where the lock **ac->queue_mutex** is released twice.

https://github.com/irungentoo/toxcore/blob/bf69b54f64003d160d759068f4816b2d9b2e1e21/toxav/audio.c#L136-L170

Best,

**Comment by ryancaicse** [comment]
Hi, developers @mannol @irungentoo 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by zoff99** [comment]
@ryancaicse can you please check with the currently active incarnation of toxcore --> https://github.com/TokTok/c-toxcore
irungentoo does not have the time to maintain it anymore

**Comment by ryancaicse** [comment]
@zoff99 Hi, thank you. I opened an issue there.
