### ISSUE TITLE
Decentralized friends list suggestion

### ISSUE THREAD

**Issue by Two-Tone** [irungentoo/toxcore#181]
Is there a way of doing a decentralized friends list?  I keep thinking of creating three hashes, private hash, public hash, and second public hash.  I am going to refer to both the first and second public hashes as just first and second hashes.  First hash is used as an identifier, anyone can know it.  Second hash can be thought of as a secret public key (kind of paradox there) and/or as a shared secret.  Only friends can know both.  First hash gets sent to the DHT network, asking if anyone knows the identifier.  People respond with an encrypted message (that contains their first and second hashes, and other relevant info) that can only be encrypted with the second hash.

If someone responds with an encrypted message that can not be decrypted with their private key then they are ignored.

So, private key, public identifier, and secret public key.  Identifier is used to find people who know the key or be found yourself.  Secret public key is only given to friends.  It is more or less used for when someone is trying to rebuild their friends list and as their actual public key.  If a person already has you in your friends list, they automatically send a message off that is encrypted using your secret public key, which when decrypted is verification that they actually know you already.

I think this would work but I am not sure if there is are flaws in it.  I can't think of anything better that is not only decentralized but is also not prone to abuse.

**Comment by GrayHatter** [comment]
stale, and not well defined. please open a new issue that list the problems this suggestion would solve, and why you think this is the best implementation idea
