### ISSUE TITLE
Add local encryption of private key

### ISSUE THREAD

**Issue by ripdog** [irungentoo/toxcore#207]
There's currently a pretty big security hole in that if someone steals your private key (this has happened, for example the bitcoin thefts) they can impersonate you perfectly.

This may not be high priority, but typing a password when launching tox would be a big security win, I think.

**Comment by zetok** [comment]
So… encryption has been available for quite a while, and there are some clients supporting it. Looks like issue should be closed?

**Comment by codedust** [comment]
@irungentoo As zetox already mentioned, this issue can be closed now.
