### ISSUE TITLE
Decide on compression formats

### ISSUE THREAD

**Issue by AnthonySuper** [irungentoo/toxcore#21]
We need to figure out what compression format to use. Theora seems like a good bet, since it has no huge patent issues. We could also possibly use WebM.

For audio, Ogg Vorbis is a pretty obvious choice. I think that getting audio support done first makes the most sense. We could use a 64-bitrate and it would sound okay. However, Vorbis is variable-bitrate, which could cause some problems with transmission.

**Comment by suhr** [comment]
Toxcore uses libvpx and opus now. Close?

**Comment by GrayHatter** [comment]
@irungentoo close
