### ISSUE TITLE
secure communication needs to be anonymous

### ISSUE THREAD

**Issue by hmeyer** [irungentoo/toxcore#356]
As long as the network is observable by third parties (which the internet is) encryption might obfuscate the content of communication. But as we all know by now it's just the metadata of the who and when you communicate with that is sufficient to get a good picture of your communication behaviour and peers.
If Tox wanted to be secure it needs to implement anonymous communications.
Basically Tox + Tor. You already stated this won't be possible and actually that is ok. I'd like to propose to add an onion routing layer to the Tox message protocol. As well as standardized message lengths (filled up with random bytes). Maybe even add sending useless packets in order to obfuscate real traffic from void traffic.
Delay packets. And yes - give up realtime functionality like audio and video.
This way Tox might become a secure instant messenger.
Anyone in for a Para(noid)Tox - Fork?

**Comment by v6** [comment]
// , I'm interested. Does anyone know the best forums to inquire about how to do this? 

I think MAIDSafe, Ethereum, or IPFS technology could be worthwhile avenues to explore.

**Comment by LittleVulpix** [comment]
Wow this necro is real :p this thread is from 2013.

Either way, tox now works in tcp-only mode. At this point, you can simply use your tor as a proxy server for tox and run tox that way.

**Comment by v6** [comment]
Googlebot, lord of the Necroposts, cares little for your silly human
concept of time. Seriously it came up on google.

Cool. Would you be willing to add that response to the stackoverflow post?
Will upvote.

**Comment by suhr** [comment]
What Tox actually needs is an i2p support. We don't need yet another handmade broken anonymization.
See https://github.com/irungentoo/toxcore/issues/942

**Comment by v6** [comment]
// , Just as long as it doesn't get baked into the tox protocol. Tox needs to deal with that like it needs a hole in the head.

**Comment by fcore117** [comment]
someone who so needs a hide their ip then use torchat or https://www.onioncat.org/about-onioncat/ use something like this with Tox.

**Comment by GrayHatter** [comment]
@irungentoo close as wontfix, tox works over tor,
