### ISSUE TITLE
Make more Black-Box like

### ISSUE THREAD

**Issue by AnthonySuper** [irungentoo/toxcore#37]
White trying to write an Obj-C wrapper for this (for ease of porting to iOS and OSX), I ran into some issues. Mainly the fact that, by default, the messenger core uses global arrays. 

In my mind, a good version of the messenger would be completely independent of the friendlist implementation, and would only deal with client IDs as a result. This would make writing wrappers in other languages easier, in turn making the project more usable.

Of course, this is a major change that is not strictly necessary, so it's very open to debate.

Does anybody agree?

**Comment by suhr** [comment]
May be closed, I presume?

**Comment by GrayHatter** [comment]
@irungentoo close
