### ISSUE TITLE
cmake issues

### ISSUE THREAD

**Issue by CharmlessCoin** [irungentoo/toxcore#390]
In 6930b5d35d5373c879502b0a719f7cf11b05c70c I changed an exposed API function, travis failed it, due to nTox not compiling correctly. nTox issues aside, if travis is checking *every* file, changing an exposed API is going to be a massive headache. This surely isn't intended behavior, is it?

**Comment by codedust** [comment]
@irungentoo As mentioned by diantahoc, this issue can be closed.
