### ISSUE TITLE
SRTP and ZRTP

### ISSUE THREAD

**Issue by kebertx** [irungentoo/toxcore#406]
I'm hearing talk that people are starting work on the VoIP stuff, which sounds fantastic.

Someone on 4chan evidently too dense to create an issue on GitHub seems to think it is very important to use SRTP and ZRTP for secure messaging.

http://en.wikipedia.org/wiki/Secure_Real-time_Transport_Protocol
https://en.wikipedia.org/wiki/ZRTP

I'm inviting him to elaborate on this, because I think that such things should be whined about on github and not 4chan.

Cheers, everybody!

**Comment by GrayHatter** [comment]
@irungentoo close
