### ISSUE TITLE
Web RTC 

### ISSUE THREAD

**Issue by Latrasis** [irungentoo/toxcore#44]
Are there any useful things we could do/borrow with/from Web RTC, or has development gone too far for Web API to be useful at this point?

https://www.youtube.com/watch?v=p2HzZkd2A40
http://www.webrtc.org/

**Comment by jscinoz** [comment]
I'm intending to do a JS implementation of the Tox protocol based on WebRTC data channels. Initially, much like #942, this will be a separate Tox network, disconnected from the main one.

At a later date, and if warranted, [librtcdc](https://github.com/xhs/librtcdc) could be used to add support for this transport to toxcore, to allow native Tox clients bridge the two networks. Again, similar to #942, this would presumably also require DHT changes to represent the new type of node.

When I have a chance to start working on all this (probably late December), I'll add a link to the repository in a comment in this thread.
