### ISSUE TITLE
Coding style violations.

### ISSUE THREAD

**Issue by aaboagye** [irungentoo/toxcore#453]
What's the point of having a coding style if no one follows it? I'm looking through the code base now and there are violations left and right.

I propose that we clean up the entire code base now. The reason I say this is that the code should adhere to the coding style document before it gets even larger and becomes unfeasible to correct.

Also, the current style document has a lot of good guidelines in there already. However, I'd like to propose that we change to Allman style. 

http://en.wikipedia.org/wiki/Indent_style#Allman_style

Using this style will help with readability and more importantly prevent coding errors due to dangling braces and the such. Furthermore, I'd like to propose that even one-line if statements have braces. It may seem cumbersome at first, but I feel that it's better. There's no ambiguity and if someone wants to expand the if block, they can without having to add a brace.

I don't mind taking this task myself. I could easily run all the files through a linter such as astyle and change all offending blocks of code.

Also, there are some issues with placing macro definitions. Macro definitions, struct definitions, and function prototypes should all go in header files. Macros should be in ALL_CAPS.

Again, I don't mind doing this task. But clean code is better for everyone.

Thanks,

--

Aseda Aboagye

**Comment by GrayHatter** [comment]
closed as stale, open a new issue, or better yet a pull request
