### ISSUE TITLE
fast lossless UDP protocol

### ISSUE THREAD

**Issue by joshuaar** [irungentoo/toxcore#570]
I'm not sure where you guys are at regarding your UDP protocol, but I thought I'd leave this here in case anybody is interested. I've used it before with hole punching and it works quite well.

http://udt.sourceforge.net/

**Comment by landswellsong** [comment]
@synctext  Hello. One question about that, is there a plain C implementation out there?

**Comment by wiseoldman95** [comment]
There's also Google's QUIC.
