### ISSUE TITLE
Tox portability 

### ISSUE THREAD

**Issue by aafaba** [irungentoo/toxcore#574]
Interesting  project, if it has an OS abstraction layer would be better for porting to other platforms, especially for embedded  platforms.

At this point, PJSIP (www.pjsip.org) is a good example.  May be we can learn something from it. its code is very clean and less third party dependent.

**Comment by codedust** [comment]
@irungentoo This might be closed as all major plattforms are supported by toxcore right now.

**Comment by Impyy** [comment]
@codedust But toxcore still doesn't compile with msvc.

**Comment by codedust** [comment]
@Impyy You might be looking for #418

**Comment by Impyy** [comment]
@codedust I'm not. Compiling using mingw or similar is not an option in some cases.

**Comment by codedust** [comment]
@Impyy I don't know why someone would want to compile tox with a propietary compiler when there is a free alternative. But maybe there might be people out there who would want to do that. ;)

**Comment by Impyy** [comment]
@codedust One of those people would be me. In order to get a tox application in the windows store or the windows phone store toxcore has to be compiled with msvc. I have to maintain my own fork of toxcore that compiles with msvc so I can't really consider this "portable".

**Comment by codedust** [comment]
@Impyy Does the windows store really *require* compiling with msvc or do you prefer compiling with msvc because it seems to be more convenient?

**Comment by GrayHatter** [comment]
@Impyy if you can open a PR to make core compile in MSVC that would be awesome...
