### ISSUE TITLE
libsodium link in the install docs not working

### ISSUE THREAD

**Issue by ProfOak** [irungentoo/toxcore#700]
The Windows instructions point to the URL of a library you need to install and the website is down.

https://github.com/irungentoo/ProjectTox-Core/blob/master/INSTALL.md#windows

I understand that Tox has no control over their website but can we add the github repo of libsodium as an alternative download?

https://github.com/jedisct1/libsodium

**Comment by GrayHatter** [comment]
@irungentoo  close fixed
