### ISSUE TITLE
Why Metadata Matters

### ISSUE THREAD

**Issue by dfortner** [irungentoo/toxcore#711]
![](http://i.imgur.com/COvMNiR.jpg)

**Comment by dfortner** [comment]
I am reopening this since I've became aware Tox still leaks metadata to strong adversaries such as your ISP, the NSA, GCHQ, etc.
Tox developers say "just use Tox through Tor", but that isn't user-friendly and doesn't solve the metadata issue for ***most*** users (the average joe Tox advertises itself to).
Please be more open that using Tox the government and some private companies (like your ISP) might collect your metadata.

**Comment by dubslow** [comment]
That's true of literally all your traffic ever, that's the definition of metadata. The only "solution" is Tor, or our own homegrown Tor-like network, which would be a massive waste of already scant resources.

When you post on Github you also leak the same metadata, but I don't see you complaining about your web browser or about Github...

**Comment by ArchangeGabriel** [comment]
Because when I post on GitHub, I know this is happening and currently don’t care much about this (but in an ideal world, I should care and this must be important).

However, I expect from Tox, claiming to be a secure messaging app that don’t let governments know to who I’m talking, not to leak metadata.

**Comment by irungentoo** [comment]
The only way to "solve" this right now is onion route everything which will cripple the performance of Tox to levels where you will only be able to use it properly for text chat.

This will be solved properly at some time in the future when people stop having horrible upload speeds.
