### ISSUE TITLE
Create a Whitepaper

### ISSUE THREAD

**Issue by dfortner** [irungentoo/toxcore#712]

**Comment by dfortner** [comment]
Good work, @Proplex 
Too bad you left Tox
What happened?

**Comment by flamsmark** [comment]
If this issue is closed then where's the whitepaper?

**Comment by JacobHenner** [comment]
@flamsmark I'm going to guess that @GrayHatter closed this as stale during yesterday's housekeeping. I still think an RFC would be a wise idea, #1445

**Comment by subliun** [comment]
https://github.com/Tox-Docs/Text

**Comment by flamsmark** [comment]
Is that actually compiled somewhere?
