### ISSUE TITLE
MinGW build error, autoreconf -i

### ISSUE THREAD

**Issue by frankred** [irungentoo/toxcore#719]
I installed mingw and libsodium, everything worked fine. If i want to build Tox-Core I get the following error during the "autoreconf -i" command....:

Can't locate Autom4te/ChannelDefs.pm in @INC (@INC contains: /mingw/share/autoconf /usr/lib/perl5/5.8/msys /usr/lib/perl5/5.8 /usr/lib/perl5/site_perl/5.8/msys /usr/lib/perl5/site_perl/5.8 /usr/lib/perl5/site_perl/5.8 /usr/lib/perl5/vendor_perl/5.8/msys /usr/lib/perl5/vendor_perl/5.8 /usr/lib/perl5/vendor_perl/5.8 .) at /c/workspace_c/mingw/bin/autoreconf-2.68 line 40.
BEGIN failed--compilation aborted at /c/workspace_c/mingw/bin/autoreconf-2.68 line 40.

Someone can help me? I'm completly new to MinGW...

**Comment by anubiann00b** [comment]
You can't use the `mount` command on certain versions of windows (Windows 8). Is there an alternative way to get that to work?

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it's a very old support issue that doesn't apply to the latest version of toxcore anymore.

**Comment by GrayHatter** [comment]
yeah, this can be closed

**Comment by Hikaru-Furuta** [comment]
I'm using windows10
suffering the same error
and also tried what you had told
`mount c:/mingw C/mingw
mount: warning - C/mingw does not exist.
mount: C/mingw: Invalid argument`

How can I solve this
Can anyone help me?

**Comment by xuleiisprogrammer** [comment]
@Hikaru-Furuta 
Have you solved the problem, sir?
I'm suffering the same error

**Comment by zoff99** [comment]
@xuleiisprogrammer the active toxcore fork is here: https://github.com/TokTok/c-toxcore
irungentoo does not have the time to maintain it anymore.

**Comment by xuleiisprogrammer** [comment]
I have solved this problem

**Comment by xuleiisprogrammer** [comment]
https://gist.github.com/shinchiro/705b0afcc7b6c0accffba1bedb067abf
