### ISSUE TITLE
Allow clients to send custom metadata

### ISSUE THREAD

**Issue by thereals0beit** [irungentoo/toxcore#731]
It seems you could allow clients to send metadata to one another to be optionally interpreted by clients. I think this already exists to a limited(?) extent, since name, status text, status state is sent to other clients.

The issue is that this metadata is static (see 'Friend' struct in 'Messenger.h') and can not be expanded to include things like (ignoring privacy concerns, but just pulling examples from Skype) website/age/birthday/"about me"/gender/location/phone number. Client developers could use the underlying protocol to make whatever chat client they want using the tox network, and clients that don't support the metadata being sent (Client A sends 'phone' field, but Client B does not send or expect to receive this information) could simply ignore it.

I understand that this might splinter client functionality, but I think it would give developers some freedom in design.

Of course you'd have to cap this metadata field to prevent headaches, but I don't see any issues beyond those two.

**Comment by GrayHatter** [comment]
stale, perhaps fixed with the custom_packet api?
