### ISSUE TITLE
Groupchat topics

### ISSUE THREAD

**Issue by Xe** [irungentoo/toxcore#740]
Much like IRC. Enough said.

**Comment by aaannndddyyy** [comment]
Topic and names are already implemented in the new groupchats, so I guess this ticket can be closed.

**Comment by zetok** [comment]
@aaannndddyyy Not really, since they aren't merged into core.

**Comment by GrayHatter** [comment]
@irungentoo close, replaced by new groupchats

**Comment by suhr** [comment]
@GrayHatter New groupchats are not merged yet.
