### ISSUE TITLE
Toxic splitts, while Venom stays connected

### ISSUE THREAD

**Issue by zetok** [irungentoo/toxcore#759]
![2014-02-23 venom and toxic comparison - toxic strange splitting](https://f.cloud.github.com/assets/3148759/2237243/a4dc06fe-9b99-11e3-9152-acd04e0f0d7f.png)
↑ comparison between Venom and Toxic, while Toxic experiences something 'split alike'.

Beside easily noticeable problems:
• What is written in Toxic is shown in Venom, also other peers seem to see it
• Messages by other peers aren't displayed in Toxic, but are in Venom
• From time to time list of connected peers fluctuates rapidly by ~ 30-60%. At all time number of connected peers in Toxic differs from number in Venom.

**Comment by codedust** [comment]
@irungentoo This issue can be closed as Venom is discontinued.

**Comment by GrayHatter** [comment]
@irungentoo close stale, fixed, replaced
