### ISSUE TITLE
suggestion to wave next user migration

### ISSUE THREAD

**Issue by lestofante** [irungentoo/toxcore#766]
Hi,
this is a suggestion.
As we all know some day ago Watsapp crashed, creating a mass migration to the similar, and almost free, app Telegram. Also that app server's crashed under the load of 1.600.000 regristation at hour (see telegram twitter's page).
that should not appen in tox, at least in theory.

I've talked with a lot of people that has do the jump, many of them has eloged the fact that you can install it on multiple device still using one account, and none of them was willing to renounce to off-line messaging.

Because that are the basic requisite i think that should be implemented first, so the next Watsupp/Telegram/whatever blackout will see tox gui, even if experimental, an apetible alternative, and finally the protocol can put on heavy test and begin to gain notoriety.

Then audio and video will be a "plus" feature that can be added later.

tox should only give some way to "group" many ID into a unique user in a safe way, and also inform all ID friend of the new/deleted ID in group.

offline message should work in single and group chat, but because they are less secure, and they are not reitable (i'm thinking about somethink like Gossip Protocol), to the above implementation it should be clear that it is using offline messagge. So maybe a different call is needed.

**Comment by GrayHatter** [comment]
@irungentoo close as dup

**Comment by saulius2** [comment]
Does the issue #766 of toxcore duplicates the issue #199 of Venom ?  I thought the relation should be done in opposite direction.

BTW, if BitMessage can do offline delivery via p2p then nothing prevents ToX from doing the same, IMO.
https://bitmessage.org/wiki/FAQ#Can_I_send_a_message_to_someone_that_is_offline
