### ISSUE TITLE
API const correctness

### ISSUE THREAD

**Issue by polymeris** [irungentoo/toxcore#842]
It's been a while since I last coded C, so I might be missing something here, but why are parameters of API calls like the `message` in
``` c
uint32_t tox_send_message(Tox *tox, int32_t friendnumber, uint8_t *message, uint32_t length);
```

not declared `const`?
It's not going to be modified (I hope) down the line... and, in this particular case, looking into the code it actually gets copied to another buffer in Messenger.c:415:

``` c
memcpy(temp + sizeof(theid), message, length);
```

This forces any consumers to make unnecessary copies of the message before feeding them to the API. Also, declaring parameters `const` helps the compiler generate more efficient code.

EDIT: I see issue #598 is related, but the discussion seems to focus on the type size, not constantness. To be clear, i am suggesting using `const uint8_t *`.

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it refers to an outdated version of the Tox API.
