### ISSUE TITLE
Network usage is high

### ISSUE THREAD

**Issue by 24566342** [irungentoo/toxcore#855]
Doing a little watching of data traffic shows data usage is rather high for tox:

60 seconds 0 friends = 560kb
60 seconds 20 friends = 1.40mb

Comes out to around 2gb for 24 hours with 20 friends. This would burn through anyone with data caps on their Internet and would certainly burn through it on a phone data plan.

**Comment by Snorflake** [comment]
https://github.com/notsecure/uTox/issues/1147

still high
