### ISSUE TITLE
High CPU usage with unaccepted friend requests

### ISSUE THREAD

**Issue by 24566342** [irungentoo/toxcore#856]
Both Toxic and Venom client show high cpu usage when friend requests are unaccepted. Having 0 unaccepted friend requests shows about 3% cpu usage, adding around 4 friends who don't accept the request puts this up to around 14%. Removing the friends goes back down to 2-3%.

**Comment by codedust** [comment]
@irungentoo This issue can be closed as it either has never been a problem or has been fixed already.

**Comment by zetok** [comment]
@codedust this has been a problem.

As for whether it has been fixed - someone should test that.

**Comment by codedust** [comment]
I tested it when I commented to the issue. Didn't notice any suspicious CPU load.

**Comment by GrayHatter** [comment]
at me if you can duplicate it on demand, or have a log from toxcore
