### ISSUE TITLE
we need api to get friend_id from peer_id (in group chat)

### ISSUE THREAD

**Issue by r-ku** [irungentoo/toxcore#859]
tox really needs such api:

    int get_friend_from_group_peer(int group_id, int peer_id)

Now apparently there is no way to figure out which group chat peer is which friend in our contacts. Now imagine chat client that can set custom local alias to contact. There is no way to use that custom alias in group chat. Furthermore there is no way to uniquely identify peer in group chat, because when peers come and leave their ids get reused. Problem here is if client wishes to properly update aliases of message senders in group chat there must be some kind of mapping between peer and message so whenever peer name changes all names next to message can be updated. since peer_id can be taken by other peer at later point it is no longer possible to do this.

**Comment by GrayHatter** [comment]
@irungentoo close as replaced by new groupchats (COMING SOON™)
