### ISSUE TITLE
High delays in audio calls.

### ISSUE THREAD

**Issue by iqualfragile** [irungentoo/toxcore#925]
Today i was testing audio calls with a friend, connection was between utox and toxic, both compiled today.
At first everything worked as expected, but after a while the delay between either of us talking and the other one hearing the voice grew greater and greater. Restarting the clients and re initiating the call fixed that. Should still be fixed.

**Comment by hotoiledgoblinsack** [comment]
I wanted to chime in and mention I also have this issue, but instead the delay was already present from the start of the conversation. We both have high bandwidth and low latency connections and are only a few blocks away, other applications such as Skype and Mumble have the desired low latency. I've already reported this issue at qTox [1] but figured this may instead be an issue with the core.

[1] https://github.com/tux3/qTox/issues/2021

**Comment by Chuongv** [comment]
All the audio and video will be replaced with a new api soon. So hopefully this won't be a non-issue afterwards. https://github.com/irungentoo/toxcore/pull/1375

**Comment by GrayHatter** [comment]
@zetok qTox issue? Either way, NEWAPIYAY
