### ISSUE TITLE
Audio sometimes repeats

### ISSUE THREAD

**Issue by iqualfragile** [irungentoo/toxcore#927]
Using toxic, compiled today.
In a call a short bit of audio was played twice every once in a while, guess that relates to packet losses.
This can be handled better, by for example just not playing anything or sending some error correction codes and trying to fix the error.

**Comment by zetok** [comment]
@GrayHatter why is it closed? Please reopen.

**Comment by GrayHatter** [comment]
I'll reopen if you can repeat this in a client on new ToxAV

**Comment by zetok** [comment]
@GrayHatter why are you closing something without confirming first that behaviour is no longer reproducible?

New av is not merged yet. It *most likely* is going to be merged quite fast, but even that doesn't constitute this problem being fixed.
