### ISSUE TITLE
Intermittent Crashes

### ISSUE THREAD

**Issue by Talierch** [irungentoo/toxcore#993]
I am running Windows 7 64bit SP 1
Random crashes occur with no apparent precursor 

  Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	win64-0.1.0.exe
  Application Version:	0.0.0.0
  Application Timestamp:	53d83791
  Fault Module Name:	win64-0.1.0.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	53d83791
  Exception Code:	c0000005
  Exception Offset:	00000000001505f7
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	c863
  Additional Information 2:	c8634068cd54b5beea351bea9bc0a782
  Additional Information 3:	39b5
  Additional Information 4:	39b563378470c4f4cb40d5604aa93bcb

**Comment by codedust** [comment]
@irungentoo This issue can be closed as its not related to toxcore and has probably already been fixed.
